# Libraries

In [1]:
import pandas as pd
import numpy as np

# Load promoters

In [10]:
df_promoters = pd.read_csv("datasets\\1_promoters.csv")

In [13]:
df_promoters.head(2)

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,Promoter -35 box start,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced
0,RDBECOLIOPC00001,ispDF,reverse,RDBECOLITUC01454,ispDF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,1097710.0,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT

In [20]:
# Selection of rows with "Promoter sequence"
df_promoters = df_promoters[df_promoters["Promoter sequence"].notnull()]
df_promoters.reset_index(drop=True, inplace=True)
df_promoters

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,Promoter -35 box start,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced
0,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,1097710.0,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT
1,RDBECOLIOPC00006,folA,forward,RDBECOLITUC02413,folA,folA,RDBECOLIPMC03546,folAp,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,49763.0,49768.0,GTCGAC,49787.0,49792.0,TATAGT,W,GACGGTTTACGCTTTACG,GTCGACGACGGTTTACGCTTTACGTATAGT
2,RDBECOLIOPC00007,ybaB-recR,forward,RDBECOLITUC01879,ybaB-recR,ybaB,RDBECOLIPMC00539,ybaBp,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,493676.0,493681.0,CAACTT,493698.0,493702.0,TCGAA,S,TCGCTACCAAAACTGG,CAACTTTCGCTACCAAAACTGGTCGAA
3,RDBECOLIOPC00010,ytjB-lplA,reverse,RDBECOLITUC02469,ytjB-lplA,ytjB,RDBECOLIPMC03716,ytjBp,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,NaN,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN
4,RDBECOLIOPC00012,yohJK,forward,RDBECOLITUC00762,yohJK,yohJ,RDBECOLIPMC00555,yohJp,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,NaN,NaN,NaN,NaN,NaN,NaN,W,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2276,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02233,pstSCA,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911600.0,3911605.0,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT
2277,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02234,pstS,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911600.0,3911605.0,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT
2278,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02235,pstSCAB-phoU,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911600.0,3911605.0,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT
2279,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02258,pstB-phoU,pstB,RDBECOLIPMC02689,pstBp2,sigma38,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,3908582.0,3908587.0,CTGGCG,3908561.0,3908571.0,TTGCGAAGAAT,S,CGCGTTGTTT,CTGGCGCGCGTTGTTTTTGCGAAGAAT
2280,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC03237,pstSCAB-phoU,pstS,RDBECOLIPMC03521,pstSp,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911603.0,3911608.0,TTACAT,3911576.0,3911581.0,TATTTT,S,ATAACTGTCACCTGTTTGTCC,TTACATATAACTGTCACCTGTTTGTCCTATTTT

In [25]:
# Selection of unique sequences
df_promoters = df_promoters.drop_duplicates(subset=["Promoter sequence"], keep="first")
df_promoters

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,Promoter -35 box start,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced
0,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,1097710.0,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT
1,RDBECOLIOPC00006,folA,forward,RDBECOLITUC02413,folA,folA,RDBECOLIPMC03546,folAp,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,49763.0,49768.0,GTCGAC,49787.0,49792.0,TATAGT,W,GACGGTTTACGCTTTACG,GTCGACGACGGTTTACGCTTTACGTATAGT
2,RDBECOLIOPC00007,ybaB-recR,forward,RDBECOLITUC01879,ybaB-recR,ybaB,RDBECOLIPMC00539,ybaBp,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,493676.0,493681.0,CAACTT,493698.0,493702.0,TCGAA,S,TCGCTACCAAAACTGG,CAACTTTCGCTACCAAAACTGGTCGAA
3,RDBECOLIOPC00010,ytjB-lplA,reverse,RDBECOLITUC02469,ytjB-lplA,ytjB,RDBECOLIPMC03716,ytjBp,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,NaN,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN
4,RDBECOLIOPC00012,yohJK,forward,RDBECOLITUC00762,yohJK,yohJ,RDBECOLIPMC00555,yohJp,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,NaN,NaN,NaN,NaN,NaN,NaN,W,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01708,pstS,pstS,RDBECOLIPMC03521,pstSp,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911603.0,3911608.0,TTACAT,3911576.0,3911581.0,TATTTT,S,ATAACTGTCACCTGTTTGTCC,TTACATATAACTGTCACCTGTTTGTCCTATTTT
2271,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01710,pstB-phoU,pstB,RDBECOLIPMC00234,pstBp3,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,3908474.0,3908479.0,TTTTTG,3908453.0,3908458.0,AACACT,W,ACTCTGTACACGGTT,TTTTTGACTCTGTACACGGTTAACACT
2272,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01907,pstCAB-phoU,pstC,RDBECOLIPMC00511,pstCp,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,3910575.0,3910580.0,CTGGAT,3910552.0,3910557.0,TAGTGT,S,TACGCCAGCCTGCCGGA,CTGGATTACGCCAGCCTGCCGGATAGTGT
2273,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01908,pstB-phoU,pstB,RDBECOLIPMC00512,pstBp1,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,3908584.0,3908589.0,TTCTGG,3908561.0,3908566.0,AAGAAT,S,CGCGCGTTGTTTTTGCG,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT
2274,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01909,phoU,phoU,RDBECOLIPMC00513,phoUp,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,3907697.0,3907702.0,CGGCGT,3907672.0,3907677.0,GATTGA,S,TTATGTACCTGGGCGAATT,CGGCGTTTATGTACCTGGGCGAATTGATTGA

In [32]:
# Selection of genes controlled by a single promoter
df_promoters = df_promoters[~df_promoters["TU first gene"].duplicated(keep=False)]
df_promoters.reset_index(drop=True, inplace=True)
df_promoters

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,Promoter -35 box start,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced
0,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,1097710.0,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT
1,RDBECOLIOPC00006,folA,forward,RDBECOLITUC02413,folA,folA,RDBECOLIPMC03546,folAp,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,49763.0,49768.0,GTCGAC,49787.0,49792.0,TATAGT,W,GACGGTTTACGCTTTACG,GTCGACGACGGTTTACGCTTTACGTATAGT
2,RDBECOLIOPC00007,ybaB-recR,forward,RDBECOLITUC01879,ybaB-recR,ybaB,RDBECOLIPMC00539,ybaBp,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,493676.0,493681.0,CAACTT,493698.0,493702.0,TCGAA,S,TCGCTACCAAAACTGG,CAACTTTCGCTACCAAAACTGGTCGAA
3,RDBECOLIOPC00010,ytjB-lplA,reverse,RDBECOLITUC02469,ytjB-lplA,ytjB,RDBECOLIPMC03716,ytjBp,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,NaN,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN
4,RDBECOLIOPC00012,yohJK,forward,RDBECOLITUC00762,yohJK,yohJ,RDBECOLIPMC00555,yohJp,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,NaN,NaN,NaN,NaN,NaN,NaN,W,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,RDBECOLIOPC03555,metY-yhbC-nusA-infB-rbfA-truB-rpsO-pnp,reverse,RDBECOLITUC03341,rimP-nusA-infB,rimP,RDBECOLIPMC02961,rimPp,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,3318205.0,3318210.0,TTCCCT,3318182.0,3318187.0,TATACT,C,TAGAGTCCTTTTTCAAA,TTCCCTTAGAGTCCTTTTTCAAATATACT
1235,RDBECOLIOPC03556,yceJI,reverse,RDBECOLITUC00391,yceJI,yceJ,RDBECOLIPMC03147,yceJp,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,1119102.0,1119107.0,TTGCAA,1119079.0,1119084.0,CATTTT,W,TTCATTCTCCGACACGC,TTGCAATTCATTCTCCGACACGCCATTTT
1236,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01708,pstS,pstS,RDBECOLIPMC03521,pstSp,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,3911603.0,3911608.0,TTACAT,3911576.0,3911581.0,TATTTT,S,ATAACTGTCACCTGTTTGTCC,TTACATATAACTGTCACCTGTTTGTCCTATTTT
1237,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01907,pstCAB-phoU,pstC,RDBECOLIPMC00511,pstCp,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,3910575.0,3910580.0,CTGGAT,3910552.0,3910557.0,TAGTGT,S,TACGCCAGCCTGCCGGA,CTGGATTACGCCAGCCTGCCGGATAGTGT
1238,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01909,phoU,phoU,RDBECOLIPMC00513,phoUp,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,3907697.0,3907702.0,CGGCGT,3907672.0,3907677.0,GATTGA,S,TTATGTACCTGGGCGAATT,CGGCGTTTATGTACCTGGGCGAATTGATTGA

In [33]:
promoters_list = df_promoters["TU first gene"]
promoters_list

0       serX
1       folA
2       ybaB
3       ytjB
4       yohJ
        ...
1234    rimP
1235    yceJ
1236    pstS
1237    pstC
1238    phoU
Name: TU first gene, Length: 1239, dtype: object

# Load gene expression

In [2]:
df_count = pd.read_csv("datasets\\2_geneExpression_count.csv")
df_fpkm = pd.read_csv("datasets\\2_geneExpression_fpkm.csv")
df_tpm = pd.read_csv("datasets\\2_geneExpression_tpm.csv")

In [8]:
df_count.drop(columns=["Unnamed: 0"], inplace=True)
df_fpkm.drop(columns=["Unnamed: 0"], inplace=True)
df_tpm.drop(columns=["Unnamed: 0"], inplace=True)

In [9]:
df_count.head(1)

,dataset id,thrL,thrA,thrB,thrC,yaaX,yaaA,yaaJ,talB,mog,...,yjjX,ytjC,rob,creA,creB,creC,creD,arcA,yjjY,yjtD
0,GENE_EXPRESSION_ERR1218301,134.008417,558.811303,208.794984,308.636949,44.796015,147.674998,111.230782,3328.571674,191.332131,...,84.656875,192.471013,2025.311346,72.129176,29.610925,49.731169,18.981362,3105.350855,835.559564,77.443958

# Load TF dataset

In [50]:
df_TFs = pd.read_csv("RegulonDB\\RegulonDB_v12\\TFactors.csv", sep="\t")

In [54]:
df_TFs.head(1)

,1)riId,2)riType,3)regulatorId,4)regulatorName,5)cnfName,6)tfrsID,7)tfrsLeft,8)tfrsRight,9)strand,10)tfrsSeq,...,18)tfrsDistTo1Gene,19)targetTuOrGene,20)confidenceLevel,21)tfrsEvidence,22)riEvidence,23)addEvidence,24)riEvTech,25)riEvCategory,26)tfrsPMIDS,27)riPMIDS
0,RDBECOLIRIC00001,tf-promoter,RDBECOLITFC00023,GadW,GadW,RDBECOLIBSC01689,3653866.0,3653885.0,forward,atcagacaggTTTACGTTACTATCAGGCATatcacctcag,...,"-85,5",RDBECOLITUC03133:slp-dctR,W,COMP-AINF-SIMILAR-TO-CONSENSUS:W,EXP-IEP-GENE-EXPRESSION-ANALYSIS:W,NaN,expression|non-experimental,Classical expression|non-experimental,18808381,12730179;18808381

In [59]:
df_TFs_reduced = df_TFs.drop(columns=["2)riType",
                                        "5)cnfName",
                                        "6)tfrsID",
                                        "7)tfrsLeft",
                                        "8)tfrsRight",
                                        "9)strand",
                                        "14)tss",
                                        "15)sigmaF",
                                        "16)tfrsDistToPm",
                                        "18)tfrsDistTo1Gene",
                                        "21)tfrsEvidence",
                                        "23)addEvidence",
                                        "24)riEvTech",
                                        "25)riEvCategory",
                                        "26)tfrsPMIDS",
                                        "27)riPMIDS "])

In [61]:
df_TFs_reduced

,1)riId,3)regulatorId,4)regulatorName,10)tfrsSeq,11)riFunction,12)promoterID,13)promoterName,17)firstGene,19)targetTuOrGene,20)confidenceLevel,22)riEvidence
0,RDBECOLIRIC00001,RDBECOLITFC00023,GadW,atcagacaggTTTACGTTACTATCAGGCATatcacctcag,repressor,RDBECOLIPMC03419,slpp,slp,RDBECOLITUC03133:slp-dctR,W,EXP-IEP-GENE-EXPRESSION-ANALYSIS:W
1,RDBECOLIRIC00002,RDBECOLITFC00023,GadW,tgaaataaaaATATCTGATTTTGATATTTTccatcaacat,activator,RDBECOLIPMC04032,hdeAp,hdeA,RDBECOLITUC03315:hdeAB-yhiD,S,EXP-IEP-GENE-EXPRESSION-ANALYSIS:W
2,RDBECOLIRIC00003,RDBECOLITFC00088,GalR,atcatcacaaCTGAAACCGATTACACcaaccacaac,repressor,RDBECOLIPMC02833,galPp,galP,RDBECOLITUC02515:galP,C,NaN
3,RDBECOLIRIC00004,RDBECOLITFC00033,GalS,atcatcacaaCTGAAACCGATTACACcaaccacaac,repressor,RDBECOLIPMC02833,galPp,galP,RDBECOLITUC02515:galP,C,NaN
4,RDBECOLIRIC00005,RDBECOLITFC00088,GalR,ttattcggttTTCACAGTTGTTACATttcttttcag,repressor,RDBECOLIPMC02833,galPp,galP,RDBECOLITUC02515:galP,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5601,RDBECOLIRIC06280,RDBECOLITFC00093,Fur,aaaaaagaatAAAAATAAGAATTATTATTgctgtgcgcg,repressor,NaN,NaN,yojI,RDBECOLIGNC01975:yojI,S,EXP-HTP-HEP-RNA-SEQ:W
5602,RDBECOLIRIC06281,RDBECOLITFC00093,Fur,NaN,activator,NaN,NaN,yqeC,RDBECOLIGNC04306:yqeC,W,EXP-HTP-HEP-RNA-SEQ:W
5603,RDBECOLIRIC06282,RDBECOLITFC00093,Fur,NaN,activator,NaN,NaN,yqeB,RDBECOLIGNC04305:yqeB,W,EXP-HTP-HEP-RNA-SEQ:W
5604,RDBECOLIRIC06283,RDBECOLITFC00093,Fur,aggttttcggTGTATTTATTCTCAATCCGtttcagcacg,activator,NaN,NaN,yqhD,RDBECOLITUC01026:yqhD-dkgA,S,EXP-HTP-HEP-RNA-SEQ:W
5605,RDBECOLIRIC06284,RDBECOLITFC00093,Fur,attagaagtgTTTGAGAAACTGGAAGCAAaagtacagca,activator,NaN,NaN,zapB,RDBECOLIGNC01805:zapB,S,EXP-HTP-HEP-RNA-SEQ:W

In [62]:
genes_with_TF = df_TFs_reduced["17)firstGene"]

In [67]:
genes_with_TF = list(set(genes_with_TF))

# Filter gene expression datasets

In [40]:
all_genes_in_geneexpression = list(df_count.columns)

In [43]:
all_genes_in_geneexpression

['dataset id',
 'thrL',
 'thrA',
 'thrB',
 'thrC',
 'yaaX',
 'yaaA',
 'yaaJ',
 'talB',
 'mog',
 'satP',
 'yaaW',
 'mbiA',
 'yaaI',
 'dnaK',
 'dnaJ',
 'insL1',
 'hokC',
 'mokC',
 'nhaA',
 'nhaR',
 'insB1',
 'insA1',
 'rpsT',
 'yaaY',
 'ribF',
 'ileS',
 'lspA',
 'fkpB',
 'ispH',
 'rihC',
 'dapB',
 'carA',
 'carB',
 'caiF',
 'caiE',
 'caiD',
 'caiC',
 'caiB',
 'caiA',
 'caiT',
 'fixA',
 'fixB',
 'fixC',
 'fixX',
 'yaaU',
 'kefF',
 'kefC',
 'folA',
 'apaH',
 'apaG',
 'rsmA',
 'pdxA',
 'surA',
 'lptD',
 'djlA',
 'yabP',
 'yabQ',
 'rluA',
 'rapA',
 'polB',
 'araD',
 'araA',
 'araB',
 'araC',
 'yabI',
 'thiQ',
 'thiP',
 'thiB',
 'sgrR',
 'sgrT',
 'setA',
 'leuD',
 'leuC',
 'leuB',
 'leuA',
 'leuL',
 'leuO',
 'yabR',
 'ilvI',
 'ilvH',
 'cra',
 'mraZ',
 'rsmH',
 'ftsL',
 'ftsI',
 'murE',
 'murF',
 'mraY',
 'murD',
 'ftsW',
 'murG',
 'murC',
 'ddlB',
 'ftsQ',
 'ftsA',
 'ftsZ',
 'lpxC',
 'secM',
 'secA',
 'mutT',
 'yacG',
 'zapD',
 'coaE',
 'yacM',
 'guaC',
 'hofC',
 'hofB',
 'ppdD',
 'nadC',
 'ampD',
 'ampE',
 'aroP',
 'pdhR',
 'aceE',
 'aceF',
 'lpd',
 'yacH',
 'acnB',
 'yacL',
 'speD',
 'speE',
 'yacC',
 'cueO',
 'gcd',
 'hpt',
 'can',
 'yadG',
 'yadH',
 'yadI',
 'yadE',
 'panD',
 'rpnC',
 'panC',
 'panB',
 'yadC',
 'yadK',
 'yadL',
 'yadM',
 'htrE',
 'yadV',
 'yadN',
 'folK',
 'pcnB',
 'gluQ',
 'dksA',
 'sfsA',
 'thpR',
 'hrpB',
 'mrcB',
 'fhuA',
 'fhuC',
 'fhuD',
 'fhuB',
 'hemL',
 'yadX',
 'clcA',
 'yadW',
 'erpA',
 'yadS',
 'btuF',
 'mtn',
 'dgt',
 'degP',
 'cdaR',
 'yaeH',
 'yaeI',
 'dapD',
 'glnD',
 'map',
 'rpsB',
 'tsf',
 'pyrH',
 'frr',
 'dxr',
 'ispU',
 'cdsA',
 'rseP',
 'bamA',
 'skp',
 'lpxD',
 'fabZ',
 'lpxA',
 'lpxB',
 'rnhB',
 'dnaE',
 'accA',
 'ldcC',
 'yaeR',
 'tilS',
 'rof',
 'yaeP',
 'yaeQ',
 'arfB',
 'nlpE',
 'yaeF',
 'proS',
 'trmO',
 'rcsF',
 'metQ',
 'metI',
 'metN',
 'gmhB',
 'dkgB',
 'yafC',
 'yafD',
 'yafE',
 'mltD',
 'gloB',
 'yafS',
 'rnhA',
 'dnaQ',
 'yafT',
 'ykfM',
 'yafU',
 'yafF',
 'yafV',
 'ivy',
 'fadE',
 'gmhA',
 'yafJ',
 'dpaA',
 'yafQ',
 'dinJ',
 'yafL',
 'rayT',
 'lfhA',
 'lafU',
 'dinB',
 'yafN',
 'yafO',
 'yafP',
 'ykfJ',
 'prfH',
 'pepD',
 'gpt',
 'frsA',
 'crl',
 'insB9',
 'insA9',
 'phoE',
 'proB',
 'proA',
 'ykfN',
 'ykfI',
 'yafW',
 'ykfH',
 'ykfG',
 'yafX',
 'ykfF',
 'ykfB',
 'yafY',
 'yafZ',
 'ykfA',
 'perR',
 'insN',
 'insI1',
 'ykfC',
 'insH1',
 'mmuP',
 'mmuM',
 'afuC',
 'afuB',
 'insB2',
 'insA2',
 'yagB',
 'yagA',
 'yagE',
 'yagF',
 'yagG',
 'yagH',
 'xynR',
 'argF',
 'argL',
 'ykgS',
 'insB3',
 'insA3',
 'yagJ',
 'yagK',
 'yagL',
 'yagM',
 'ykgV',
 'yagN',
 'intF',
 'yagP',
 'paoD',
 'paoC',
 'paoB',
 'paoA',
 'yagU',
 'ykgJ',
 'ecpE',
 'ecpD',
 'ecpC',
 'ecpB',
 'ecpA',
 'matA',
 'ykgL',
 'ykgO',
 'ykgM',
 'ykgR',
 'ykgP',
 'eaeH',
 'insE1',
 'insF1',
 'ykgA',
 'rclC',
 'rclB',
 'rclA',
 'rclR',
 'ykgE',
 'ykgF',
 'ykgG',
 'ykgH',
 'betA',
 'betB',
 'betI',
 'betT',
 'yahV',
 'pdeL',
 'yahB',
 'yahC',
 'yahD',
 'yahE',
 'yahF',
 'yahG',
 'yahH',
 'yahI',
 'yahJ',
 'yahK',
 'yahL',
 'yahM',
 'yahN',
 'yahO',
 'prpR',
 'prpB',
 'prpC',
 'prpD',
 'prpE',
 'codB',
 'codA',
 'cynR',
 'cynT',
 'cynS',
 'cynX',
 'lacA',
 'lacY',
 'lacZ',
 'lacI',
 'mhpR',
 'mhpA',
 'mhpB',
 'mhpC',
 'mhpD',
 'mhpF',
 'mhpE',
 'mhpT',
 'yaiL',
 'frmB',
 'frmA',
 'frmR',
 'yaiO',
 'yaiX',
 'insC1',
 'insD1',
 'yaiP',
 'ykiC',
 'yaiS',
 'tauA',
 'tauB',
 'tauC',
 'tauD',
 'hemB',
 'yaiT',
 'ytiB',
 'insF2',
 'insE2',
 'iprA',
 'ampH',
 'sbmA',
 'yaiW',
 'yaiY',
 'yaiZ',
 'ddlA',
 'iraP',
 'phoA',
 'psiF',
 'dgcC',
 'proC',
 'yaiI',
 'aroL',
 'yaiA',
 'aroM',
 'ppnP',
 'ykiA',
 'ykiD',
 'rdgC',
 'mak',
 'araJ',
 'sbcC',
 'sbcD',
 'phoB',
 'phoR',
 'brnQ',
 'proY',
 'malZ',
 'acpH',
 'queA',
 'tgt',
 'yajC',
 'secD',
 'secF',
 'yajD',
 'tsx',
 'yajI',
 'nrdR',
 'ribD',
 'ribE',
 'nusB',
 'thiL',
 'pgpA',
 'yajO',
 'dxs',
 'ispA',
 'xseB',
 'thiI',
 'yajL',
 'panE',
 'yajQ',
 'yajR',
 'cyoE',
 'cyoD',
 'cyoC',
 'cyoB',
 'cyoA',
 'ampG',
 'yajG',
 'bolA',
 'tig',
 'clpP',
 'clpX',
 'lon',
 'hupB',
 'ppiD',
 'ybaV',
 'fadM',
 'queC',
 'ybaE',
 'cof',
 'decR',
 'mdlA',
 'mdlB',
 'glnK',
 'amtB',
 'tesB',
 'ybaY',
 'ybaZ',
 'ybaA',
 'pdeB',
 'ylaC',
 'maa',
 'hha',
 'tomB',
 'acrB',
 'acrA',
 'acrR',
 'mscK',
 'ybaM',
 'priC',
 'ybaN',
 'apt',
 'dnaX',
 'ybaB',
 'recR',
 'htpG',
 'adk',
 'hemH',
 'aes',
 'gsk',
 'ybaL',
 'fsr',
 'ushA',
 'ybaK',
 'ybaP',
 'ybaQ',
 'copA',
 'glsA',
 'ybaT',
 'cueR',
 'ybbJ',
 'qmcA',
 'fetA',
 'fetB',
 'cnoX',
 'ybbO',
 'tesA',
 'ybbA',
 'ybbP',
 'rhsD',
 'ybbC',
 'ylbH',
 'ybbD',
 'ylbI',
 'ylbG',
 'selU',
 'allS',
 'allA',
 'allR',
 'gcl',
 'hyi',
 'glxR',
 'allW',
 'allB',
 'ybbY',
 'glxK',
 'allE',
 'allC',
 'allD',
 'fdrA',
 'ylbE',
 'ylbF',
 'ybcF',
 'purK',
 'purE',
 'lpxH',
 'ppiB',
 'cysS',
 'ybcI',
 'ybcJ',
 'folD',
 'sfmA',
 'sfmC',
 'sfmD',
 'sfmH',
 'sfmF',
 'fimZ',
 'intD',
 'xisD',
 'exoD',
 'renD',
 'insE3',
 'insF3',
 'emrE',
 'ylcJ',
 'ybcK',
 'ybcL',
 'ybcM',
 'ylcH',
 'ybcN',
 'ninE',
 'ybcO',
 'rusA',
 'ylcG',
 'quuD',
 'nmpC',
 'insH2',
 'essD',
 'rrrD',
 'rzpD',
 'rzoD',
 'borD',
 'ybcV',
 'ybcW',
 'ylcI',
 'nohD',
 'aaaD',
 'tfaD',
 'ybcY',
 'tfaX',
 'appY',
 'ompT',
 'envY',
 'ybcH',
 'nfrA',
 'nfrB',
 'cusS',
 'cusR',
 'cusC',
 'cusF',
 'cusB',
 'cusA',
 'pheP',
 'ybdG',
 'nfsB',
 'ybdF',
 'ybdJ',
 'ybdK',
 'hokE',
 'insL2',
 'entD',
 'fepA',
 'fes',
 'ybdZ',
 'entF',
 'fepE',
 'fepC',
 'fepG',
 'fepD',
 'entS',
 'fepB',
 'entC',
 'entE',
 'entB',
 'entA',
 'entH',
 'cstA',
 'ybdD',
 'hcxA',
 'ybdL',
 'ybdM',
 'ybdN',
 'citR',
 'dsbG',
 'ahpC',
 'ahpF',
 'uspG',
 'ybdR',
 'yldA',
 'rnk',
 'rna',
 'citT',
 'citG',
 'citX',
 'citF',
 'citE',
 'citD',
 'citC',
 'dpiB',
 'dpiA',
 'dcuC',
 'pagP',
 'cspE',
 'crcB',
 'ybeM',
 'tatE',
 'lipA',
 'ybeF',
 'lipB',
 'ybeD',
 'dacA',
 'rlpA',
 'mrdB',
 'mrdA',
 'rlmH',
 'rsfS',
 'cobC',
 'nadD',
 'holA',
 'lptE',
 'leuS',
 'ybeL',
 'ybeQ',
 'ybeR',
 'djlB',
 'ybeT',
 'ybeU',
 'djlC',
 'hscC',
 'rihA',
 'gltL',
 'gltK',
 'gltJ',
 'gltI',
 'insH3',
 'lnt',
 'ybeX',
 'ybeY',
 'ybeZ',
 'miaB',
 'ubiF',
 'asnB',
 'umpH',
 'nagC',
 'nagA',
 'nagB',
 'nagE',
 'glnS',
 'chiP',
 'chiQ',
 'fur',
 'uof',
 'fldA',
 'ybfE',
 'ybfF',
 'seqA',
 'pgm',
 'ybfP',
 'ybfG',
 'potE',
 'speF',
 'ybfK',
 'speFL',
 'kdpE',
 'kdpD',
 'kdpC',
 'kdpB',
 'kdpA',
 'kdpF',
 'ybfA',
 'rhsC',
 'ybfB',
 'ybfO',
 'ybfC',
 'ybfQ',
 'ybfL',
 'ybfD',
 'ybgA',
 'phr',
 'dtpD',
 'ybgI',
 'pxpB',
 'pxpC',
 'pxpA',
 'nei',
 'abrB',
 'ybgO',
 'ybgP',
 'ybgQ',
 'ybgD',
 'gltA',
 'ybgV',
 'ybgU',
 'sdhC',
 'sdhD',
 'sdhA',
 'sdhB',
 'sucA',
 'sucB',
 'sucC',
 'sucD',
 'mngR',
 'mngA',
 'mngB',
 'cydA',
 'cydB',
 'cydX',
 'ybgE',
 'ybgC',
 'tolQ',
 'tolR',
 'tolA',
 'tolB',
 'pal',
 'cpoB',
 'nadA',
 'pnuC',
 'zitB',
 'ybgS',
 'aroG',
 'gpmA',
 'galM',
 'galK',
 'galT',
 'galE',
 'modF',
 'modE',
 'acrZ',
 'modA',
 'modB',
 'modC',
 'ybhA',
 'pgl',
 'ybhD',
 'ybhH',
 'ybhI',
 'ybhJ',
 'ybhC',
 'ybhB',
 'bioA',
 'bioB',
 'bioF',
 'bioC',
 'bioD',
 'uvrB',
 'ybhK',
 'moaA',
 'moaB',
 'moaC',
 'moaD',
 'moaE',
 'ybhL',
 'ybhM',
 'ybhN',
 'clsB',
 'ybhP',
 'ybhQ',
 'ybhR',
 'ybhS',
 'ybhF',
 'ybhG',
 'cecR',
 'rhlE',
 'ybiA',
 'dinG',
 'ybiB',
 'hcxB',
 'ybiE',
 'ybiJ',
 'ybiI',
 'ybiX',
 'fiu',
 'mcbA',
 'rlmF',
 'ybiO',
 'glnQ',
 'glnP',
 'glnH',
 'dps',
 'rhtA',
 'yliM',
 'ompX',
 'opgE',
 'mntS',
 'mntR',
 'ybiR',
 'ldtB',
 'ybiT',
 'ybiU',
 'ybiV',
 'ybiW',
 'ybiY',
 'fsaA',
 'moeB',
 'moeA',
 'iaaA',
 'gsiA',
 'gsiB',
 'gsiC',
 'gsiD',
 'pdeI',
 'dgcI',
 'rimO',
 'bssR',
 'yliI',
 'gstB',
 'dacC',
 'deoR',
 'ybjG',
 'mdfA',
 'ybjH',
 'ybjI',
 'ybjJ',
 'rcdA',
 'ybjL',
 'ybjM',
 'grxA',
 'ybjC',
 'nfsA',
 'rimK',
 'ybjN',
 'potF',
 'potG',
 'potH',
 'potI',
 'ybjO',
 'rlmC',
 'artJ',
 'artM',
 'artQ',
 'artI',
 'artP',
 'ybjP',
 'ybjQ',
 'amiD',
 'ybjS',
 'ybjT',
 'ltaE',
 'poxB',
 'hcr',
 'hcp',
 'lysO',
 'aqpZ',
 'ybjD',
 'ybjX',
 'macA',
 'macB',
 'cspD',
 'yljB',
 'clpS',
 'clpA',
 'infA',
 'aat',
 'cydC',
 'cydD',
 'trxB',
 'lrp',
 'ftsK',
 'lolA',
 'rarA',
 'serS',
 'dmsA',
 'dmsB',
 'dmsC',
 'ycaC',
 'ycaD',
 'ycaM',
 'ycaN',
 'ycaK',
 'pflA',
 'pflB',
 'focA',
 'ycaO',
 'ycaP',
 'serC',
 'aroA',
 'ycaL',
 'cmk',
 'rpsA',
 'ihfB',
 'ycaI',
 'msbA',
 'lpxK',
 'ycaQ',
 'ycaR',
 'kdsB',
 'ycbJ',
 'elyC',
 'cmoM',
 'mukF',
 'mukE',
 'mukB',
 'ldtD',
 'mepK',
 'gloC',
 'aspC',
 'ompF',
 'asnS',
 'pncB',
 'pepN',
 'ssuB',
 'ssuC',
 'ssuD',
 'ssuA',
 'ssuE',
 'elfA',
 'elfD',
 'elfC',
 'elfG',
 'ycbU',
 'ycbV',
 'ycbF',
 'pyrD',
 'zapC',
 'ycbX',
 'rlmL',
 'uup',
 'pqiA',
 'pqiB',
 'pqiC',
 'rmf',
 'fabA',
 'ycbZ',
 'matP',
 'ompA',
 'sulA',
 'sxy',
 'yccS',
 'yccF',
 'helD',
 'mgsA',
 'csgI',
 'yccU',
 'hspQ',
 'rlmI',
 'yccX',
 'tusE',
 'yccA',
 'hyaA',
 'hyaB',
 'hyaC',
 'hyaD',
 'hyaE',
 'hyaF',
 'appC',
 'appB',
 'appX',
 'appA',
 'etk',
 'etp',
 'gfcE',
 'gfcD',
 'gfcC',
 'gfcB',
 'gfcA',
 'insA4',
 'insB4',
 'cspH',
 'cspG',
 'ymcF',
 'ymcE',
 'gnsA',
 'yccM',
 'torS',
 'torT',
 'torR',
 'torC',
 'torA',
 'torD',
 'cbpM',
 'cbpA',
 ...]

In [44]:
promoters_list

0       serX
1       folA
2       ybaB
3       ytjB
4       yohJ
        ...
1234    rimP
1235    yceJ
1236    pstS
1237    pstC
1238    phoU
Name: TU first gene, Length: 1239, dtype: object

In [69]:
# Selection of genes in both datasets
genes_in_both = [gene for gene in all_genes_in_geneexpression if gene in promoters_list.values]
genes_in_both

['thrL',
 'talB',
 'ribF',
 'lspA',
 'carB',
 'caiF',
 'caiT',
 'fixA',
 'yaaU',
 'folA',
 'apaG',
 'rsmA',
 'polB',
 'araB',
 'araC',
 'yabI',
 'sgrR',
 'cra',
 'mraZ',
 'rsmH',
 'ftsA',
 'ppdD',
 'nadC',
 'ampD',
 'pdhR',
 'aceE',
 'lpd',
 'yacL',
 'speD',
 'speE',
 'yacC',
 'cueO',
 'hpt',
 'can',
 'panB',
 'sfsA',
 'mrcB',
 'fhuA',
 'erpA',
 'mtn',
 'degP',
 'cdaR',
 'dapD',
 'glnD',
 'pyrH',
 'frr',
 'ispU',
 'rseP',
 'skp',
 'lpxD',
 'yaeP',
 'yaeQ',
 'proS',
 'metN',
 'gmhB',
 'dkgB',
 'yafD',
 'rnhA',
 'yafV',
 'fadE',
 'dinJ',
 'dinB',
 'yafN',
 'gpt',
 'frsA',
 'phoE',
 'yafZ',
 'insN',
 'argF',
 'yagK',
 'ecpA',
 'matA',
 'ykgM',
 'ykgR',
 'rclA',
 'betI',
 'betT',
 'yahE',
 'yahO',
 'prpR',
 'prpB',
 'codB',
 'cynR',
 'cynT',
 'lacI',
 'mhpA',
 'mhpT',
 'tauA',
 'hemB',
 'sbmA',
 'yaiZ',
 'phoA',
 'psiF',
 'dgcC',
 'proC',
 'aroM',
 'ppnP',
 'ykiA',
 'araJ',
 'sbcD',
 'phoB',
 'brnQ',
 'malZ',
 'queA',
 'tgt',
 'yajC',
 'nrdR',
 'ribE',
 'xseB',
 'thiI',
 'yajQ',
 'yajR',
 'cyoA',
 'yajG',
 'clpX',
 'lon',
 'fadM',
 'decR',
 'glnK',
 'tesB',
 'ylaC',
 'tomB',
 'acrB',
 'acrA',
 'acrR',
 'mscK',
 'apt',
 'dnaX',
 'ybaB',
 'adk',
 'hemH',
 'aes',
 'gsk',
 'ybaL',
 'ybaQ',
 'copA',
 'glsA',
 'qmcA',
 'fetA',
 'cnoX',
 'tesA',
 'allS',
 'allA',
 'gcl',
 'ybbY',
 'allD',
 'purE',
 'cysS',
 'folD',
 'nmpC',
 'essD',
 'borD',
 'ompT',
 'cusR',
 'cusC',
 'pheP',
 'nfsB',
 'hokE',
 'fepA',
 'fes',
 'fepB',
 'entC',
 'entH',
 'ybdN',
 'dsbG',
 'ahpF',
 'uspG',
 'rna',
 'dcuC',
 'pagP',
 'lipA',
 'ybeD',
 'rsfS',
 'ybeL',
 'gltI',
 'ybeZ',
 'asnB',
 'umpH',
 'nagA',
 'nagB',
 'nagE',
 'uof',
 'fldA',
 'ybfE',
 'seqA',
 'ybfG',
 'kdpF',
 'phr',
 'nei',
 'sdhC',
 'sdhD',
 'sucA',
 'mngR',
 'mngA',
 'nadA',
 'aroG',
 'galK',
 'acrZ',
 'ybhC',
 'bioA',
 'bioB',
 'moaB',
 'ybhL',
 'ybhQ',
 'cecR',
 'dinG',
 'ybiI',
 'fiu',
 'mcbA',
 'glnQ',
 'dps',
 'yliM',
 'ompX',
 'mntR',
 'ldtB',
 'ybiT',
 'moeA',
 'iaaA',
 'rimO',
 'gstB',
 'dacC',
 'ybjG',
 'grxA',
 'ybjC',
 'rimK',
 'artJ',
 'ybjP',
 'ybjQ',
 'ltaE',
 'poxB',
 'lysO',
 'ybjX',
 'cspD',
 'clpS',
 'cydD',
 'trxB',
 'lrp',
 'lolA',
 'serS',
 'dmsC',
 'pflA',
 'cmk',
 'ihfB',
 'ycaR',
 'ycbJ',
 'cmoM',
 'ldtD',
 'mepK',
 'aspC',
 'ompF',
 'asnS',
 'pncB',
 'pepN',
 'ssuE',
 'pyrD',
 'rlmL',
 'rmf',
 'fabA',
 'matP',
 'sulA',
 'sxy',
 'yccF',
 'helD',
 'mgsA',
 'csgI',
 'yccA',
 'hyaA',
 'appC',
 'appA',
 'gfcA',
 'torR',
 'torC',
 'agp',
 'wrbA',
 'rutA',
 'putA',
 'efeU',
 'pgaA',
 'dgcT',
 'ycdZ',
 'csgB',
 'csgA',
 'ymdA',
 'ymdB',
 'clsC',
 'msyB',
 'lpxL',
 'trhO',
 'yceJ',
 'solA',
 'dinI',
 'pyrC',
 'grxB',
 'rimJ',
 'flgM',
 'flgA',
 'flgB',
 'flgK',
 'rpmF',
 'plsX',
 'fabH',
 'acpP',
 'fhuE',
 'ndh',
 'comR',
 'ldtC',
 'pepT',
 'phoQ',
 'hflD',
 'bluR',
 'bluF',
 'ycgZ',
 'ycgL',
 'hlyE',
 'umuD',
 'ycgB',
 'ycgR',
 'treA',
 'dhaK',
 'dhaR',
 'ychF',
 'pth',
 'ychH',
 'prs',
 'lolB',
 'ychQ',
 'kdsA',
 'chaC',
 'ychO',
 'narX',
 'narG',
 'purU',
 'ychJ',
 'rssA',
 'rssB',
 'galU',
 'hns',
 'oppB',
 'clsA',
 'yciI',
 'tonB',
 'yciC',
 'ompW',
 'yciE',
 'yciG',
 'trpC',
 'trpL',
 'rnm',
 'cysB',
 'ymiA',
 'ymiC',
 'pgpB',
 'pyrF',
 'yciT',
 'yciZ',
 'pdeR',
 'yciW',
 'ymjE',
 'puuA',
 'puuD',
 'puuC',
 'pspA',
 'ycjX',
 'tyrR',
 'tpx',
 'ycjG',
 'ycjY',
 'ynaI',
 'uspE',
 'fnr',
 'ogt',
 'zntB',
 'uspF',
 'ompN',
 'ydbJ',
 'hslJ',
 'ldhA',
 'tynA',
 'paaZ',
 'paaA',
 'paaX',
 'ydbD',
 'ynbA',
 'azoR',
 'aldA',
 'trg',
 'ydcI',
 'rimL',
 'tehA',
 'sutR',
 'ydcR',
 'ydcS',
 'yncE',
 'yncG',
 'narW',
 'yddG',
 'fdnG',
 'sra',
 'bdm',
 'gadB',
 'ydeN',
 'safA',
 'ydeP',
 'hipB',
 'lsrR',
 'lsrA',
 'tam',
 'uxaB',
 'ydeA',
 'marC',
 'marR',
 'mgtS',
 'dgcZ',
 'ydeI',
 'ydeJ',
 'ydfG',
 'rspR',
 'ynfT',
 'nohA',
 'gnsB',
 'cspB',
 'relB',
 'flxA',
 'dicC',
 'ydfA',
 'dicB',
 'rspA',
 'ynfB',
 'ynfE',
 'ynfM',
 'asr',
 'mdtU',
 'tqsA',
 'pntA',
 'rstA',
 'fumA',
 'manA',
 'ydgA',
 'uidA',
 'uidR',
 'hdhA',
 'malI',
 'malX',
 'malY',
 'add',
 'blr',
 'ydgK',
 'rsxA',
 'dtpA',
 'gstA',
 'pdxH',
 'ydhI',
 'sodC',
 'nemR',
 'gloA',
 'rnt',
 'lhr',
 'grxD',
 'mepH',
 'sodB',
 'purR',
 'ydhQ',
 'ydhY',
 'sufA',
 'aroD',
 'ydiP',
 'ppsA',
 'selO',
 'rflP',
 'btuD',
 'ihfA',
 'pheM',
 'rplT',
 'rpmI',
 'thrS',
 'yniB',
 'hxpB',
 'ydjM',
 'tcyP',
 'cedA',
 'katE',
 'chbB',
 'osmE',
 'nadE',
 'cho',
 'ves',
 'spy',
 'xthA',
 'ynjE',
 'ynjF',
 'gdhA',
 'ynjI',
 'ydjA',
 'msrB',
 'yeaE',
 'mipA',
 'yeaL',
 'nimR',
 'nimT',
 'dgcP',
 'yeaR',
 'leuE',
 'rnd',
 'fadD',
 'yeaY',
 'yoaC',
 'sdaA',
 'yoaE',
 'manX',
 'mntP',
 'mgrB',
 'htpX',
 'ptrB',
 'yebE',
 'yebG',
 'purT',
 'edd',
 'zwf',
 'znuA',
 'znuC',
 'ruvC',
 'yebC',
 'nudB',
 'argS',
 'yecT',
 'flhB',
 'tar',
 'insA5',
 'otsA',
 'yecR',
 'ftnA',
 'uvrC',
 'uvrY',
 'yecF',
 'dcyD',
 'tcyJ',
 'fliC',
 'fliD',
 'amyA',
 'rcsA',
 'hiuH',
 'zinT',
 'shiA',
 'amn',
 'cbl',
 'nac',
 'sbcB',
 'tsuA',
 'yefM',
 'hisL',
 'hisB',
 'gnd',
 'galF',
 'yegH',
 'alkA',
 'mdtA',
 'yegR',
 'gatZ',
 'gatY',
 'fbaB',
 'yegT',
 'thiM',
 'rcnR',
 'rcnA',
 'mrp',
 'yehF',
 'mlrA',
 'osmF',
 'bglX',
 'dusC',
 'yohJ',
 'cdd',
 'preT',
 'mglA',
 'mglB',
 'galS',
 'folE',
 'lysP',
 'nfo',
 'rihB',
 'yeiL',
 'fruB',
 'yeiW',
 'yeiP',
 'lpxT',
 'radD',
 'rplY',
 'yejO',
 'narP',
 'yojI',
 'alkB',
 'ada',
 'rcsD',
 'atoD',
 'gyrA',
 'ubiG',
 'nrdA',
 'inaA',
 'glpQ',
 'glpT',
 'glpA',
 'yfaY',
 'elaB',
 'rbn',
 'lrhA',
 'alaA',
 'yfbR',
 'yfbU',
 'ackA',
 'pta',
 'hisJ',
 'argT',
 'accD',
 'usg',
 'pdxB',
 'flk',
 'fabB',
 'sixA',
 'fadI',
 'yfcZ',
 'fadL',
 'mlaA',
 'intS',
 'dsdC',
 'dsdX',
 'dsdA',
 'emrK',
 'frc',
 'yfdX',
 'lpxP',
 'alaC',
 'mntH',
 'nupC',
 'yfeC',
 'xapA',
 'ligA',
 'pdxK',
 'yfeK',
 'cysP',
 'murR',
 'yfeY',
 'amiA',
 'yffO',
 'tktB',
 'narQ',
 'ypfM',
 'dapE',
 'purC',
 'bamC',
 'dapA',
 'bcp',
 'hyfA',
 'upp',
 'purM',
 'ppk',
 'pdeF',
 'yfgG',
 'guaB',
 'xseA',
 'bamB',
 'hisS',
 'yfhM',
 'sseA',
 'hscB',
 'iscR',
 'csiE',
 'hcaR',
 'hcaE',
 'glyA',
 'hmp',
 'glrK',
 'purL',
 'mltF',
 'pgpC',
 'shoB',
 'pdxJ',
 'rnc',
 'lepA',
 'rseA',
 'nadB',
 'ung',
 'trxC',
 'patZ',
 'pssL',
 'clpB',
 'raiA',
 'pheL',
 'aroF',
 'yfiR',
 'rpsP',
 'ffh',
 'grpE',
 'recN',
 'bamE',
 'ypjB',
 'glaH',
 'kbp',
 'yqaE',
 'alaE',
 'ygaC',
 'ygaM',
 'nrdH',
 'mprA',
 'alaS',
 'recA',
 'pncC',
 'srlA',
 'srlR',
 'norR',
 'norV',
 'hydN',
 'ascF',
 'ascB',
 'hycA',
 'hypA',
 'hypB',
 'ygbA',
 'mutS',
 'ygbK',
 'umpG',
 'cysD',
 'cas2',
 'casA',
 'cysJ',
 'rlmD',
 'queF',
 'fucO',
 'fucA',
 'fucP',
 'fucU',
 'gcvA',
 'argA',
 'ptrA',
 'recC',
 'ppdA',
 'thyA',
 'lgt',
 'rppH',
 'galR',
 'lysA',
 'lysR',
 'araE',
 'ygeH',
 'ygeV',
 'ygfK',
 'ssnA',
 'xerD',
 'fldB',
 'sdhE',
 'ygfZ',
 'gcvT',
 'ygfB',
 'ibsC',
 'rpiA',
 'argP',
 'argO',
 'mscS',
 'epd',
 'tktA',
 'loiP',
 'speB',
 'speA',
 'metK',
 'galP',
 'rdgB',
 'yggX',
 'nupG',
 'speC',
 'yghF',
 'glcD',
 'glcC',
 'pitB',
 'gss',
 'yghU',
 'hybO',
 'exbD',
 'exbB',
 'metC',
 'yghB',
 'yqhD',
 'dkgA',
 'yqhG',
 'ygiZ',
 'zupT',
 'yqiG',
 'ibsD',
 'bacA',
 'ttdR',
 'ttdA',
 'nfeF',
 'nfeR',
 'aer',
 'patA',
 'ebgR',
 'ebgA',
 'fadH',
 'higB',
 'ygjR',
 'sstT',
 'exuR',
 'yqjC',
 'yqjD',
 'tdcA',
 'garR',
 'garP',
 'prlF',
 'agaR',
 'kbaZ',
 'agaS',
 'yraR',
 'pnp',
 'rpsO',
 'infB',
 'nusA',
 'rimP',
 'argG',
 'yhbY',
 'rplU',
 'sfsB',
 'yrbG',
 'lptB',
 'rpoN',
 'yrbL',
 'arcB',
 'gltB',
 'nanA',
 'sspA',
 'rplM',
 'zapG',
 'degS',
 'aaeX',
 'aaeR',
 'yhdT',
 'dusB',
 'acrE',
 'yhdW',
 'smf',
 'def',
 'mscL',
 'arfA',
 'yhdN',
 'rplN',
 'rpsJ',
 'chiA',
 'fusA',
 'rpsL',
 'prkB',
 'yhfA',
 'argD',
 'pabA',
 'yhfG',
 'tsgA',
 'nirB',
 'frlA',
 'trpS',
 'rpe',
 'damX',
 'hofM',
 'mrcA',
 'hslR',
 'pck',
 'feoA',
 'bioH',
 'yhgH',
 'malQ',
 'malP',
 'malT',
 'rtcB',
 'glpG',
 'glpE',
 'glpD',
 'glgA',
 'glgB',
 'gntK',
 'yhhY',
 'livJ',
 'zntA',
 'nikR',
 'yhiM',
 'pitA',
 'uspB',
 'prlC',
 'rlmJ',
 'gor',
 'dinQ',
 'arsR',
 'slp',
 'hdeA',
 'hdeD',
 'gadX',
 'gadA',
 'ccp',
 'treF',
 'rcdB',
 'yhjG',
 'pdeH',
 'yhjJ',
 'dctA',
 'bcsB',
 'yhjR',
 'bcsE',
 'ldrD',
 'dppA',
 'eptB',
 'yhjX',
 'yiaF',
 'yiaG',
 'insK',
 'glyQ',
 'xylA',
 'xylF',
 'xylR',
 'malS',
 'avtA',
 'plaR',
 'aldB',
 'selA',
 'yibF',
 'mtlA',
 'lldP',
 'cysE',
 'secB',
 'yibN',
 'waaH',
 'kbl',
 'waaY',
 'waaQ',
 'mutM',
 'rpmB',
 'yicR',
 'dfp',
 'dut',
 'rph',
 'yicC',
 'dinD',
 'gmk',
 'rpoZ',
 'yicH',
 'yicJ',
 'nlpA',
 'nepI',
 'adeD',
 'uhpT',
 'uhpB',
 'ivbL',
 'tisB',
 'emrD',
 'yidL',
 'ibpB',
 'ibpA',
 'yidQ',
 'dgoR',
 'gyrB',
 'tnaC',
 'yieE',
 'phoU',
 'pstC',
 'pstS',
 'atpI',
 'mnmG',
 'mioC',
 'asnC',
 'asnA',
 'ravA',
 'rbsD',
 'hdfR',
 'ilvE',
 'ilvA',
 'ilvY',
 'ilvC',
 'ppiC',
 'rep',
 'rhoL',
 'rfe',
 'aslB',
 'lptM',
 'corA',
 'yigI',
 'pldA',
 'recQ',
 'metE',
 'ysgA',
 'udp',
 'tatA',
 'fadB',
 'pepQ',
 'yihD',
 'srkA',
 'dsbA',
 'yihG',
 'polA',
 'yihI',
 'hemN',
 'glnL',
 'yihV',
 'csqR',
 'yihX',
 'rhaD',
 'rhaB',
 'rhaS',
 ...]

In [72]:
## genes with TF in both datasets

genes_in_both_with_TF = [gene for gene in genes_in_both if gene in genes_with_TF]
len(genes_in_both_with_TF)

817

In [73]:
## genes without TF in both datasets

genes_in_both_without_TF = [gene for gene in genes_in_both if gene not in genes_with_TF]
len(genes_in_both_without_TF)

323

In [87]:
## Filter geneExpression dataset

tpm_wo_TF = df_tpm[["dataset id"] +genes_in_both_without_TF]
tpm_wo_TF

,dataset id,talB,ribF,lspA,carB,apaG,rsmA,yabI,rsmH,speD,...,queG,nsrR,yzfA,ppa,tldE,holC,idnR,dnaT,yjjB,holD
0,GENE_EXPRESSION_ERR1218301,125.728812,14.672481,8.283922,2.434414,38.259702,48.371512,1.949867,59.997689,44.722447,...,23.096083,8.169063,11.770322,44.254689,39.686357,10.098825,NaN,6.669081,0.587490,7.426688
1,GENE_EXPRESSION_ERR1218302,94.979412,13.584008,4.048387,4.025614,57.909072,76.412978,3.225000,24.826544,18.725805,...,33.603909,8.834305,9.668774,48.254689,36.541769,6.256652,NaN,7.555603,0.521881,6.757119
2,GENE_EXPRESSION_ERR1399576,390.658573,28.281509,21.688995,13.563789,19.104872,33.398659,6.390576,25.464407,27.441458,...,5.253229,20.989300,7.973541,67.376019,15.634765,3.285447,NaN,7.951487,2.909595,3.460968
3,GENE_EXPRESSION_ERR1399577,405.697289,27.575940,23.459829,14.142202,20.468631,32.593185,5.342919,24.600592,28.167976,...,4.850956,19.392700,4.877711,68.911160,13.854472,3.200225,NaN,8.519621,2.445813,3.922253
4,GENE_EXPRESSION_ERR1399578,490.651004,25.674925,26.130226,15.435764,20.814581,31.532126,8.147108,20.757368,33.299862,...,5.140968,17.162845,7.235022,69.833468,14.776131,2.977522,NaN,8.402082,2.227962,2.969373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,GENE_EXPRESSION_SRR9919243,152.714646,24.833296,17.625685,164.517410,8.259709,16.484985,2.995522,16.367641,54.412830,...,2.304591,6.556307,20.254964,140.257877,13.128584,10.891115,3.432676,2.791612,0.463588,5.056093
1860,GENE_EXPRESSION_SRR9919244,128.039858,21.682687,18.566951,91.941032,9.427383,15.787240,2.661017,18.271807,19.345162,...,3.600395,6.169619,13.891803,96.185661,14.654876,8.614509,3.448629,4.792810,1.341009,4.938713
1861,GENE_EXPRESSION_SRR9919245,126.906737,20.455657,18.764994,106.882661,8.500820,16.239040,2.542442,17.547014,16.693331,...,3.776150,5.835782,14.790302,93.537906,13.996865,8.702609,3.332304,4.543245,1.255498,5.932506
1862,GENE_EXPRESSION_SRR9919246,122.605519,23.399676,20.063632,58.707289,8.883398,16.493210,2.711211,17.921798,24.231615,...,3.523419,6.358232,17.891373,102.810425,14.606067,9.903559,3.304536,4.241548,1.043845,4.986112
1863,GENE_EXPRESSION_SRR9919247,120.170441,23.843122,18.557752,63.887982,8.550697,15.172071,2.610294,18.643001,22.685048,...,2.990206,6.478274,14.277042,95.770261,14.174707,9.541698,3.372537,4.526251,1.190581,4.647282

# Filter wrong datasets

In [100]:
# 10000 is a very high value for TPM, if a put 1000 as threshold almost all the dataset are eliminated. 

threshold = 10000
index_wrong_datasets = tpm_wo_TF[(tpm_wo_TF.drop(columns="dataset id") > threshold).any(axis=1)].index

In [102]:
tpm_wo_TF_curated = tpm_wo_TF.drop(index=index_wrong_datasets)
tpm_wo_TF_curated

,dataset id,talB,ribF,lspA,carB,apaG,rsmA,yabI,rsmH,speD,...,queG,nsrR,yzfA,ppa,tldE,holC,idnR,dnaT,yjjB,holD
0,GENE_EXPRESSION_ERR1218301,125.728812,14.672481,8.283922,2.434414,38.259702,48.371512,1.949867,59.997689,44.722447,...,23.096083,8.169063,11.770322,44.254689,39.686357,10.098825,NaN,6.669081,0.587490,7.426688
1,GENE_EXPRESSION_ERR1218302,94.979412,13.584008,4.048387,4.025614,57.909072,76.412978,3.225000,24.826544,18.725805,...,33.603909,8.834305,9.668774,48.254689,36.541769,6.256652,NaN,7.555603,0.521881,6.757119
2,GENE_EXPRESSION_ERR1399576,390.658573,28.281509,21.688995,13.563789,19.104872,33.398659,6.390576,25.464407,27.441458,...,5.253229,20.989300,7.973541,67.376019,15.634765,3.285447,NaN,7.951487,2.909595,3.460968
3,GENE_EXPRESSION_ERR1399577,405.697289,27.575940,23.459829,14.142202,20.468631,32.593185,5.342919,24.600592,28.167976,...,4.850956,19.392700,4.877711,68.911160,13.854472,3.200225,NaN,8.519621,2.445813,3.922253
4,GENE_EXPRESSION_ERR1399578,490.651004,25.674925,26.130226,15.435764,20.814581,31.532126,8.147108,20.757368,33.299862,...,5.140968,17.162845,7.235022,69.833468,14.776131,2.977522,NaN,8.402082,2.227962,2.969373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,GENE_EXPRESSION_SRR9919243,152.714646,24.833296,17.625685,164.517410,8.259709,16.484985,2.995522,16.367641,54.412830,...,2.304591,6.556307,20.254964,140.257877,13.128584,10.891115,3.432676,2.791612,0.463588,5.056093
1860,GENE_EXPRESSION_SRR9919244,128.039858,21.682687,18.566951,91.941032,9.427383,15.787240,2.661017,18.271807,19.345162,...,3.600395,6.169619,13.891803,96.185661,14.654876,8.614509,3.448629,4.792810,1.341009,4.938713
1861,GENE_EXPRESSION_SRR9919245,126.906737,20.455657,18.764994,106.882661,8.500820,16.239040,2.542442,17.547014,16.693331,...,3.776150,5.835782,14.790302,93.537906,13.996865,8.702609,3.332304,4.543245,1.255498,5.932506
1862,GENE_EXPRESSION_SRR9919246,122.605519,23.399676,20.063632,58.707289,8.883398,16.493210,2.711211,17.921798,24.231615,...,3.523419,6.358232,17.891373,102.810425,14.606067,9.903559,3.304536,4.241548,1.043845,4.986112
1863,GENE_EXPRESSION_SRR9919247,120.170441,23.843122,18.557752,63.887982,8.550697,15.172071,2.610294,18.643001,22.685048,...,2.990206,6.478274,14.277042,95.770261,14.174707,9.541698,3.372537,4.526251,1.190581,4.647282

In [106]:
# Función para filtrar valores extremos usando IQR
def filter_outliers_iqr(row):
    # Calcular Q1, Q3 y el IQR
    Q1 = np.percentile(row, 25)
    Q3 = np.percentile(row, 75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Reemplazar valores extremos con NaN
    return row.where((row >= lower_bound) & (row <= upper_bound))

# Aplicar la función al DataFrame
filtered_df_tpm = tpm_wo_TF_curated.drop(columns="dataset id").apply(filter_outliers_iqr, axis=1)

In [107]:
filtered_df_tpm

,talB,ribF,lspA,carB,apaG,rsmA,yabI,rsmH,speD,speE,...,queG,nsrR,yzfA,ppa,tldE,holC,idnR,dnaT,yjjB,holD
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
gene_list = tpm_wo_TF_curated.drop(columns="dataset id").median().index
gene_median = tpm_wo_TF_curated.drop(columns="dataset id").median().values

expression_categorized = pd.DataFrame({"gene":gene_list, "median expression": gene_median})

In [120]:
expression_categorized

     gene  median expression
0    talB         132.384663
1    ribF          24.342764
2    lspA          13.381328
3    carB          20.522481
4    apaG          11.202675
..    ...                ...
318  holC           9.172458
319  idnR           2.827597
320  dnaT           4.514769
321  yjjB           0.663471
322  holD           4.910984

[323 rows x 2 columns]

In [121]:
expression_categorized["strength"] = pd.qcut(expression_categorized['median expression'], q=5, labels=False)

In [122]:
expression_categorized

     gene  median expression  strength
0    talB         132.384663         4
1    ribF          24.342764         4
2    lspA          13.381328         3
3    carB          20.522481         3
4    apaG          11.202675         2
..    ...                ...       ...
318  holC           9.172458         2
319  idnR           2.827597         0
320  dnaT           4.514769         1
321  yjjB           0.663471         0
322  holD           4.910984         1

[323 rows x 3 columns]

In [138]:
df_for_cnn = expression_categorized.copy()

In [139]:
df_for_cnn = pd.merge(df_for_cnn, df_promoters[["TU first gene", "Promoter sequence", "Sigma factor"]], left_on="gene", right_on="TU first gene")

In [140]:
df_for_cnn.drop(columns="TU first gene", inplace=True)

In [141]:
df_for_cnn.to_csv("dataframes/7_forCNN_test.csv", index=False)

In [142]:
df_for_cnn.head(1)

,gene,median expression,strength,Promoter sequence,Sigma factor
0,talB,132.384663,4,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN

# Test with Trees

## Libraries

In [147]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [143]:
def sequence_to_onehot(sequence):
    sequence = sequence.upper()
    mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    onehot = np.zeros((len(sequence), len(mapping)))
    for i, nucleotide in enumerate(sequence):
        if nucleotide in mapping:
            onehot[i, mapping[nucleotide]] = 1
    return onehot.flatten()

In [144]:
df_for_cnn["sequence OHE"] = df_for_cnn["Promoter sequence"].apply(sequence_to_onehot)

In [145]:
df_for_cnn

,gene,median expression,strength,Promoter sequence,Sigma factor,sequence OHE
0,talB,132.384663,4,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
1,ribF,24.342764,4,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
2,lspA,13.381328,3,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
3,carB,20.522481,3,agccagccctggtccacacgacgccgcgccgttgttcgaccacttt...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
4,apaG,11.202675,2,aacctgccttataacatctccacgccgttgatgttccatctgttta...,NaN,"[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...
318,holC,9.172458,2,cgctgcggtgtatacctgatgcgtatttaaatccaccacaagaagc...,sigma32,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
319,idnR,2.827597,0,gctgggcgtgttagccattaacgccgtattgcactgaaagaataaa...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
320,dnaT,4.514769,1,cggtctttccattcctggattatggttgtaccgcaagcgccctcgc...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
321,yjjB,0.663471,0,tttccgttgattaatgccgtcgccgatatgtttaaaggccacatca...,NaN,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
322,holD,4.910984,1,ctggcggcgattatagccatatgttggcgcggtatcgacgaatttg...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."

## X and Y

In [146]:
X = list(df_for_cnn["sequence OHE"])
y = list(df_for_cnn["strength"])

In [148]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

## Models

In [149]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [150]:
KNN_model = KNeighborsClassifier()
Logit_model = LogisticRegression()
DecTree_model = DecisionTreeClassifier()
RF_model = RandomForestClassifier()
GB_model = GradientBoostingClassifier()
XGB_model = XGBClassifier()

In [151]:
list_of_models = [KNN_model, Logit_model, DecTree_model, RF_model, GB_model, XGB_model]

In [152]:
def run_model(model, X_train, y_train):
    L=[]
    model.fit(X_train, y_train)
    y_hat_train = model.predict(X_train)
    y_hat_test = model.predict(X_test)
    accuracy_train = accuracy_score(y_train,y_hat_train)
    accuracy_test = accuracy_score(y_test,y_hat_test)
    L.append(accuracy_train)
    L.append(accuracy_test)
    return L

In [153]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y)

### Results

In [154]:
L=[]
for elem in list_of_models:
    try:
        L.append(run_model(elem, X_train, y_train))
    except:
        None
L

[[0.496551724137931, 0.12121212121212122],
 [1.0, 0.15151515151515152],
 [1.0, 0.24242424242424243],
 [1.0, 0.12121212121212122],
 [1.0, 0.21212121212121213],
 [1.0, 0.15151515151515152]]

# Convolutional Neural Network

In [155]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
import tensorflow
import keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [156]:
def one_hot_encode_dna(sequences):
    """
    Codifica una lista de secuencias de ADN en una representación one-hot.

    Parameters:
    sequences (list of str): Lista de secuencias de ADN.

    Returns:
    np.array: Matriz 3D de secuencias codificadas one-hot.
    """
    # Definir el diccionario de codificación one-hot
    mapping = {
        'A': [1, 0, 0, 0],
        'C': [0, 1, 0, 0],
        'G': [0, 0, 1, 0],
        'T': [0, 0, 0, 1],
        'N': [0, 0, 0, 0]  # Para manejar nucleótidos desconocidos
    }
    
    # Obtener la longitud de la secuencia y el número de secuencias
    seq_length = len(sequences[0])
    num_sequences = len(sequences)
    
    # Crear una matriz vacía para almacenar las secuencias codificadas
    one_hot_encoded = np.zeros((num_sequences, seq_length, 4), dtype=np.int8)
    
    # Rellenar la matriz con los valores one-hot
    for i, seq in enumerate(sequences):
        for j, nucleotide in enumerate(seq):
            one_hot_encoded[i, j, :] = mapping.get(nucleotide, [0, 0, 0, 0])
    
    return one_hot_encoded

In [157]:
df_for_cnn["sequence OHE CNN"] = df_for_cnn["Promoter sequence"].apply(lambda x: one_hot_encode_dna(x.upper()))

In [158]:
df_for_cnn

,gene,median expression,strength,Promoter sequence,Sigma factor,sequence OHE,sequence OHE CNN
0,talB,132.384663,4,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 1, 0, 0]], [[0, 0, 0, 1]..."
1,ribF,24.342764,4,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 0, 1]], [[0, 1, 0, 0]..."
2,lspA,13.381328,3,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 1, 0]], [[0, 0, 1, 0]..."
3,carB,20.522481,3,agccagccctggtccacacgacgccgcgccgttgttcgaccacttt...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[1, 0, 0, 0]], [[0, 0, 1, 0]], [[0, 1, 0, 0]..."
4,apaG,11.202675,2,aacctgccttataacatctccacgccgttgatgttccatctgttta...,NaN,"[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[[[1, 0, 0, 0]], [[1, 0, 0, 0]], [[0, 1, 0, 0]..."
...,...,...,...,...,...,...,...
318,holC,9.172458,2,cgctgcggtgtatacctgatgcgtatttaaatccaccacaagaagc...,sigma32,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 0, 1, 0]], [[0, 1, 0, 0]..."
319,idnR,2.827597,0,gctgggcgtgttagccattaacgccgtattgcactgaaagaataaa...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[0, 0, 0, 1]..."
320,dnaT,4.514769,1,cggtctttccattcctggattatggttgtaccgcaagcgccctcgc...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 0, 1, 0]], [[0, 0, 1, 0]..."
321,yjjB,0.663471,0,tttccgttgattaatgccgtcgccgatatgtttaaaggccacatca...,NaN,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 0, 1]], [[0, 0, 0, 1]..."
322,holD,4.910984,1,ctggcggcgattatagccatatgttggcgcggtatcgacgaatttg...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 0, 0, 1]], [[0, 0, 1, 0]..."

In [159]:
sequences = list(df_for_cnn["Promoter sequence"].str.upper())

In [ ]:
sequences

['AAAGAAAATAATTAATTTTACAGCTGTTAAACCAAACGGTTATAACCTGGTCATACGCAGTAGTTCGGACAAGCGGTACAT',
 'CTGCTGTTCCTTGCGATCGAAAAGATCAAGGGCGGACCGGTATCCGAGCGGGTTCAAGACTTTTGTTATCGCATTGGCTCG',
 'GCGGAAGCACAAATTGCACCAGGTACGGAACTAAAAGCCGTAGATGGTATCGAAACGCCTGATTGGGATGCCGTGCGTTTG',
 'AAATACTTATGGTGCGCTGGCTTCTTTGGAACTTGCGCAGCAATTTGTTGACAAAAATGAACTAGAGAAAGCTGCCGCCCA',
 'ACGCGTTATTAATCAGCGTCTGATGCCATTACACAACAAACTATTTGTCGAACCCAATCCAATCCCGGTGAAATGGGCATG',
 'CTGATCTAAGCGTTGACCGAGTTGGTTTTCGGACACCGTTGCAGTGAGCTGTACTCGTTGTGCCATATATACTGCTTCTTC',
 'TTTTATTCGCGAACGTGAATAATCCGGGAACATTTCGGCCAAAGCCTGATCTAAGCGTTGACCGAGTTGGTTTTCGGACAC',
 'GGCGAATGCGAAAGAACTGCTTGCAGCGTAAACTTTTTTCCTGCTTCACGGTCAGAGTAAACAGCAAAACGCCGTAAGACC',
 'GCCGTTACACTCAAAGGCGGCGCGGTGGGAACGATATTTCACAGTATCGGTCAAATGACTATCTCCAGAAATACAGGATAG',
 'TAAAAAATATCTTGTATGTGATCCAGATCACATCTATCATTTAGTTATCGATCGTTAAGTAATTGCTTGCGACGTCATTCA',
 'ATTCTGAAAGTTAAAGGGCGCATGAATGAACTTATGGCGCTTCATACGGGTCAATCATTAGAACAGATTGAACGTGATACC',
 'TGGAAAATTCTTAGAAACCGATCACATACAGCTGCATTTATTAAGGTTATCATCCGTTTCGCTGAAAAACATAACCCATAA',
 'TTTACCTTTTGCAGAAACTTTAGTTCGGAACTTCAGGCTATAAAACGAATCTGAAGAACACAGCAATTTTGCGTTATCTGT',
 'ACCGAGCGTCTGCGGCAACTTCATCAACAGCATCACCCGCGGGCGTGATGTCTGAAAAGAACGGGAAGATTTATGAAGAAA',
 'GGAAAAAAATCTGGCTGAAAATACGTTGAACGCTTACCGTCGCGATCTGTCAATGATGGTGGAGTGGTTGCATCACCGCGG',
 'TTTGTGCTTCATGCACACTCTTTCCCCACACTTTTTCCCTTTGCTGTGGTCTACTTATTCGCGCGTGTAGATTTTACTTAT',
 'TTAATTTTTTCATCGTGAGCCCTTTTTTTGAACTATTATTAAAAAATGATGTCACTGCGCGATAAATATTCATCTAATCAA',
 'GAGACAGCACTCATTTCGCGGTCATCGAAACTAATTTAAACAAAAAGAGTCTGAAAATAGATGATAATAGGGCGTGTCTGT',
 'ATTTCATCAATGAAATGTAAAAATATATAAACTTGATGATTTAAGCATTTTCTTATACCCGTTCAGACGTTATTCTTATTT',
 'GATAAATCCATGGCTCTGCGCCTGGCGAACGAACTTTCTGATGCTGCAGAAAACAAAGGTACTGCAGTTAAGAAACGTGAA',
 'CCCTATAAAGTAAACGATGACCCTTCGGGAACTTCAGGGTAAAATGACTATCAAAATGTGAATTGTAGCTGACCTGGGACT',
 'ATGGAAATAATTCACATTAAAAATAATCGACCCTATGCTTATAAATATAATCAATATATTGATGGCAGCATCTTTATTATG',
 'CGCGGCGTTTTTTAATGATCTGGCCCGTGAACTGATTGCTATTATGTTGATCCCTGGGCTGATTCGCCGCAGCCGCTCTAC',
 'CGATGACTTTAGGCGATCAATATAAGATCGCCGGGCCACGCAAAGAACTGCACCCTCCGGTGCAAATGGGATGGTAAGGAG',
 'GGCCACGCCAATGATTTTTCCCCAATACTGCATATATTCCCCAAATCGACACACGGATATCAGGGCTATCTCCCACAATAT',
 'CAAGTAATATTTGTCATAATGCGCGCTGCAATTTATCCGTATTAAGAGAATCAGATGTCCGATAACGCTCAACTTACCGGT',
 'CCTCTGAAGACCTCGTCACGTTATACGGAACAACATTTAACTCCAGCGGTCTGAAAATGCGCGGCAACTTACGCAGCAAGA',
 'ACGCAGCAAGAACGCCGAGCTGATTGAAAAGGTTAGAACATCCTATGAAATTCAAAACAAACAAACTCAGCCTTAATCTTG',
 'ACGCCGTTGCTTACAACAGCAGCGATGTAAAAGACATCACTGCCGACGTACTGAAACAGGTTAAATAAGTAATGCCTTCAA',
 'TGTCCTGACTAGTCTTTACACTCTTTACAGGAACCATTGTCGTACATGATGGCCCAACCAATTGAGTGTACCGCTGTCGAC',
 'AAAATATCTTTATTTTTGGTCATACCGTGGAACAAGTGAAGGCAATTCTGGCCAAAGGCTACGACCCGGTGAAATGGCGGA',
 'CTCCGGTAATTTTTTTAAAAATTTTCTGAACTCTTTCTTCCCAGGCGAGTCTGAGTATATGAAAGACGCGCATTTGTTATC',
 'GCACTGCAAGGTTTATCAAAAATTATGGAACTTATTGCCCATCGTGATGCTCCAATCATTATGGCCGGAGCAGGAGTCCGT',
 'TGGAGTACGCATGGTTTAACAACGTCGAAACCAAACCGGGCATTGGTTATCCGAAAAACTGGGAAGATCAGGAAGAGTGGC',
 'ATCCAGTGGTATTATTGGCCATTGAAAGAACCTTTTTACATTATGAGCGTCAATATCAGTGTACCGTTAAATCCGATGATT',
 'GTGAGTTCGGCCTCTGGCACCTGGAGCCGGAACAAATCACTCAGGGCTTTGTCGAATTCCATGACTATTTAGGTCTGTGTA',
 'GATTCGGATGTGATGGTATGATTACAGACATTCGTGTCTGAGATTGTCTCTGACTCCATAATTCGAAGGTTACAGTTATGA',
 'CCTGACTACTGTATGTTACTTTATCCTGAACTACGCACCATTGAAGGTGTCTTAAAAAGTAAGATGAGTGGGTTAGGCATG',
 'TACAAATAATGCTGCCACCCTTGAAAAACTGTCGATGTGGGACGATATAGCAGATAAGAATATTGCTGAGCAAACCTTCAC',
 'TGCGTAATTTATTCACAAGCTTGCATTGAACTTGTGGATAAAATCACGGTCTGATAAAACAGTGAATGATAACCTCGTTGC',
 'AAGTGGCGGCGCGTTGAAAGAAATTTCGAACCCTGAGAACTTAATGTTGTCAGAAGAACTGAGACAGATAGTTTTCCGAAC',
 'CAGGAATTAAGGACAGCGGTCATTTAATTCCAGGACACGGTGGTATTTTAGATCGTATTGATAGCCTGACGGCTGCGGTAC',
 'TTATTAATCTGTTAACATTACGTTATCTAAAATATCTGGTAAAAAGTGGACTAAACGGTCAAAACAGTTGCACATAAAACA',
 'AAAATGAAATTTTTTTGCACAACCGCAGAACTTTTCCGCAGGGCATCAGTCTTAATTAGTGCCACTGCTTTTCTTTGATGT',
 'TCGAAACAATTCTTATGGTCAGGCTGGCGAACTAAGCGCCTTGCTATGGGTCACAATGGGCGGTTTCATTTGGCTGACGCT',
 'TAAATAAACAATGATGAAATCCAAAATGAAATTGATGCCATTATTGGTGTCAGTAACCTTGATAAGCGGTTGCACAGTACT',
 'CGCGACCCGTGGGCGGCACAGGTGAGCCAACTTTCGCTACCAAAACTGGTCGAACAGGTGGCGTTAAATGCCTGGAAAGAG',
 'ATAAAGTCATTTTTTATTCAAATATAAGGAACTTAATATTTAAAAAATGTTCCATACAATTCCTCATCATAAATGACACCG',
 'TTTTCAGAAATTGCGCGTAAATTTTTCGCACTTAAAGAATATTTATTAATCTAACGCAATATATTCGGTCGTAAAGGAATC',
 'TTTATTTACGTAACAACGTCGCATGGAAGAAACTTCCGGGCAAAGAATGAATCTTAAGAGTATGCCCTGAGAAAAAAAGGA',
 'CCGATGATCCTCATCGTAATCCAACCGAAACTTTACCTGATTCTGGCAGTCAAATCGGCTATCACAAAACAAGGATAAGGT',
 'GCTTGTTTTTATGAAGTAAAAGAATAACGGCACTTTTTGGTGAATTTGCACTCCAAGCAACGTTATTGAATAACCAAAGGA',
 'CAAACTGGATGAGGTACGCACCAGCGAACTTTTCGACGTTTGGTGGGACTAAGAAAGCATACGGGCGATGACAAATGCAAA',
 'AAGCATACGGGCGATGACAAATGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTGGAAAGATGCACGATCGAGTAGGC',
 'AATACAGACAAAGAGCATCTGCGAAAAATTGCACGCGGGATGTTCTGGCTGATGCTGCTTATTATTTCTGCAAAAATGGCG',
 'ATTTTGCGCCAAATTGCCATGCAACGGGCAATTTGACGGGCGTAAAAGTTTGAAGCAGTGGCAAGACCTGACACAGAGGAT',
 'TTATGTCACATAAGTGACGATGAACGGCGAACTTAATGCGATCTTTTTTGTCAGTAGATAGTATTTTGCGCCAAATTGCCA',
 'TGAGTTCAGGTTTATTTCACTTCTTCCGTGACATTTTCATGTTCTTGCGGTCTAACACGAAGTGTTTTTAACGTCATTTAG',
 'TATATTTGAAATCAAGTTTCGCATATTGAAATTTTAAGCCAAAAAAGCGATCAAAAAAACAAGGAAGCCTGGGATGAAAGT',
 'AAAACAAGTTGATTTGATATATTAAATGAACAAATTAATCTTGATGGCAGTCTGATTATTGGTGAAGTTTATAGTCAGTTT',
 'CCAGAACACCCATCAGGCGCGTCCTCATCGGCTACGATGTAAAAATGGGTCTGGAAATGAACTTTTCAAGCCTTATCAGCG',
 'AAAGTTGTAATAAGCTTGTCTGAATCGAACTTTTAGCCGCTTTAGTCTGTCCATCATTCCAGTAAATGATTACTCTTGTAT',
 'GCAAATGACAATACCCGGAAAATCCTTCTGAACTCTTCACCTTAAGCAATATCAAAAAAAATGGTAATCCATAAGATCATT',
 'GACCTTTGTTACAATTAGATTCAATTTGAATTTATGTTTTTGAATGCTTTCTTATCTCACGATTTAACAGGGAATAGTTCA',
 'ATCCGCATTCCTTCGCATCGTAGTGCTCGCATTCAGGAAATGCATATGCTGACGGTAAATTGCCTGTGCGATCTGATCGAT',
 'AACGGAGCGGCCCAGCTTACCTGCCATTGCACTAAATACTGATAATGTTGTCTTAACGGCGATTGCCAACGATCGCTTACA',
 'GCGGGAAATTCGATAAATAGCACATATGATTAAAACTCAGACCCAAGTGGTCGGATCACCTGCATATCATAAGAAGGAAAC',
 'AATTGCGATCTAAATCAAATTAATCGGTTAAAGATAACCGCAGCGGGGCCGACATAAACTCTGACAAGAAGTTAACAACCA',
 'ACCCACTAATCGTCCGATTAAAAACCCTGCAGAAACGGATAATCATGCCGATAACTCATATAACGCAGGGCTGTTTATCGT',
 'AAAAATGGCTGTTTTTGAAAAAAATTCTAAAGGTTGTTTTACGACAGACGATAACAGGGTTGACGGCGATTGAGCCGACGG',
 'CCGCGTCTTTTCCCCGCTTTGTTGCGCTCAAGACGCAGGATAATTAGCCGATAAGCAGTAGCGACACAGGAAGACCGCAAC',
 'GCACCAGTACAAGCAGCCTGATGTTTGACGAGTATTTAACTTGTTATGAATAACATAGAATAGCAGCCATTCACTTTTTCT',
 'CAATTTCGCGGCGGGTGGCATCAGCAATAAAGTTTCCCCCCTCCTTGCCGATAACGAGATCAACTTGTTTTCAGGAAGGTG',
 'TGTGACGCAAAGAGGTTTTTGGTCATAAGTAATTACCGTCAAGTGCCGATGACTTTCTATCAGGAGTAAACCTGGACGAGA',
 'CTCGGCGTAATCTCCGCGGGATATTCATAAAGTTTTTCCTTTCCAGGCCGAAAATCTTGCATCGGTCCACAGGAAAGAGAA',
 'AGTTGTAAAAAAAGCCTGATCACCACTAACGTAAATCACCCGAGTTGCCGATAACCATCCACGGTTACCTGAACGATAACA',
 'AGTGGTCGGATGAGTAGTAAAATTACACAAAAGGCGGTACTATTTTCATCAGATAAACAAATTCATTTTTCCGGTGCCATT',
 'GCTGTTTTATTGTTCATATAAATCTTAAAAGCAGAAATTTATCTGTTTCCCCCTTTAAAAATTCGGTGAATACCCTTACTT',
 'AAAAGCAGAAATTTATCTGTTTCCCCCTTTAAAAATTCGGTGAATACCCTTACTTATTGGTATACTGAAGTTGCTTCAGAT',
 'TTACGTTCTTACACTTTATCTGTGGTTTAAATCGTCCCGGAGTTGCCCTATATTAGCCAAACGTAATTATTTGGTTACAGG',
 'TTTTCACATTAATCTGGTCAATAACCTTGAATAATTGAGGGATGACCTCATTTAATCTCCAGTAGCAACTTTGATCCGTTA',
 'GCGTAACAACAAAAGATTGTTATGCTTGAAATATGGTGATGCCGTACCCATAACACAGGGACTAGCTGATAATCCGTCCAT',
 'TTAAACATTCTCTGTAAGTGCCACTTGGAATAACCTGCTTTCGCCGCTACATTGTCGAGCGACAGGGGCTGATCCAGATGA',
 'GCACAAAAAATTTTTGCATCTCCCCCTTGATGACGTGGTTTACGACCCCATTTAGTAGTCAACCGCAGTGAGTGAGTCTGC',
 'GTCTGCAAAAAAATGAAATTGGGCAGTTGAAACCAGACGTTTCGCCCCTATTACAGACTCACAACCACATGATGACCGAAT',
 'GGCAGTTGAAACCAGACGTTTCGCCCCTATTACAGACTCACAACCACATGATGACCGAATATATAGTGGAGACGTTTAGAT',
 'CTACCAAAAATAGTTGCGCAAACATCTTGAAATTTTGCTAATGACCACAATATAAGCTAAACGCGATTCGCAACCCATTCA',
 'ATCACATTTTTATCGTAATTGCCCTTTAAAATTCGGGGCGCCGACCCCATGTGGTCTCAAGCCCAAAGGAAGAGTGAGGCG',
 'AAGCGGTGGAGATCTTCTCTGCCGCTTTTTTTTTCATCAATCATCCCCATAATCCTTGTTAGATTATCAATTTTAAAAAAC',
 'CAGAATTTTTTTTCTTTTTCCCCCTTGAAGGGGCGAAGCCTCATCCCCATTTCTCTGGTCACCAGCCGGGAAACCACGTAA',
 'GATTGATGACAATGTGAGTGCTTCCCTTGAAACCCTGAAACTGATCCCCATAATAAGCGAAGTTAGCGAGATGAATGCGAA',
 'AGAAAACCAAAAGCGTGGTCGCCCCTTGCAATATCAGAATCGCGGCACCATTAAGTACGTATGGACCACCAACGGCCCGGA',
 'CGCTGCGGTGTATACCTGATGCGTATTTAAATCCACCACAAGAAGCCCCATTTATGAAAAACGCGACGTTCTACCTTCTGG',
 'GAGCATACCGGTCTGGACGCACACCTTGATTTATTACTTTCCACCCACACATTTGGTTATCCGAAAGAGGATCAGCGGTTA',
 'ATACAAACTGCATTCGGCTCGCCGCCGGGGGTTGAAACCCTCAAAATCCCCCCCATCTATAATTGCATTATGCCCCGTACT',
 'GTGGGGCAGTGTCTACGATCTTTTGAGGGGAAAATGAAAATTTTCCCCGGTTTCCGGTATCAGACCTGAGTGGCGCTAACC',
 'ACGAGAGCAGGATCACCTGCTCTCGCTTGAAATTATTCTCCCTTGTCCCCATCTCTCCCACATCCTGTTTTTAACCTTAAA',
 'TCTGGTGACTTACGCACTATCCAGACTTGAAAATAGTCGCGTAACCCATACGATGTGGGTATCGCATATTGCGTTTTGTTA',
 'TGCAAAAAAAAGTCCGCTGATAAGGCTTGAAAAGTTCATTTCCAGACCCATTTTTACATCGTAGCCGATGAGGACGCGCCT',
 'CAGCTGGAAGTGCATTTGTTAGATGTTGCAATGGACCTTTACGGTCGCCATATACAAGTAGTGCTGCGTAAAAAAATACGC',
 'AACGAGAACAAGAAAGTTAACGCTGGTTGATTTTCCGAATTTAGCCCTTAAATCATCAACAATGCGTGTGGATGCCATTTC',
 'GAAGGTTGCGCCTACACTAAGCATAGTTGTTGATGAATTTTTCAATATCGCCATAGCTTTCAATTAAATTTGAAATTTTGT',
 'TAATTTTTCCTCTATTCTCGGCGTTGAATGTGGGGGAAACATCCCCATATACTGACGTACATGTTAATAGATGGCGTGAAG',
 'AACTTTCTCACCTTCAACATGCAGGCTCGACATTGGCAAATTTTCTGGTTATCTTCAGCTATCTGGATGTCTAAACGTATA',
 'AGTCTGCCCTGGCGGAATTGGGTATTGATTTCCAGTCAGATGCACAGCATGTGACCATCAGGGCAGTGCCTTTACCCTTAC',
 'CTGCTGGGTGGGGCGGGTGATGTGCTGGCGAACAGTCAGTCTGACCCCTATTTAAGCCAGGCGGTGCTGGATTTACAGTTC',
 'TAACAAAAAACCTCGCTCCGGCGGGGTTTTTTGTTATCTGCTTGCCCCCATATTGACTGCATCTGTTCATTCCTGGAGATG',
 'ATGATGCCAAAGCGAACGACAAGGTTGTAGTTTTCACTACATGTCCATACATAAAATGGGGTAACATTCACGCGCCTGGTA',
 'CGCAACCTGAAAAATGCCTTTCGTCTTGAATTGCCCGTGCAAGGTCGCCATATGGTGATTGTGGATGATGTCGTTACCACC',
 'TTTTTCACTTTACCTCCCCTCCCCGCTGGTTTATTTAATGTTTACCCCCATAACCACATAATCGCGTTACACTATTTTAAT',
 'TAATCAGCTTTTTTCTGAATCCTCCTCGTAAAATTGCAACGCCAACACCATCTTCCTGACGAAAGTGCTATCTTGTCCGGC',
 'ATTCAGATTGATGATCCTAACAATCCCGGCGAAAAAATGAGTCTGGCACCGTTTATAGAACGAGCTGAAAAACTCTGTTAA',
 'CTTTTTTATTTGTATTCGGTGACTTTCTGCGTCTTGTGGGCTGACAATTGCCCCCGTTTCTTGTCACAATAGGCCTTTGCG',
 'CGCCGCGAAAGCGTAACGTTTCTCATTGAAATTCACTACACTTAACCCCATGCTACACACATTATGTAAAGCGCCTGTTGA',
 'AAAAGATTCGTTGACAAAAAGTGACAAAATTATGAGATTTTCATCACACATTTTGACATCAGGAACGGTATGCTGAATTCA',
 'CGGGTTGCCAAAAGCCAGGTGGTGATTGAAAAAGGCGAACTTGGCCGCCACAAACAAATTAAAATCATTAATCCGCAACAA',
 'GCACTATTCACATGCAAAACCAACATCCGCCATGAAGGACTAGCTAAAACCCAAACTAGTTTGTTGCAATTAGCATCCTTG',
 'CCGCGGATTATGCACGCTGCCAGGGCTTGAGAAATTAGCCGACGCCCCCCAATTTAAATTCAAAGAGATACGTCATGTAGG',
 'ATCGTATTTTTTGCTTACGTTGGGATTGAAAACGGGTCATTCTACCGCCATCTCCCATATATCACCAAATAGGCGCGTAAA',
 'TTTAGCAAATCAATACACTTCAGGGGGGTATTATTGTAGAGTTTCCCCATATGTTTCTATGGGATCCAGGAAATGACAATC',
 'CACATTGCCGTAGAAGAGTGCGGATCAGTTTGCATACGCTGGTTAATTTCTGTATGATTTCGCGCCTTCGTACGAAATGAT',
 'CAGAAAATTATTTTAAATTTCCTCTTGTCAGGCCGGAATAACTCCCTATAATGCGCCACCACTGACACGGAACAACGGCAA',
 'CAGAAAAAAAGATCAAAAAAATACTTGTGCAAAAAATTGGGATCCCTATAATGCGCCTCCGTTGAGACGACAACGTGAAAC',
 'TGAAATAAAAATGCATTTTTCCGCTTGTCTTCCTGAGCCGACTCCCTATAATGCGCCTCCATCGACACGGCGGATGTGAAT',
 'CTATACTTATCTTTACATCTACAAAACACTACTTGAGACAATCATCGCAATATTAGTTAAATCGCGGTTTTTGATTAGTTT',
 'TCGTGAACAGAGTCACGACAAGGGGTTGATATCCGCAGAGAGCGAGTCCATATCGGTAACTCGTTGCCAGTGGAAGGTTTA',
 'CTCACAAATAGGAATTCATCAAGATCTGGACATCTGATGAGCAATCCCTACAATCGCCGCGTACTTTAATTTTTCAGGATA',
 'TTCTGCCGCCATTTCGGTGTAACAGGTGCTGGAACCGTAAAAAAGACCCATATTCATAACGTAAGCTTCTCGATTCTGCTG',
 'GCACTTGCTTACATAACAATATACAATTGCTCGTTGAAAGAGTGAGCTAAAATCCCTATAACAGTAGAACCCTCCCGAGTG',
 'CAACCAGACGCAAAGTGATAAACCAGTCGAAAATCCCGGCATCGCCGCCCGCTTTACGTTGGGACCGGAAGCGGTGGTGGA',
 'CACTGGTTTGGTTAAAAATTAAACACTTGAAAGTGTAATTTCCGTCCCCATATACTAAGCATCAGTAAAAAACTCCCGCCT',
 'TCTCAGGCCTGCCGTTCCGGTGGGCCTTGTTTTTTCTCTCTTTATCCCCATCTTTATTGCAATGCTTGCGCCTTTTTCCTG',
 'ATCATTCAATTTGTTATTTTTGTGTTGCAATTCATTCTCCGACACGCCATTTTCTTTCTCTCGCAAATTCGTTTTGGATGC',
 'TCGCCGGTCGATGACAACACGGGCAGTTGATAATCAATGGCCTGGCCCCCACATTCATATCCTTACGAATGATTTTTTTTC',
 'ACAACCCAATAATTCGTGTATCAGAGTTTAAACAGAGTTGTTTGCCACCATCTCAAATCTGTCGTGGATAAATCCTCCGTA',
 'GCTTATAGAGGACGTGCTTGCCGCTGGAGAAATACAACCGCCGGCCCCACCTGAAGATGCACAGCCTGTTGCCATTCCGCT',
 'ACGTAAAAAAACCCGCCCCGGCGGGTTTTTTTATACCCGTAGTATCCCCACTTATCTACAATAGCTGTACTCTTTTTGTTC',
 'AGATGACTAATATCCTGAAACTGACTGAACTAATTGAGTCAAACTCGGCAAGGATTCGATACTATTCCTGTGTAACTTTCT',
 'CCCGTAATATCAGGGAATGACCCCACATAAAATGTGGCATAAAAGATGCATACTGTAGTCGAGAGCGCGTATGCGTGATTT',
 'ATAATCAGTACGTTACCAAACTATTTTCTTTATTGGCACAGTTACTGCATAATAGTAACCAGTGGCTCATTCACCGACTTA',
 'GCATGATAACGCCTTTTAGGGGCAATTTAAAAGTTGGCACAGATTTCGCTTTATCTTTTTTACGGCGACACGGCCAAAATA',
 'GCCGCATCTCGAAAAATCAAGGAGTTGCAAAACTGGCACGATTTTTTCATATATGTGAATGTCACGCAGGGGATCGTCCCG',
 'TTAAAAATCTCTTTAATAACAATAAATTAAAAGTTGGCACAAAAAATGCTTAAAGCTGGCATCTCTGTTAAACGGGTAACC',
 'AATTAATTTCCTTAAATAACAGTAAATTAAAAACTGGCATGATTTGTGAATGTATCGGCGCATTAACTGTCATTGCTGGAG',
 'CATAACTTATTGAATATATTGAGTTAATCAGAATGGCATCCTTTATGCAATATGAAATGCAATGTTTCATATCATTTTCAA',
 'CATCGACATTATTCACCGCAGGGATAATCAACACTGGCACAATTATTGCTTGTAGCTGGCAATAGTTAATGGGAGGCGATA',
 'GCGAAAAAACCGCGCCGTATCGAAATCAACTAATTCCCTAAGGCCGCCTGGCGCGGCCTGACATCTCCATGCTCGCCGTCA',
 'TTGGTTAGCTTGTACATCAACACCAAAATAAAACTGGCAAGCATCTTGCAATCTGGTTGTAAGTAATGGCGGCACTTGGGC',
 'TTATTTATAGAGTAAAAACAATCAGATAAAAAACTGGCACGCAATCTGCAATTAGCAAGACATCTTTTTAGAACACGCTGA',
 'AATCAGATCTTTATAAATCAAAAAGATAAAAAATTGGCACGCAAATTGTATTAACAGTTCAGCAGGACAATCCTGAACGCA',
 'GGGCGTTTTGCTGTTAAATCAATAGATTATTTTTGGCATGATTCTTGTAATGCCAGCAAGAGATTTCATATTTGGGAGAGC',
 'TGGATATGTTCCCACACACGGGACATCTGGAATCGATGGTACTTTTCTCGCGCGTTAAATAGTTGCGATTTGCCGATTTCG',
 'CCGCACCGCTAAGTTCGGCAGATCGCGAAAAACTGGAACGCTTTTCGCATTCTGAAGGCCTGGATCTGTATCTCGCCCCCG',
 'TGAATTAAAAAATTAAGCTGCTTATTTAATTTTCTGGCACGACGGTTGCAATTATCAGGACAGCAAACAACGAAAAGAGAA',
 'CCTACCTCCCCTAACGCTTATCGTCGTTTCTGGCGTAAATCTTGCCTGCTTAGACTAAATCTTTGCCATAAGAACCAAATG',
 'GCCCGGGAAAAATATGCTCGCGGGCTTGCTATCTCGCTGACGGACAGGCAAATTGATGACCAGCTTTTAAACCGACTCCGT',
 'TGAAGGTTATTTACATGTTAGCTGTTGATTATCTTCCCTGATAAGACCAGTATTTAGCTGCCAATTGCTACGAAATCGTTA',
 'ACTCCGCGGTTCGACCACTTTTTTATCCAAAGTTTCGGGCTGTTATGTTTTAATGTGCAACATTCATGGTCTGTTGGGGGC',
 'TATTTTTAATTAAAATGGAAATTGTTTTTGATTTTGCATTTTAAATGAGTAGTCTTAGTTGTGCTGAACGAAAAGAGCACA',
 'AAAGCGCGGCAACTAAACGTAGAACCTGTCTTATTGAGCTTTCCGGCGAGAGTTCAATGGGACAGGTTCCAGAAAACTCAA',
 'TCTTTTATCAATTTGGGTTGTTATCAAATCGTTACGCGATGTTTGTGTTATCTTTAATATTCACCCTGAAGAGAATCAGGG',
 'TTTATGTTGCTTTTTTGTAAACAGATTAACACCTCGTCAAAATCCTGCTATTCTGCCCGTTGCGGTACTGGGCATTTACCC',
 'ATCGTGGTAAGACCTGCCGGGATTTAGTTGCAAATTTTTCAACATTTTATACACTACGAAAACCATCGCGAAAGCGAGTTT',
 'GTTCGTGAATTTACAGGCGTTAGATTTACATACATTTGTGAATGTATGTACCATAGCACGACGATAATATAAACGCAGCAA',
 'CGCAAAGCTGACCGCACAAAAGGGGAGTGCTTTTCTGTGCTTAGCGGTTAGAATAGTCTCATGACTATATCTGGAGTTGAC',
 'ATACTAAACAAAACTGCCAATACCCCTACATTTAACGCTTATGCCACATATTATTAACATCCTACAAGGAGAACAAAAGCA',
 'TTCAGTGATAATTATCACATTTCAATTGCACATTAATGGATATTCTTTAATAATCTCGCGACGTTTCTTTATGATAAATAA',
 'TTCAAAAATGTTTGTTTTTCACGCGCTTTACAGCCCGAAAAGGCCGGAAGATACTTGCCCGCAACGAAGATTCCTTCATAA',
 'TCGTTTTATTTCTTTTTTCTCCATTGAACTTTCAGTTTCTTTTCTATAGATTTTAATCAACGAAAGACATCACCAAGTGAA',
 'ATCGATTTGATAATGGAAACGCATTAGCCGAATCGGCAAAAATTGGTTACCTTACATCTCATCGAAAACACGGAGGAAGTA',
 'TAGGTAAGAGCTTAGATCAGGTGATTGCCCTTTGTTTATGAGGGTGTTGTAATCCATGTCGTTGTTGCATTTGTAAGGGCA',
 'GATAAGAATGTTTTAGCAATCTCTTTCTGTCATGAATCCATGGCAGTGACCATACTAATGGTGACTGCCATTGATGGAGGG',
 'CCCTTCACAGAATTGTCCTTTCACGATTCCGTCTCTCTGATGATTGATGTTAATTAACAATGTATTCACCGAAAACAAACA',
 'CATCTATCATCTAAAAAACCAGAAAAACAAATAACATCATGTTTTTAAACTAATTAAATGAAATAAAATTTTAAGCCACTC',
 'GTGAACGGTCGAATTAGCCAATATCTGACGAAAATCGGTTGAAAAAGTGGCATAATGGGGAGTTGTCAACTATTGAAATGA',
 'TACGGTCTGGCTGCTATCCTGACAGTTGTCACGCTGATTGGTGTCGTTACAATCTAACGCATCGCCAATGTAAATCCGGCC',
 'TCACGTTGTAAATTGTTTAACGTCAAATTTCCCATACAGAGCTAAGGGATAATGCGTAGCGTTCACGTAACTGGAGGAATG',
 'AAAGCACTGAAGCACAACAATCGCAGTTGCAATTATTGCGTACAGCCAGTACATTCTGGCGTTTTCGAGCACAGGCGCAGG',
 'CCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATACCCGTTTTTTTGGATGGAGT',
 'CAATGTGGACTTTTCTGCCGTGATTATAGACACTTTTGTTACGCGTTTTTGTCATGGCTTTGGTCCCGCTTTGTTACAGAA',
 'CATATTTATGCTGTTTCCGACCTGACACCTGCGTGAGTTGTTCACGTATTTTTTCACTATGTCTTACTCTCTGCTGGCAGG',
 'AATTCTGCGATGTGATATTGCTCTCCTATGGAGAATTAATTTCTCGCTAAAACTATGTCAACACAGTCACTTATCTTTTAG',
 'GAATACAGAGGGGCGAATTATCTCTTGGCCTTGCTGGTCGTTATCCTGCAAGCTATCACTTTATTGGCTACGGTGATTGGT',
 'TTGGGTGTCCGGCCCCTCTTAGCCTGTTATGTTGCTGTTAAAATGGTTAGGATGACAGCCGTTTTTGACACTGTCGGGTCC',
 'GATATATGTCAACGAAGCGTAGTTTTATTGGGTGTCCGGCCCCTCTTAGCCTGTTATGTTGCTGTTAAAATGGTTAGGATG',
 'TGACGAAAGCTAGCATTTAGATACGATGATTTCATCAAACTGTTAACGTGCTACAATTGAACTTGATATATGTCAACGAAG',
 'TTTATAAAAAATAAATCTCGACAATTGGATTCACCACGTTTATTAGTTGTATGATGCAACTAGTTGGATTATTAAAATAAT',
 'TAACGTAAGTCGCAGAAAAAGCCCTTTACTTAGCTTAAAAAAGGCTAAACTATTTCCTGACTGTACTAACGGTTGAGTTGT',
 'GGGCGAGTGGCGTTAAGAGTGGTTGTTGATTTTTTGCACTGGCAGGATTACACTCGCGCCGTTAAATAACCAACTGGAGTT',
 'AATGGCGGTAATTTGTTTTTCATTGTTGACACACCTCTGGTCATGATAGTATCAATATTCATGCAGTATTTATGAATAAAA',
 'TTTCCTGCATCGCTGATTTCTGATTGCCATTTAGTGATTTTTTATGCATATTTTGTGGTTATAATTTCACATTTGTTTATG',
 'AAAACATTCACCTTACGGCTGGTGGGTTTTATTACGCTCAACGTTAGTGTATTTTTATTCATAAATACTGCATGAATATTG',
 'GTGACAAAGATTTATGCTTTAGACTTGCAAATGAATAATCATCCATATAAATTGAATTTTAATTCATTGAGGCGTTAGCCA',
 'TTCAGCCTTCTTCAGGGCTGACTGTTTGCATAAAAATTCATCTGTATGCACAATAATGTTGTATCAACCACCATATCGGGT',
 'AAACGGCAATACGCCACGCGCACGTTGCTGACGAAAACAGCCATTTGCAGTATACTCCCGCCCTAATTTCTTTAACTGGTG',
 'GTAAATAAAAATGTACGAAATATGGATTGAAAACTTTACTTTATGTGTTATCGTTACGTCATCCTCGCTGAGGATCAACTA',
 'CTTAGTCGCCGAATGTACTAGAGAACTAGTGCATTAGCTTATTTTTTTGTTATCATGCTAACCACCCGGCGAGGTGTGACA',
 'CGGCGAGGTGTGACACACCTCGCACTTGAAATCAGCAGCGATTGGTTTATCGTGATGCGCATCACTTCCCGGCAGTCCTGC',
 'TTACGCTGAACGTGTTTCATCTATTTGACGCGCGCAGGTATTTAGCATACAAGGAGTACCGATTTGAGAGTTGGTGCTCTT',
 'CAGAGGGATGGGTGATTTATTCAGTTGCCAAACCCGCTGGAGTATTGAGATAATTTTCAGTCTGACTCTCGCAATATCTTA',
 'TAAATGTAATTTATTATTTACACTTCATTCTTGAATATTTATTGGTATAGTAAGGGGTGTATTGAGATTTTCACTTTAAGT',
 'TTCAACCATGCATAAAGCGGGTGCATTCGCTGCCGCATACCATTATTCTTGATCTGACGGAAGTCTTTTTGTAACAATTCA',
 'TGCATTCGCTGCCGCATACCATTATTCTTGATCTGACGGAAGTCTTTTTGTAACAATTCAAACTTCTTTGATGTAAACAAA',
 'CATTCGTTAAGTCATATATGTTTTTGACTTATCCGCTTCGAAGAGAGACACTACCTGCAACAATCAGGAGCGCAATATGTC',
 'TTTTAACTTTTAAAGCAGAAATATTGCATAATTATTCTGTCAAAGGTACTATCTTCGACCTCAATAGCTATCAGACTGCCA',
 'ATAAAAAATGAACAATTCACTCTCTTGCTTATTTAGTGACAACTATTCATGATTTTGTGAAACCGGTTTCTTAATTCCGTT',
 'GAGTTAGGCTTTTTATTGAATGATTATTGCATGTGTGTCGGTTTTTGTTGCTTAATCATAAGCAACAGGACGCAGGAGTAT',
 'TCATTCAATAAAAAGCCTAACTCACTTTTGATTCATTAAAAAAGAAGGCTAAAATAGAATGAATCATCAATCCGCATAAGA',
 'ACCGACACTTAAAGTGATCCAGATTACGGTAGAAATCCTCAAGCAGCATATGATCTCGGGTATTCGGTCGATGCAGGGGAT',
 'TTATTCACCTTTTGGCTACTTATTGTTTGAAATCACGGGGGCGCACCGTATAATTTGACCGCTTTTTGATGCTTGACTCTA',
 'GAACATAGGCTTCGATTTATTGCGCTATCTCTGTGGCAGGATTGTGAATAAAGTGTCAACAAGCAACGGGGCATCGCCCAT',
 'TTTATGTGATTTGTATCACATAAAGATTGATTTTTGTGATGGTTGTCATATTATAAGCGCAAAGACAATAACACCTGTATA',
 'ATTGAGCAAGCGTTCAAAGCCCTATGTACAGAACTCAATGCACAAGGCAGTATTAACGTCGTCAATTATTCCCAACATGAT',
 'GATAAGTTTTAATTTCAATGGTAGGTTTATTTCTTAGCTTTCGCTAGTAAACTGATAATCAGACAAAATGGTGACATGAGG',
 'CGTAACAATTAAGACACATTTTATATTGAACGTCCAATCAATAACCGCTTTAATAGATAAACACCGCTGATGAATGGAGTG',
 'TTTATCTATTAAAGCGGTTATTGATTGGACGTTCAATATAAAATGTGTCTTAATTGTTACGAATTTGATTTTAAATAGTAA',
 'GGAGTCCGCATAAACGGAGTGTGTTTTTTGACTTACTCGTAAGCCGTTCTACTCTTCAAAGAGTGGAAGCGAAGGAGTCAA',
 'ATTAATGATTGTTATAAAAAATATCTTGTATGTGATCCAGATCACATCTATCATTTAGTTATCGATCGTTAAGTAATTGCT',
 'AAACGGTTATGTTTTGGTATTAAAAGAAAGACACAAGAAGATATGTCTGTTACCGTCTTACTCTCGCCTCACCCATTACCC',
 'TCATCCAATTTAGCTGAAATCTTATTTATACTTTGTACAATTTTAGCGTATATTGTACAAAGTATTATTGGGTCGTGTACA',
 'CTGGTAAAAGAAACACTGATGCGAGGCCTGTGTTTCAATCTTTAAATCAGTAAACTTCATACGCTTGACGGAAAAACCAGG',
 'GAATTCCTATTTGTGAGCTACGTCTGGACAGTAACTTGTTACAACCTGTAGCATCCACTTGCCGGTCCTGTGAGTTAATAG',
 'TTTGTGTTATTTCACCTAATCTTTAGGATTAATCCTTTTTTCGTGAGTAATCTTATCGCCAGTTTGGTCTGGTCAGGAAAT',
 'ATAATATGTAAATAAACCCATCTATAGATGGTAAAAATAGGTTGTGGCAATTATCATTGCATCATTCCCTTTTCGAATGAG',
 'GATGACATAAGCAGGATTTAGCTCACACTTATCGACGGTGAAGTTGCATACTATCGATATATCCACAATTTTAATATGGCC',
 'CGAAACAAAAATGTGATACCAATCACAGAATACAGCTTATTGAATACCCATTATGAGTTAGCCATTAACGCGTCCACGAGG',
 'TAATATAAAAAATCCCGCCATTAAGTTGACTTTTAGCGCCCATATCTCCAGAATGCCGCCGTTTGCCAGAAATTCGTCGGT',
 'GAAATTCGTCGGTAAGCAGATTTGCATTGATTTACGTCATCATTGTGAATTAATATGCAAATAAAGTGAGTGAATATTCTC',
 'TTTCTTTAATAATAAAACGAATAACTTGCAGATTTGAAATGCATGCATTATTGTCTTTAAACAATTCAACACATCTTAATA',
 'TGGAATAAGATGCGGGTTTTTATTATTTGTTATGCCGGGCATTAGACTTTAACAATAACGGGAAATCTGAACTGCCCGGAG',
 'TGGTTCAACTATCAAAAATCGCTCACCCTTTTTCACCTGTTTAAAATATGTTCAGCAACCCATCTTGATGGCGACCTCCTC',
 'TTCCAGGCCTGTTTCAAATAATTATTTGCAGTGCAACTAATTCCATGTATATTACTACCCATATATAGCGTCTATAAAATT',

In [160]:
encoded_sequences = one_hot_encode_dna(sequences)

In [173]:
labels = df_for_cnn["strength"]

In [174]:
labels = np.array(labels).astype(np.float32).reshape(-1, 1)

In [175]:
labels.shape

(323, 1)

In [176]:
labelencoder = LabelEncoder()

In [177]:
labels = labelencoder.fit_transform(labels)

c:\Users\Sergio\miniconda3\envs\python3_10_9\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [178]:
labels

array([4, 4, 3, 3, 2, 3, 0, 3, 3, 3, 1, 3, 3, 3, 4, 3, 4, 4, 4, 1, 1, 2,
       0, 1, 0, 3, 1, 1, 2, 1, 3, 4, 4, 2, 3, 3, 4, 1, 3, 4, 1, 2, 4, 3,
       4, 4, 0, 2, 2, 0, 3, 1, 0, 3, 0, 1, 0, 4, 2, 3, 3, 3, 4, 2, 0, 0,
       3, 3, 2, 4, 1, 2, 1, 2, 0, 2, 3, 2, 1, 4, 4, 3, 1, 0, 2, 3, 0, 1,
       1, 3, 0, 2, 3, 2, 0, 4, 3, 2, 1, 2, 3, 2, 2, 4, 3, 3, 3, 1, 0, 2,
       2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 4, 0, 3, 0, 1, 4, 2, 1,
       1, 2, 0, 3, 1, 1, 1, 2, 4, 0, 3, 0, 0, 2, 0, 2, 1, 1, 2, 1, 2, 4,
       3, 0, 2, 2, 2, 2, 4, 4, 0, 0, 3, 0, 0, 0, 0, 4, 2, 1, 0, 1, 2, 0,
       4, 2, 3, 1, 3, 3, 0, 3, 1, 0, 2, 2, 4, 4, 4, 4, 4, 4, 2, 2, 1, 3,
       3, 4, 4, 4, 4, 0, 3, 1, 0, 2, 2, 0, 1, 0, 0, 3, 3, 2, 3, 1, 0, 0,
       2, 3, 4, 3, 0, 4, 2, 2, 1, 3, 0, 3, 2, 1, 2, 0, 0, 0, 4, 4, 0, 0,
       4, 4, 1, 3, 4, 1, 0, 2, 4, 1, 4, 4, 4, 2, 0, 1, 4, 3, 4, 2, 2, 0,
       2, 1, 0, 4, 1, 1, 1, 3, 1, 4, 4, 2, 1, 2, 0, 3, 2, 1, 3, 0, 3, 3,
       2, 4, 4, 2, 4, 4, 0, 3, 0, 0, 4, 3, 2, 4, 4, 4, 4, 0, 3, 1, 0, 2,
       1, 3, 4, 1, 1, 2, 1, 2, 4, 3, 2, 0, 1, 0, 1], dtype=int64)

In [179]:
labels = to_categorical(labels)

In [180]:
labels

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [181]:
labels.shape

(323, 5)

In [182]:
encoded_sequences.shape[1]

81

In [183]:
encoded_sequences.shape[2]

4

In [184]:
X_train, X_test, y_train, y_test = train_test_split(encoded_sequences, labels, test_size=0.1, stratify=labels)

In [ ]:
encoded_sequences.shape[0]

2676

In [ ]:
encoded_sequences.shape[1]

81

In [ ]:
encoded_sequences.shape[2]

4

In [185]:
model = Sequential([
    Conv1D(filters=16, kernel_size=7, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    Conv1D(filters=16, kernel_size=6, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    Conv1D(filters=16, kernel_size=5, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    MaxPooling1D(pool_size=4),
    Dropout(0.8),
    Flatten(),
    Dense(16, activation='relu'),
    Dense(5, activation='softmax')  # Salida única para clasificación binaria
])

# Compilar el modelo
model.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])

In [187]:
# Entrenar el modelo
model.fit(X_train, y_train, epochs=500, batch_size=32, validation_split=0.2)

Epoch 1/500
8/8 [==============================] - 0s 34ms/step - loss: 0.4192 - accuracy: 0.4741 - val_loss: 0.5100 - val_accuracy: 0.1897
Epoch 2/500
8/8 [==============================] - 0s 11ms/step - loss: 0.4118 - accuracy: 0.5172 - val_loss: 0.5107 - val_accuracy: 0.2069
Epoch 3/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4286 - accuracy: 0.4569 - val_loss: 0.5082 - val_accuracy: 0.2586
Epoch 4/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4179 - accuracy: 0.5043 - val_loss: 0.5077 - val_accuracy: 0.2414
Epoch 5/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4070 - accuracy: 0.5216 - val_loss: 0.5114 - val_accuracy: 0.2069
Epoch 6/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4068 - accuracy: 0.5259 - val_loss: 0.5083 - val_accuracy: 0.2414
Epoch 7/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4053 - accuracy: 0.5000 - val_loss: 0.5178 - val_accuracy: 0.2069
Epoch 8/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3919 - accuracy: 0.5388 - val_loss: 0.5120 - val_accuracy: 0.2241
Epoch 9/500
8/8 [==============================] - 0s 12ms/step - loss: 0.4117 - accuracy: 0.5000 - val_loss: 0.5160 - val_accuracy: 0.2241
Epoch 10/500
8/8 [==============================] - 0s 11ms/step - loss: 0.4073 - accuracy: 0.5000 - val_loss: 0.5081 - val_accuracy: 0.1897
Epoch 11/500
8/8 [==============================] - 0s 11ms/step - loss: 0.4057 - accuracy: 0.5776 - val_loss: 0.5066 - val_accuracy: 0.2414
Epoch 12/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3952 - accuracy: 0.5560 - val_loss: 0.5107 - val_accuracy: 0.2069
Epoch 13/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3950 - accuracy: 0.5517 - val_loss: 0.5110 - val_accuracy: 0.2414
Epoch 14/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3924 - accuracy: 0.5345 - val_loss: 0.5114 - val_accuracy: 0.2414
Epoch 15/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3907 - accuracy: 0.5776 - val_loss: 0.5066 - val_accuracy: 0.1897
Epoch 16/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3898 - accuracy: 0.5603 - val_loss: 0.5096 - val_accuracy: 0.1897
Epoch 17/500
8/8 [==============================] - 0s 12ms/step - loss: 0.3764 - accuracy: 0.5474 - val_loss: 0.5114 - val_accuracy: 0.2414
Epoch 18/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3925 - accuracy: 0.5129 - val_loss: 0.5184 - val_accuracy: 0.2069
Epoch 19/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4039 - accuracy: 0.5129 - val_loss: 0.5132 - val_accuracy: 0.2586
Epoch 20/500
8/8 [==============================] - 0s 10ms/step - loss: 0.4008 - accuracy: 0.5216 - val_loss: 0.5157 - val_accuracy: 0.1897
Epoch 21/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3862 - accuracy: 0.5517 - val_loss: 0.5159 - val_accuracy: 0.2414
Epoch 22/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3860 - accuracy: 0.5819 - val_loss: 0.5143 - val_accuracy: 0.2069
Epoch 23/500
8/8 [==============================] - 0s 14ms/step - loss: 0.4030 - accuracy: 0.5086 - val_loss: 0.5113 - val_accuracy: 0.2241
Epoch 24/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3956 - accuracy: 0.5172 - val_loss: 0.5137 - val_accuracy: 0.1897
Epoch 25/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3736 - accuracy: 0.5733 - val_loss: 0.5211 - val_accuracy: 0.2069
Epoch 26/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3784 - accuracy: 0.5647 - val_loss: 0.5164 - val_accuracy: 0.1897
Epoch 27/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3678 - accuracy: 0.5819 - val_loss: 0.5199 - val_accuracy: 0.2241
Epoch 28/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3833 - accuracy: 0.5690 - val_loss: 0.5138 - val_accuracy: 0.2414
Epoch 29/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3754 - accuracy: 0.5948 - val_loss: 0.5173 - val_accuracy: 0.2241
Epoch 30/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3668 - accuracy: 0.5603 - val_loss: 0.5175 - val_accuracy: 0.2069
Epoch 31/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3651 - accuracy: 0.5560 - val_loss: 0.5179 - val_accuracy: 0.2069
Epoch 32/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3728 - accuracy: 0.5560 - val_loss: 0.5312 - val_accuracy: 0.2069
Epoch 33/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3797 - accuracy: 0.5388 - val_loss: 0.5166 - val_accuracy: 0.2414
Epoch 34/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3698 - accuracy: 0.6034 - val_loss: 0.5170 - val_accuracy: 0.2069
Epoch 35/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3780 - accuracy: 0.5647 - val_loss: 0.5165 - val_accuracy: 0.2241
Epoch 36/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3850 - accuracy: 0.5647 - val_loss: 0.5205 - val_accuracy: 0.2241
Epoch 37/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3586 - accuracy: 0.6078 - val_loss: 0.5224 - val_accuracy: 0.2241
Epoch 38/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3668 - accuracy: 0.5819 - val_loss: 0.5251 - val_accuracy: 0.2069
Epoch 39/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3739 - accuracy: 0.5905 - val_loss: 0.5223 - val_accuracy: 0.2069
Epoch 40/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3589 - accuracy: 0.5948 - val_loss: 0.5234 - val_accuracy: 0.1897
Epoch 41/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3682 - accuracy: 0.5431 - val_loss: 0.5239 - val_accuracy: 0.2241
Epoch 42/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3515 - accuracy: 0.5733 - val_loss: 0.5290 - val_accuracy: 0.1724
Epoch 43/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3598 - accuracy: 0.6034 - val_loss: 0.5161 - val_accuracy: 0.1724
Epoch 44/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3436 - accuracy: 0.6034 - val_loss: 0.5240 - val_accuracy: 0.1552
Epoch 45/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3542 - accuracy: 0.5690 - val_loss: 0.5284 - val_accuracy: 0.2241
Epoch 46/500
8/8 [==============================] - 0s 9ms/step - loss: 0.3415 - accuracy: 0.6250 - val_loss: 0.5321 - val_accuracy: 0.1724
Epoch 47/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3447 - accuracy: 0.6164 - val_loss: 0.5339 - val_accuracy: 0.1552
Epoch 48/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3210 - accuracy: 0.6121 - val_loss: 0.5447 - val_accuracy: 0.1897
Epoch 49/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3739 - accuracy: 0.5431 - val_loss: 0.5246 - val_accuracy: 0.1552
Epoch 50/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3383 - accuracy: 0.6336 - val_loss: 0.5254 - val_accuracy: 0.2069
Epoch 51/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3691 - accuracy: 0.5603 - val_loss: 0.5318 - val_accuracy: 0.1724
Epoch 52/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3518 - accuracy: 0.6207 - val_loss: 0.5320 - val_accuracy: 0.1897
Epoch 53/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3290 - accuracy: 0.6552 - val_loss: 0.5273 - val_accuracy: 0.1552
Epoch 54/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3465 - accuracy: 0.6034 - val_loss: 0.5440 - val_accuracy: 0.1724
Epoch 55/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3455 - accuracy: 0.5991 - val_loss: 0.5350 - val_accuracy: 0.1897
Epoch 56/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3554 - accuracy: 0.5819 - val_loss: 0.5317 - val_accuracy: 0.1552
Epoch 57/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3533 - accuracy: 0.5819 - val_loss: 0.5258 - val_accuracy: 0.1724
Epoch 58/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3373 - accuracy: 0.6250 - val_loss: 0.5381 - val_accuracy: 0.2069
Epoch 59/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3604 - accuracy: 0.5776 - val_loss: 0.5237 - val_accuracy: 0.1897
Epoch 60/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3640 - accuracy: 0.5905 - val_loss: 0.5258 - val_accuracy: 0.1897
Epoch 61/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3389 - accuracy: 0.5905 - val_loss: 0.5391 - val_accuracy: 0.1897
Epoch 62/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3343 - accuracy: 0.6250 - val_loss: 0.5446 - val_accuracy: 0.1897
Epoch 63/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3516 - accuracy: 0.6078 - val_loss: 0.5325 - val_accuracy: 0.2069
Epoch 64/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3371 - accuracy: 0.6293 - val_loss: 0.5314 - val_accuracy: 0.1724
Epoch 65/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3492 - accuracy: 0.6250 - val_loss: 0.5292 - val_accuracy: 0.2069
Epoch 66/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3411 - accuracy: 0.6293 - val_loss: 0.5326 - val_accuracy: 0.1724
Epoch 67/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3298 - accuracy: 0.6164 - val_loss: 0.5493 - val_accuracy: 0.1897
Epoch 68/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3375 - accuracy: 0.6250 - val_loss: 0.5384 - val_accuracy: 0.2414
Epoch 69/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3142 - accuracy: 0.7026 - val_loss: 0.5633 - val_accuracy: 0.1897
Epoch 70/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3305 - accuracy: 0.6379 - val_loss: 0.5486 - val_accuracy: 0.2069
Epoch 71/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3442 - accuracy: 0.6034 - val_loss: 0.5388 - val_accuracy: 0.1897
Epoch 72/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3255 - accuracy: 0.6638 - val_loss: 0.5474 - val_accuracy: 0.2069
Epoch 73/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3301 - accuracy: 0.6336 - val_loss: 0.5457 - val_accuracy: 0.1724
Epoch 74/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3475 - accuracy: 0.5905 - val_loss: 0.5392 - val_accuracy: 0.1724
Epoch 75/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3314 - accuracy: 0.6250 - val_loss: 0.5422 - val_accuracy: 0.1897
Epoch 76/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3254 - accuracy: 0.6466 - val_loss: 0.5532 - val_accuracy: 0.1897
Epoch 77/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3394 - accuracy: 0.6250 - val_loss: 0.5386 - val_accuracy: 0.1724
Epoch 78/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2966 - accuracy: 0.7069 - val_loss: 0.5626 - val_accuracy: 0.2069
Epoch 79/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3179 - accuracy: 0.6466 - val_loss: 0.5424 - val_accuracy: 0.1724
Epoch 80/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3140 - accuracy: 0.6336 - val_loss: 0.5592 - val_accuracy: 0.1897
Epoch 81/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3443 - accuracy: 0.6034 - val_loss: 0.5380 - val_accuracy: 0.1897
Epoch 82/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3143 - accuracy: 0.6681 - val_loss: 0.5575 - val_accuracy: 0.2069
Epoch 83/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3271 - accuracy: 0.6466 - val_loss: 0.5512 - val_accuracy: 0.2069
Epoch 84/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3126 - accuracy: 0.6940 - val_loss: 0.5525 - val_accuracy: 0.1724
Epoch 85/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3130 - accuracy: 0.6466 - val_loss: 0.5488 - val_accuracy: 0.1897
Epoch 86/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3110 - accuracy: 0.6552 - val_loss: 0.5575 - val_accuracy: 0.1724
Epoch 87/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3122 - accuracy: 0.6595 - val_loss: 0.5447 - val_accuracy: 0.2241
Epoch 88/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3286 - accuracy: 0.5948 - val_loss: 0.5495 - val_accuracy: 0.1724
Epoch 89/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3218 - accuracy: 0.6293 - val_loss: 0.5771 - val_accuracy: 0.1897
Epoch 90/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3085 - accuracy: 0.6552 - val_loss: 0.5399 - val_accuracy: 0.1897
Epoch 91/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3022 - accuracy: 0.6767 - val_loss: 0.5557 - val_accuracy: 0.1552
Epoch 92/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3083 - accuracy: 0.6336 - val_loss: 0.5496 - val_accuracy: 0.2069
Epoch 93/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3253 - accuracy: 0.6767 - val_loss: 0.5391 - val_accuracy: 0.1724
Epoch 94/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3200 - accuracy: 0.6336 - val_loss: 0.5617 - val_accuracy: 0.1897
Epoch 95/500
8/8 [==============================] - 0s 14ms/step - loss: 0.3054 - accuracy: 0.6638 - val_loss: 0.5581 - val_accuracy: 0.2241
Epoch 96/500
8/8 [==============================] - 0s 9ms/step - loss: 0.3250 - accuracy: 0.6681 - val_loss: 0.5573 - val_accuracy: 0.1724
Epoch 97/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2990 - accuracy: 0.6810 - val_loss: 0.5527 - val_accuracy: 0.1724
Epoch 98/500
8/8 [==============================] - 0s 11ms/step - loss: 0.3112 - accuracy: 0.6595 - val_loss: 0.5489 - val_accuracy: 0.1897
Epoch 99/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2838 - accuracy: 0.6940 - val_loss: 0.5681 - val_accuracy: 0.1897
Epoch 100/500
8/8 [==============================] - 0s 11ms/step - loss: 0.2746 - accuracy: 0.7026 - val_loss: 0.5691 - val_accuracy: 0.1552
Epoch 101/500
8/8 [==============================] - 0s 12ms/step - loss: 0.2853 - accuracy: 0.6897 - val_loss: 0.5598 - val_accuracy: 0.1897
Epoch 102/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2927 - accuracy: 0.6767 - val_loss: 0.5398 - val_accuracy: 0.2241
Epoch 103/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2883 - accuracy: 0.6940 - val_loss: 0.5801 - val_accuracy: 0.1897
Epoch 104/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2833 - accuracy: 0.7069 - val_loss: 0.5668 - val_accuracy: 0.1724
Epoch 105/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2930 - accuracy: 0.6767 - val_loss: 0.5530 - val_accuracy: 0.1724
Epoch 106/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3059 - accuracy: 0.6767 - val_loss: 0.5504 - val_accuracy: 0.1724
Epoch 107/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2825 - accuracy: 0.7026 - val_loss: 0.5655 - val_accuracy: 0.2069
Epoch 108/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2958 - accuracy: 0.7026 - val_loss: 0.5585 - val_accuracy: 0.2069
Epoch 109/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3034 - accuracy: 0.6638 - val_loss: 0.5518 - val_accuracy: 0.2069
Epoch 110/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2929 - accuracy: 0.7112 - val_loss: 0.5680 - val_accuracy: 0.1724
Epoch 111/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2906 - accuracy: 0.7112 - val_loss: 0.5720 - val_accuracy: 0.1724
Epoch 112/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2922 - accuracy: 0.6853 - val_loss: 0.5489 - val_accuracy: 0.1724
Epoch 113/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2728 - accuracy: 0.6940 - val_loss: 0.5622 - val_accuracy: 0.1724
Epoch 114/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3092 - accuracy: 0.6767 - val_loss: 0.5477 - val_accuracy: 0.2069
Epoch 115/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2826 - accuracy: 0.7155 - val_loss: 0.5486 - val_accuracy: 0.1724
Epoch 116/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2904 - accuracy: 0.6983 - val_loss: 0.5749 - val_accuracy: 0.1897
Epoch 117/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2898 - accuracy: 0.6767 - val_loss: 0.5490 - val_accuracy: 0.1897
Epoch 118/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2850 - accuracy: 0.7198 - val_loss: 0.5671 - val_accuracy: 0.1897
Epoch 119/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3062 - accuracy: 0.6940 - val_loss: 0.5726 - val_accuracy: 0.1724
Epoch 120/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2921 - accuracy: 0.7155 - val_loss: 0.5629 - val_accuracy: 0.1724
Epoch 121/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2685 - accuracy: 0.7112 - val_loss: 0.5607 - val_accuracy: 0.1724
Epoch 122/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2655 - accuracy: 0.6853 - val_loss: 0.5753 - val_accuracy: 0.2069
Epoch 123/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2711 - accuracy: 0.7026 - val_loss: 0.5715 - val_accuracy: 0.2069
Epoch 124/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2685 - accuracy: 0.7371 - val_loss: 0.5819 - val_accuracy: 0.2069
Epoch 125/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2983 - accuracy: 0.6681 - val_loss: 0.5657 - val_accuracy: 0.1724
Epoch 126/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2873 - accuracy: 0.6983 - val_loss: 0.5597 - val_accuracy: 0.1724
Epoch 127/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2754 - accuracy: 0.7198 - val_loss: 0.5903 - val_accuracy: 0.1724
Epoch 128/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2648 - accuracy: 0.7457 - val_loss: 0.5859 - val_accuracy: 0.1379
Epoch 129/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2928 - accuracy: 0.6940 - val_loss: 0.5837 - val_accuracy: 0.1552
Epoch 130/500
8/8 [==============================] - 0s 12ms/step - loss: 0.2952 - accuracy: 0.6897 - val_loss: 0.5758 - val_accuracy: 0.1552
Epoch 131/500
8/8 [==============================] - 0s 11ms/step - loss: 0.2703 - accuracy: 0.7328 - val_loss: 0.5967 - val_accuracy: 0.1724
Epoch 132/500
8/8 [==============================] - 0s 10ms/step - loss: 0.3018 - accuracy: 0.6767 - val_loss: 0.5773 - val_accuracy: 0.1552
Epoch 133/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2731 - accuracy: 0.7371 - val_loss: 0.5847 - val_accuracy: 0.1552
Epoch 134/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2620 - accuracy: 0.7586 - val_loss: 0.5781 - val_accuracy: 0.1552
Epoch 135/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2714 - accuracy: 0.7026 - val_loss: 0.5706 - val_accuracy: 0.1724
Epoch 136/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2645 - accuracy: 0.7241 - val_loss: 0.5879 - val_accuracy: 0.1724
Epoch 137/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2954 - accuracy: 0.7198 - val_loss: 0.5766 - val_accuracy: 0.1724
Epoch 138/500
8/8 [==============================] - 0s 11ms/step - loss: 0.2728 - accuracy: 0.7328 - val_loss: 0.6064 - val_accuracy: 0.1552
Epoch 139/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2849 - accuracy: 0.6422 - val_loss: 0.5896 - val_accuracy: 0.1552
Epoch 140/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2647 - accuracy: 0.7026 - val_loss: 0.5752 - val_accuracy: 0.1552
Epoch 141/500
8/8 [==============================] - 0s 10ms/step - loss: 0.2659 - accuracy: 0.7500 - val_loss: 0.5859 - val_accuracy: 0.1552
Epoch 142/500

In [188]:
# Evaluar el modelo
loss_test, accuracy_test = model.evaluate(X_test, y_test)
print(f'Loss: {loss_test}, Accuracy: {accuracy_test}')

2/2 [==============================] - 0s 8ms/step - loss: 0.8620 - accuracy: 0.1212
Loss: 0.8619705438613892, Accuracy: 0.12121212482452393

# All values

In [191]:
tpm_wo_TF = df_tpm[["dataset id"] +genes_in_both]

## Filter wrong datasets

In [192]:
# 10000 is a very high value for TPM, if a put 1000 as threshold almost all the dataset are eliminated. 

threshold = 10000
index_wrong_datasets = tpm_wo_TF[(tpm_wo_TF.drop(columns="dataset id") > threshold).any(axis=1)].index

In [193]:
tpm_wo_TF_curated = tpm_wo_TF.drop(index=index_wrong_datasets)
tpm_wo_TF_curated

,dataset id,thrL,talB,ribF,lspA,carB,caiF,caiT,fixA,yaaU,...,holD,prfC,osmY,deoB,ytjB,serB,slt,trpR,rob,creD
0,GENE_EXPRESSION_ERR1218301,NaN,125.728812,14.672481,8.283922,2.434414,4.007472,0.324927,0.076253,0.232337,...,7.426688,25.759303,762.097680,152.871310,1.965652,6.898852,24.288792,2.492881,92.313130,0.810941
1,GENE_EXPRESSION_ERR1218302,NaN,94.979412,13.584008,4.048387,4.025614,3.316703,0.286131,0.141366,0.076916,...,6.757119,27.780002,434.461472,267.278795,1.442468,4.169862,25.312390,2.143322,96.085111,1.242606
2,GENE_EXPRESSION_ERR1399576,NaN,390.658573,28.281509,21.688995,13.563789,27.467289,1.367853,0.802509,0.698623,...,3.460968,18.613148,2.924724,59.119422,5.729519,8.035470,34.764230,16.327493,82.461126,1.229470
8,GENE_EXPRESSION_ERR1399582,6.636851,464.716255,23.565546,36.076724,13.215864,16.887239,1.968874,0.657782,1.368724,...,3.620969,14.905006,4.153450,80.112855,5.807165,7.287414,37.482123,16.023646,87.637837,2.367772
9,GENE_EXPRESSION_ERR1399583,4.209359,503.412200,25.445917,34.739855,13.788208,20.259933,2.263338,0.763153,0.504917,...,2.896309,15.187347,4.390476,83.451644,8.065745,6.577046,41.260288,12.033436,98.840988,1.219059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,GENE_EXPRESSION_SRR9919243,148.948923,152.714646,24.833296,17.625685,164.517410,2.168428,0.099251,0.151400,0.177423,...,5.056093,36.267601,4.445236,21.141086,3.164742,11.291532,6.295526,7.305722,15.467567,0.788623
1860,GENE_EXPRESSION_SRR9919244,130.236320,128.039858,21.682687,18.566951,91.941032,2.553575,0.199403,0.074188,0.238464,...,4.938713,19.140654,5.177248,24.726398,3.702234,6.706672,6.428653,6.835355,14.472931,0.852143
1861,GENE_EXPRESSION_SRR9919245,77.175933,126.906737,20.455657,18.764994,106.882661,2.136414,0.327560,0.134862,0.170235,...,5.932506,14.954057,5.475841,23.902862,3.092602,5.786205,6.478358,6.709220,15.791694,0.942496
1862,GENE_EXPRESSION_SRR9919246,167.313229,122.605519,23.399676,20.063632,58.707289,1.898784,0.169350,0.162583,0.267347,...,4.986112,21.149352,4.776693,22.016452,3.693050,8.194346,7.250109,6.356556,16.579747,0.773693
1863,GENE_EXPRESSION_SRR9919247,184.258732,120.170441,23.843122,18.557752,63.887982,2.144181,0.219730,0.123956,0.181287,...,4.647282,20.355463,5.798228,21.912910,3.520184,7.736939,7.065605,5.591112,16.101983,0.882420

In [194]:
gene_list = tpm_wo_TF_curated.drop(columns="dataset id").median().index
gene_median = tpm_wo_TF_curated.drop(columns="dataset id").median().values

expression_categorized = pd.DataFrame({"gene":gene_list, "median expression": gene_median})

In [195]:
expression_categorized

      gene  median expression
0     thrL          20.376208
1     talB         132.381025
2     ribF          24.410089
3     lspA          13.209378
4     carB          22.086200
...    ...                ...
1135  serB           7.080661
1136   slt          11.988701
1137  trpR           5.760647
1138   rob          29.567782
1139  creD           1.249324

[1140 rows x 2 columns]

In [196]:
expression_categorized["strength"] = pd.qcut(expression_categorized['median expression'], q=5, labels=False)

In [197]:
expression_categorized

      gene  median expression  strength
0     thrL          20.376208         4
1     talB         132.381025         4
2     ribF          24.410089         4
3     lspA          13.209378         3
4     carB          22.086200         4
...    ...                ...       ...
1135  serB           7.080661         2
1136   slt          11.988701         3
1137  trpR           5.760647         2
1138   rob          29.567782         4
1139  creD           1.249324         0

[1140 rows x 3 columns]

In [198]:
df_for_cnn = expression_categorized.copy()

In [199]:
df_for_cnn = pd.merge(df_for_cnn, df_promoters[["TU first gene", "Promoter sequence", "Sigma factor"]], left_on="gene", right_on="TU first gene")

In [200]:
df_for_cnn.drop(columns="TU first gene", inplace=True)

In [201]:
df_for_cnn.to_csv("dataframes/7_forCNN_test.csv", index=False)

In [202]:
df_for_cnn.head(1)

,gene,median expression,strength,Promoter sequence,Sigma factor
0,thrL,20.376208,4,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70

## Test with Trees

### Libraries

In [203]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [204]:
def sequence_to_onehot(sequence):
    sequence = sequence.upper()
    mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    onehot = np.zeros((len(sequence), len(mapping)))
    for i, nucleotide in enumerate(sequence):
        if nucleotide in mapping:
            onehot[i, mapping[nucleotide]] = 1
    return onehot.flatten()

In [205]:
df_for_cnn["sequence OHE"] = df_for_cnn["Promoter sequence"].apply(sequence_to_onehot)

In [206]:
df_for_cnn

,gene,median expression,strength,Promoter sequence,Sigma factor,sequence OHE
0,thrL,20.376208,4,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
1,talB,132.381025,4,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
2,ribF,24.410089,4,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
3,lspA,13.209378,3,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
4,carB,22.086200,4,agccagccctggtccacacgacgccgcgccgttgttcgaccacttt...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...
1135,serB,7.080661,2,ccctttgaaaatttgagacttaatgttgccagaagcaatggataca...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
1136,slt,11.988701,3,cgtaacgtggcgtaaacggcaatgactggttagcataaatctatta...,sigma32,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
1137,trpR,5.760647,2,gccacggaatggggacgtcgttactgatccgcacgtttatgatatg...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
1138,rob,29.567782,4,atactctactaagaaaaaaacactgaatgctaaaacagcaaaaaat...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
1139,creD,1.249324,0,cttcaccgtcacttcacatagcttcaaattcttcccacatagtctt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."

### X and Y

In [207]:
X = list(df_for_cnn["sequence OHE"])
y = list(df_for_cnn["strength"])

In [208]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

### Models

In [209]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [210]:
KNN_model = KNeighborsClassifier()
Logit_model = LogisticRegression()
DecTree_model = DecisionTreeClassifier()
RF_model = RandomForestClassifier()
GB_model = GradientBoostingClassifier()
XGB_model = XGBClassifier()

In [211]:
list_of_models = [KNN_model, Logit_model, DecTree_model, RF_model, GB_model, XGB_model]

In [212]:
def run_model(model, X_train, y_train):
    L=[]
    model.fit(X_train, y_train)
    y_hat_train = model.predict(X_train)
    y_hat_test = model.predict(X_test)
    accuracy_train = accuracy_score(y_train,y_hat_train)
    accuracy_test = accuracy_score(y_test,y_hat_test)
    L.append(accuracy_train)
    L.append(accuracy_test)
    return L

In [213]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y)

### Results

In [214]:
L=[]
for elem in list_of_models:
    try:
        L.append(run_model(elem, X_train, y_train))
    except:
        None
L

[[0.47173489278752434, 0.22807017543859648],
 [0.5925925925925926, 0.21929824561403508],
 [1.0, 0.22807017543859648],
 [1.0, 0.2894736842105263],
 [0.9961013645224172, 0.18421052631578946],
 [1.0, 0.21929824561403508]]

## Convolutional Neural Network

In [215]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
import tensorflow
import keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [216]:
def one_hot_encode_dna(sequences):
    """
    Codifica una lista de secuencias de ADN en una representación one-hot.

    Parameters:
    sequences (list of str): Lista de secuencias de ADN.

    Returns:
    np.array: Matriz 3D de secuencias codificadas one-hot.
    """
    # Definir el diccionario de codificación one-hot
    mapping = {
        'A': [1, 0, 0, 0],
        'C': [0, 1, 0, 0],
        'G': [0, 0, 1, 0],
        'T': [0, 0, 0, 1],
        'N': [0, 0, 0, 0]  # Para manejar nucleótidos desconocidos
    }
    
    # Obtener la longitud de la secuencia y el número de secuencias
    seq_length = len(sequences[0])
    num_sequences = len(sequences)
    
    # Crear una matriz vacía para almacenar las secuencias codificadas
    one_hot_encoded = np.zeros((num_sequences, seq_length, 4), dtype=np.int8)
    
    # Rellenar la matriz con los valores one-hot
    for i, seq in enumerate(sequences):
        for j, nucleotide in enumerate(seq):
            one_hot_encoded[i, j, :] = mapping.get(nucleotide, [0, 0, 0, 0])
    
    return one_hot_encoded

In [217]:
df_for_cnn["sequence OHE CNN"] = df_for_cnn["Promoter sequence"].apply(lambda x: one_hot_encode_dna(x.upper()))

In [218]:
df_for_cnn

,gene,median expression,strength,Promoter sequence,Sigma factor,sequence OHE,sequence OHE CNN
0,thrL,20.376208,4,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."
1,talB,132.381025,4,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 1, 0, 0]], [[0, 0, 0, 1]..."
2,ribF,24.410089,4,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 0, 1]], [[0, 1, 0, 0]..."
3,lspA,13.209378,3,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 1, 0]], [[0, 0, 1, 0]..."
4,carB,22.086200,4,agccagccctggtccacacgacgccgcgccgttgttcgaccacttt...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[1, 0, 0, 0]], [[0, 0, 1, 0]], [[0, 1, 0, 0]..."
...,...,...,...,...,...,...,...
1135,serB,7.080661,2,ccctttgaaaatttgagacttaatgttgccagaagcaatggataca...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."
1136,slt,11.988701,3,cgtaacgtggcgtaaacggcaatgactggttagcataaatctatta...,sigma32,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 0, 1, 0]], [[0, 0, 0, 1]..."
1137,trpR,5.760647,2,gccacggaatggggacgtcgttactgatccgcacgtttatgatatg...,sigma70,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."
1138,rob,29.567782,4,atactctactaagaaaaaaacactgaatgctaaaacagcaaaaaat...,NaN,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ...","[[[1, 0, 0, 0]], [[0, 0, 0, 1]], [[1, 0, 0, 0]..."
1139,creD,1.249324,0,cttcaccgtcacttcacatagcttcaaattcttcccacatagtctt...,NaN,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 0, 0, 1]], [[0, 0, 0, 1]..."

In [219]:
sequences = list(df_for_cnn["Promoter sequence"].str.upper())

In [220]:
sequences

['GCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAA',
 'CCTGGCGATAACCGTCTTGTCGGCGGTTGCGCTGACGTTGCGTCGTGATATCATCAGGGCAGACCGGTTACATCCCCCTAA',
 'TTCTGATTTCGGTACTCAATCGCCGGTTAACCTTGACCGCTGTACAAGGTATACTCGGACGATTTTCACTGTTTTGAGCCA',
 'TGGGCGATGAATTACGATTTGTCCTGTTGACCTCCGGCGCTACCGTTGCAGACTATAACGACGCACCTGCTGATGCTCAGC',
 'AGCCAGCCCTGGTCCACACGACGCCGCGCCGTTGTTCGACCACTTTATCGAGTTAATTGAGCAGTACCGTAAAACCGCTAA',
 'GATGACATAAGCAGGATTTAGCTCACACTTATCGACGGTGAAGTTGCATACTATCGATATATCCACAATTTTAATATGGCC',
 'CGAAACAAAAATGTGATACCAATCACAGAATACAGCTTATTGAATACCCATTATGAGTTAGCCATTAACGCGTCCACGAGG',
 'TATTGAAAGTTGGATTTATCTGCGTGTGACATTTTCAATATTGGTGATTAAAGTTTTATTTCAAAATTAAAGGGCGTGATA',
 'CACATTGTTGTGAAGGCCGATGCTGATAAACAGGCGCTGGAGCTGCTGGTGAAAGCGTGCCCCGCAGGTCTGTACAAGAAG',
 'TTCCTCAACATCATCCTCGCACCAGTCGACGACGGTTTACGCTTTACGTATAGTGGCGACAATTTTTTTTATCGGGAAATC',
 'AACCTGCCTTATAACATCTCCACGCCGTTGATGTTCCATCTGTTTAGCTATACTGATGCCATTGCCGACATGCACTTTATG',
 'AACGCCGACGCCGTGCTGGCGATGTACCACGATCAGGGTCTTCCCGTGCTAAAATACCAGGGCTTCGGGCGCGGTGTGAAC',
 'GGGCAGTAATGACTGTATAAAACCACAGCCAATCAAACGAAACCAGGCTATACTCAAGCCTGGTTTTTTGATGGATTTTCA',
 'CCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATACCCGTTTTTTTGGATGGAGT',
 'TGACGCCGTGCAAATAATCAATGTGGACTTTTCTGCCGTGATTATAGACACTTTTGTTACGCGTTTTTGTCATGGCTTTGG',
 'GTTTCGTGCCGGTTGTGAAGAAAAAGTGAATGATGTAGCCGTCAAGTTGTCATAATTGGTAACGAATCAGACAATTGACGG',
 'AACTGACGCATGGGGCACCCCCTTGCTTCATCGTTAGGAATTATTGACTTAATATAGGGAAAATAAAATTGCTGTCTTTTG',
 'CGTTGGGCTTTTTTTGCGAAATCAGTGGGAACCTGGAATAAAAGCAGTTGCCGCAGTTAATTTTCTGCGCTTAGATGTTAA',
 'TATGCCTTGTGACTGGCTTGACAAGCTTTTCCTCAGCTCCGTAAACTCCTTTCAGTGGGAAATTGTGGGGCAAAGTGGGAA',
 'AAGAAGTGATGCTGGTTGGACAGTTCAACAAGTTTGAGCTGTGGGATGAAACAACCTGGCATCAACAGGTCAAGGAAGATA',
 'CTGATGAATTGAAGATTCATCTGGTTGAATATGTGCCGATTGCGCGGTGGAATGATCAACATATGGTAGACGCGGAAGGAA',
 'TGCGTTTTCGCTAATAGTTGACAGATTTATCCGCTCCATCGCGGGCGGATAATCTCCCCTTCCCCAACTTTCTTCGTAACG',
 'CCTTATATGTGGTGCTAATACCCGGTTCAGAGTAGCATGTTTCTACCTTATGATTCGTTAGCTATCTGGAGTTTTAACATG',
 'CATGTTAAAACTCCAGATAGCTAACGAATCATAAGGTAGAAACATGCTACTCTGAACCGGGTATTAGCACCACATATAAGG',
 'TTCATGATTTCAATCAAAACCTGTATGGACATAAGGTGAATACTTTGTTACTTTAGCGTCACAGACATGAAATTGGTAAGA',
 'AAAGCGCGGCAACTAAACGTAGAACCTGTCTTATTGAGCTTTCCGGCGAGAGTTCAATGGGACAGGTTCCAGAAAACTCAA',
 'TAGACAAATCGGTTGCCGTTTGTTGTTTAAAAATTGTTAACAATTTTGTAAAATACCGACGGATAGAACGACCCGGTGGTG',
 'TTATTTCTAAACCATCGCCGTTCCGCTGTTTTTCTCCGGTAAGGCTGCGATAATTACATCAATGGCGCAATGCGATTTCGG',
 'ATCATGACTTTTGCATGGGCGACAGATAACGACGCCTTACGCCATCTCTCAACCGAAATTATTCAGGCGCGTTTTCTCGCC',
 'GATACCTTTTTGTAGAAATATTGACCGTGCATCCGCGGTCAATGTTAGCTATTATGTTGCGCCCTTTTTTTACGGGTGTTA',
 'GACACAATTTAATCGACAATAATGGTCGTCGCCTCGCTCGCAGTGTGCTAACGTTTATCTTCTTTAAGCCCCTGGTAGAAG',
 'TCGATTAAATTGTGTCTGCGGCTTGACCTTCCCGTAAGGGGAAGGACTATGCTCAACGTTTGATTTTGTTTCGCCTGCTTA',
 'ACAATTCGAGCTTTATTAACAGATTCCGCGAATGAATAGTTTTACTGGTATACTGCGTGTCTTGCGCTTTGTTGCGGTGCC',
 'TTACGTTCTTACACTTTATCTGTGGTTTAAATCGTCCCGGAGTTGCCCTATATTAGCCAAACGTAATTATTTGGTTACAGG',
 'TGGCAGTGCTGCTACGGATAAATCATTGCCCCCACCAATGTGACTGATAAAATGCCAGACAGCACAACATCAATTTATCAG',
 'ACCCTTTACGCCTCCTCGTTTGCCCGTGGACGCACACGCTACACGCCGCTAAAACGCTGGGCGCTAACGCAATAACAAGGA',
 'TCTTCTTCTGTCTTGTAACAGAAGAACAGAAAATCGGGCTTTTGCGCCTGAATATTGCGGAGAAAAAGCATGGCCGGGAAT',
 'TGCGTACCGCTTGCGAACCCGCCAGCGTTTCGAATATTATCTTATCTTTATAATAATCATTCTCGTTTACGTTATCATTCA',
 'GGCCGCATCAGCCAGCGAGAATACTTGAACGAAATACCAGGGTATTAGATAATGGCGATTATTATTGGGTTAGAATTTGCC',
 'GTGCCATGTCCTCTCCCGCGTGAGAAATACGCTTCCCCGTAAGCGCATGGTAAACTATGCCTTCAAATCGGGCTTATCGCG',
 'TTTACCTTTTGCAGAAACTTTAGTTCGGAACTTCAGGCTATAAAACGAATCTGAAGAACACAGCAATTTTGCGTTATCTGT',
 'CATCATCCTTTAGGCATTTGCACAATGCCGTACGTTACGTACTTCCTTATGCTAAGCCGTGCATAACGGAGGACTTATGGC',
 'TTGCAGCAGGAAGTGCATCAGCGGTTGACAGAGGCCCTCAATCCAAACGATAAAGGGTGATGTGTTTACTGATATGAAAAG',
 'ATAAGATGAAGCCGGCGAATGCCGGCTTTTTTAATGCGATAATTTAATCTTATGGGTGGCGCACAATGAATACCCTTCCAG',
 'ATCTTGTAAATTCAGCTAACCCTTGTGGGGCTGCGCTGAAAAGCGACGTACAATGTCGCTAGTATTAATTCATTTCAATCG',
 'AATAGCCTAATAATCCAGACGATTACCCGTAATATGTTTAATCAGGGCTATACTTAGCACACTTCCACTGTGTGTGACTGT',
 'TTTTTTTGTATAGGCTTCAGTATTCCTGAGTACCGTAAACCCTGTCAGGGAATAAAAAACGCGTGATGTTGTCTGCTACTC',
 'CAGGAATTAAGGACAGCGGTCATTTAATTCCAGGACACGGTGGTATTTTAGATCGTATTGATAGCCTGACGGCTGCGGTAC',
 'CGATGACTTTAGGCGATCAATATAAGATCGCCGGGCCACGCAAAGAACTGCACCCTCCGGTGCAAATGGGATGGTAAGGAG',
 'ACGCCGTTGCTTACAACAGCAGCGATGTAAAAGACATCACTGCCGACGTACTGAAACAGGTTAAATAAGTAATGCCTTCAA',
 'GTGCAGTTGCGGCGCTGATATTGCAGAAATGAGTGTGGTATAGTCACCTTGCGAAACAGAGTTTATCTTCGTAGGCTTAGA',
 'TTCTGCAATATCAGCGCCGCAACTGCACGTATTCCGTTACAATGGCCTCCTGATTCGAAAGGAGTTTTCTTATGGCGCTTA',
 'AACCGCGTTAAATTCACGCCCTTCTCTTTTGACATTTCTTTTGCACTGGTAAACTAAATCACTTTTTTTTGTCCCAGGCTC',
 'AAAGTGCTCTTCGCATAAACCTGATTGATTTAGACGTCTGGATGCCTTAACATCCATTTCATTGACGGCGTTGCCCGTTTC',
 'ATCAATCAGGTTTATGCGAAGAGCACTTTCTTGCAGGTCGAAACATGCGATACTAGCGTCACATGCCTTATTAAGGAGCTA',
 'TTTTTTTCGTCTGTATATCTATTATTGCCAGAATCGCAAAAATCCTCTGCATTTTACGCTCTTTTTCCTCAACAGTCTGAA',
 'GCACTTGCTTACATAACAATATACAATTGCTCGTTGAAAGAGTGAGCTAAAATCCCTATAACAGTAGAACCCTCCCGAGTG',
 'TCGAGAACGATCTGGCGTGTAATTGCAGTGCTCATAGCGGTCATTTATGTCAGACTTGTCGTTTTACAGTTCGATTCAATT',
 'ATTTGTTATCAATTTATTCTGCGCTAAGGCAACTGCCTGATAAGGTGTTAAAGTTATAAAACCCTTCGCATAAAGGAGTTG',
 'GGTGCTATGACCAGGACTTTTTGACCTGAAGTGCGGATAAAAACAGCAACAATGTGAGCTTTGTTGTAATTATATTGTAAA',
 'GTATCCCGGATCGTTTCTGAACAAACTTAATAAACCATTATTATAAAATTAACATATATATTTCAGTTAATTATGTAAAAA',
 'CGCGTTAAATGCTGAATCTTTACGCATTTCTCAAACCCTGAAATCACTGTATACTTTACCAGTGTTGAGAGGTGAGCAATG',
 'TTGCTTGACCCGCAAATGGAAAGACAACTGGTGCTGGGATTATGATGTATACTATTATGTATATTCTGGTGTGCATTATTA',
 'TAAAAAGACGCGGACTCATGTGAAATACTGGTTTTTAGTGCGCCAGATCTCTATAATCTCGCGCAACCTATTTTCCCCTCG',
 'CAACGCCTGGCACTGCCGGGCGTTGTTCTTTTTAACTTCAGGCGGGTTACAATAGTTTCCAGTAAGTATTCTGGAGGCTGC',
 'TTTTAAGAATATTATTAATCTGTAATATATCTTTAACAATCTCAGGTTAAAAACTTTCCTGTTTTCAACGGGACTCTCCCG',
 'CATCCCTGTTACTTCCCTGCCCCTGTCGCCGATGCGACGGGGATCCCTTTTATTTGTTTTCCCGTTATGAGGAGTCTGCTT',
 'TTTGCTAAGAGCTTCATTCATGAATCCTTTTCACTAGGGATGAAGTGGTTTACTGAATTTGGCCACCTGAACAGAGGTGAT',
 'GTAAGAAAGAATTGTGAAATGGGGTTGCAAATGAATAATTACACATATAAAGTGAATTTTAATTCAATAAGTGGCGTTCGC',
 'CAGGCTGGGGCTACCTTCGTCTCAAATTTAGATGTTGGATAGGTATTATATAATGGCATTGTGTACTCTTACTACCTGTAT',
 'GCAACCTAAATCGATTGCCAGAATTGAAAATTGTAGTGTGAAGACAGTGTATACCCATCGGCGTAATGCTGAGGCCAAGCT',
 'GAAAATAATTAAACTTAATCTCGTTTAACCTTTATTGATATGTACTACGTATCTTATTTACTTCCGGTTTACTAAGGAAAC',
 'CCACAAAGAGTCACAGGGATTGAGTGTTGAAATGATCCGGATGAGCATGTATCTTTATGGTTATGTTATAACATAACAGGT',
 'CTATTCAAATTTGTGATACATGTCAAAAAATTGGTTGACCAAACTCGTTATTTATATAAGGGCACTTACGAAGTGCACTCT',
 'TCGTTCCTTGTGGAGCGTTAAGCATCAACAAACGGCTAAGGGCATCCATATCAGACTCCTGAGTGGTTTTTGATTACAAAC',
 'CGTAACAATTAAGACACATTTTATATTGAACGTCCAATCAATAACCGCTTTAATAGATAAACACCGCTGATGAATGGAGTG',
 'TTTATCTATTAAAGCGGTTATTGATTGGACGTTCAATATAAAATGTGTCTTAATTGTTACGAATTTGATTTTAAATAGTAA',
 'CAGACCAACCATGTAGGCTGGACGCCGCTACTGGAAGCGATTGTGCTTAATGATGGTGGTATTAAACAGCAGGCGATTGTG',
 'CACAAAGTGTCTTATTTCCGGTTACTGGCGTTTATGCCCTGACTGAACTAATTATTAATCAACCCAATAATGTGGGTGGGT',
 'TTTCAGGCAATGTTTCACCGCGTTTCATTGCAACAATTATGAAACAAGACTAAACCCAATATTCGGTTTCTTAACTTTGCG',
 'TGAAATTAAACATTTAATTTTATTAAGGCAATTGTGGCACACCCCTTGCTTTGTCTTTATCAACGCAAATAACAAGTTGAT',
 'AAAAATATATTTCCCCACGAAAACGATTGCTTTTTATCTTCAGATGAATAGAATGCGGCGGATTTTTTGGGTTTCAAACAG',
 'AGGCAGACTACTCGCCGATTGTCATAAGGTAAAAGTCTCATTTATGATGAGTTCCATTGGATTTACTTATAGGTTGCGAAT',
 'ATGGAACTCATCATAAATGAGACTTTTACCTTATGACAATCGGCGAGTAGTCTGCCTCTCATTCCAGAGACAGACAGAGGT',
 'CATTTACGTTGACACCATCGAATGGCGCAAAACCTTTCGCGGTATGGCATGATAGCGCCCGGAAGAGAGTCAATTCAGGGT',
 'CCTGGTGCACATTCGGGCATGTTTTGATTGTAGCCGAAAACACCCTTCCTATACTGAGCGCACAATAAAAAATCATTTACA',
 'ACACGACTGCCGGATGCGATAAACGTCTTGTCCGGCCTACATTTCGCCCGTAGGCAGTCATTAAATAGTTCTGATTACGCG',
 'TCATCTGTGCGATAACGACTAATTCTTTTAATGAATGTTTTTATTCCTGAATACTGCTCCCATAACAAGACAGGGGAGCAG',
 'TGTCAACATCGCGACAACTTTCGTAAAACATCCCTACCCTGCTTCAGGTATACTATGCCCCTCGATTCCACAAACATCAGG',
 'TCGAAACAATTCTTATGGTCAGGCTGGCGAACTAAGCGCCTTGCTATGGGTCACAATGGGCGGTTTCATTTGGCTGACGCT',
 'CTGACAGGTCATTTAGATTGTCAATATCAGAATCATGGTAAATTGATGTTGGGAATATTCCCGAAGCGTGAATCTTCGTTG',
 'AAAGTTAATCTTTTCAACAGCTGTCATAAAGTTGTCACGGCCGAGACTTATAGTCGCTTTGTTTTTATTTTTTAATGTATT',
 'CCGGCAGTGAATTTTCGCTGCCGGGTGGTTTTTTTGCTGTTAGCAACCAGACTTAATGGCAGATCACGGGCGCATACGCTC',
 'TACGAAAATGGCTCACCCGAAATATCATACTTCTGCCTTTAGCTCCGTCTCTATAATTTGGGAAAATTGTTTCTGAATGTT',
 'GGTAATCCTCTATTGTGTCGCGCTTTTGCCTTCCGGCATAGTTCTGTTTATGCTTCTGCCAGCGATTATCAAAACAATGAA',
 'TGTCATTTGTAGCACAAGTAAGTGTCAGCAGTGGTGCTTCACACTTGCCCGGTAATTAACGACGAAAGAAAAGTAAGGTGG',
 'GCGGAATTACTGGTGTAATTTTGCGTGACAGCCAGCGCCTCTGGCCCCTATAGTGAAGTAGATGTTCAACTACCAAACAGG',
 'TAGCCCATAATAATATTTCCTTTGCTGCGATTTTTTCAATTTCCGATATATTCATAATTTATCAAGGTTGATATAAATATC',
 'GAATACAGAGGGGCGAATTATCTCTTGGCCTTGCTGGTCGTTATCCTGCAAGCTATCACTTTATTGGCTACGGTGATTGGT',
 'TATTGATTTCCGTGGCGCAGAAAAAAGCAAATGGCACATCTGTTTGGGTATAATCGCGCCCATGCTTTTTCGCCAGGGAAC',
 'TGAAGATATGTGCGACGAGCTTTTCATAAATCTGTCATAAATCTGACGCATAATGACGTCGCATTAATGATCGCAACCTAT',
 'GTCATACTGACTGCATTAACGCGGTAAATCGAAAAACTATTCTTCGCCGCGCCTGGTTGGGAGTATTTCCCGCTAAAATTG',
 'TCCCCCAAATATCCTTCAGATGATGAGTGATCCTGCATTAGGCTATGGCAAGGTGATCAGATTTTCATCACAGGGGAATTA',
 'TATTCTATCCAAAAGGGGGTAAAGGTTGCAGGGAGAGCGCCCCGGCACTAGACTACCCGCCTCTTATTTTAGTCTGAGTCA',
 'GAAGAGAAATATCGCTTTTTTAGTTACGGTGATGCGATGTTTATCACGTACAATCCGCAGGCAATTAATGAGCGCGTCGGG',
 'TACTACCAGCGTTTGATGGCGGGTTTACGCAAGGCTATTGAAGAGGGTAAATTAGAGAGCTTCGTAACTGATTTTTACCAG',
 'CTTTATCTCAAAAGCGTTGCGCCTTTGTTGTATCGTCAGTTCAGGGTAAAATAGATTTCCGTTAACCACCTGGTCAGGACG',
 'CCGCGGATTATGCACGCTGCCAGGGCTTGAGAAATTAGCCGACGCCCCCCAATTTAAATTCAAAGAGATACGTCATGTAGG',
 'CACATCACCTTACCATTGCGCGTTATTTGCTATTTGCCCTGAGTCCGTTACCATGACGGGGCGAAAAATATTGAGAGTCAG',
 'ATAACGCGCAATGGTAAGGTGATGTGCACAGCAAAGCGATGTTAGTGGTATACTTCCGCGCCTGGATGCAGCCGCAGGTGT',
 'AAGGGATACGTCCTGGTGCAGGACTGTCGGTTATTTAACTTTGCGGGTATTATGCTTCGCATCAAAAATGAAGGGAGAGGA',
 'AAATATTTACTAAAAAATCCGCATGTTTACCCCATTCGTTTGCCGCTTTACACTAGTCGCGAATTTAAAACAGAGGTGGTA',
 'TCCAAGTAACAGGAATTTAATCATGTTTACAGTAATGTAACCTTCCCGTAAAATGCCCACACACTTTAAACGCCACCAGAT',
 'CATGATGAATTTACATGCCTTACCCACTTCCCCTCGCCGTTGGCAATGTTATGATGGCGGGAATTTTTACCAAACACGCTT',
 'ATTCTGAAAGTTAAAGGGCGCATGAATGAACTTATGGCGCTTCATACGGGTCAATCATTAGAACAGATTGAACGTGATACC',
 'TAATTTTTCCTCTATTCTCGGCGTTGAATGTGGGGGAAACATCCCCATATACTGACGTACATGTTAATAGATGGCGTGAAG',
 'ACCCTGTAATTAATTTGCATAGTGGCAATTTTTTGCCAGACTGAAGAGGTCATACCAGTTATGACCTCTGTACTTATAACA',
 'TGCCGTGGTGTTTAAACCGCACAGAATAAATTGTCGTGATTTCACCTTTAAAATAAAATTAAAAGAGAAAAAAATTCTCTG',
 'TTAACTTCCTGCTCTCTTTCTCGTTTTTCATTTCTGGCACACCGCTTGCAATACCTTCTTCGTGTAGCAGAACCATTACCG',
 'CCCGTAATTCAGACCATTGCACCCATCGGACCAGTAGCAAATTTGCGTTATACTCAACTCACTTTGGCTTGCTGCGGCAGC',
 'TATGCAAAATTGTGGTAGATCTGTTACTTCCCCTCTACTATTCCCACGTTAAAATAGGGTGTTCCCTGGAAAGTTGCAGAT',
 'ATTGTAATTTTTCGTAATAATGCGATGAAAACCTGCAAAGAGTGGCTTATAGTTAAGCTAACAAACGAGAGGGCAAGTCCA',
 'TCGTGCGCGCACGTCTGGAAGAAGGGCTTAATCCAAACGCTATTTTAGTCCCGCAACAGGGCGTAACCCGTACGCCGCGTG',
 'GTTCGTGAATTTACAGGCGTTAGATTTACATACATTTGTGAATGTATGTACCATAGCACGACGATAATATAAACGCAGCAA',
 'GATTTCAAATTGGTCAATGGTCAAAAGTTAATAAACCCATTGCTGCGTTTATATTATCGTCGTGCTATGGTACATACATTC',
 'TTCCTGGACATTTTCGTCGTTGCTATTCTGGTTCACTGCGTCGTGATATTCTTGCGGTTTGACTTTTTCAGGTCGTTCTTC',
 'AAAGCACTGAAGCACAACAATCGCAGTTGCAATTATTGCGTACAGCCAGTACATTCTGGCGTTTTCGAGCACAGGCGCAGG',
 'ACAGCACAAGATGTGCATTCAGCCTCGCCGTTCTGACGGGGCTGTGTTAGCATTACCCCTTCGTGAATCCACCTTCCAGCG',
 'CGCGACCCGTGGGCGGCACAGGTGAGCCAACTTTCGCTACCAAAACTGGTCGAACAGGTGGCGTTAAATGCCTGGAAAGAG',
 'TTCAGCCCCAGGTGCCTTTCTTGAGGCAATCGCCTGTTGGTGGTATCGTTTATCGCTTTTTCAAAAAATTCGACACATTTT',
 'TGATTTGACCTCTCACAGCAATTAGTTCTTCTTCCTCACTTTTCCGCTACAATTATCAACAAGTTGAATCGATAAGAGGCG',
 'GGTGGTTAACTGAGCGGCGAATGTTAACACAATCTGACGGGAGCGCGCGAGACGCAGCCAGTTTCAATATCAGCAGGCGGG',
 'GTTTGTTTTCCGGCTTCATACAAAAACTCCTTTCAAATTACGTCATTGTAAGGAACCACTGCCATGAAAATGCGATCCCGC',
 'CTGCAAAATTCAATAATTATTCATGAACATCATCAATGAAATTGTCATAAACTATTACCTGTAATTTTGGTTTTCCCGGCC',
 'AAATGGAGTTGGAGACTTGTTTAATGTGTTTGTATGATTCAGTATGTTCTTGCATCGCTATTCACAAGGAAGCAACAGTTA',
 'ACCCGCCTGGTTTATTAATTTCTTGACCTTCCCCTTGCTGGAAGGTTTAACCTTTATCACAGCCAGTCAAAACTGTCTTAA',
 'GGATTAGACATTTATCTCTTTGTTTTCCTGTAGTTAAGTTGCGGGTGCTAAGTTAAATCAGGATGCCTGAAAATCGGCACC',
 'TTTATCCTTCGCAGGAATAAGGGGGAACTCTCTTTCAGTAATCAGGTATAATTTGTTTAATCAAGCAGCAATTTTGCTGAT',
 'TTACTGAAAGAGAGTTCCCCCTTATTCCTGCGAAGGATAAACTGTTTTTAGTAAAAATCAGAAAAAGGGAACAGCGATGCA',
 'CAACCAGACGCAAAGTGATAAACCAGTCGAAAATCCCGGCATCGCCGCCCGCTTTACGTTGGGACCGGAAGCGGTGGTGGA',
 'CAAAGCCGACGTGCTTCGCGCGCAACTTTGCCCGCGCTTCTTCGTCCATATTATGTAGCGGTTGTCCCACCAGACTCACTT',
 'ACATCAATACAAAAGTTGGAATATTTTTCCAAAACTAGATTTAGTCCACAAATTGAACAGGGTTATCATGTAAAAATACTG',
 'TGGAAAAATATTCCAACTTTTGTATTGATGTTGTTCTCTTAAGGTTTTAGATTGCCTGTTATTGAAACCAAGCTGACCGGT',
 'GCGGAGCGGGTTTTTTTGACAAAATTTGAAAGTTGGAAAAATTTTCCAATAAATAGAGGTAGGAATAAAATGGCAAAAATG',
 'GATGCCGACTTCGTCTTCATTCAGCCGAATAGCAGCTATGTTCTTACCAATGACGATCTGGAATATCGCCACAAAGTCAGC',
 'AATAAATTCTAACTATATTTTTTTGCCTGTCTGGATCACATAATCCAGATATTTTCCCTGTATGTTAATTGCAGTCATGCT',
 'GCTGATTTCACAGCCACGCAACCGTTTTCCTTGCTCTCTTTCCGTGCTATTCTCTGTGCCCTCTAAAGCCGAGAGTTGTGC',
 'GATCGGATCATCACGCAATGTATGCTGATTCGCGCGGGAAATATGGGTATTATACGCAACTCAATTACCCACACATGTCTA',
 'TCACGCGATAAATCTGAAACGAAACCTGACAGCGCGCCCCGCTTCTGACAAAATAGGCGCATCCCCTTCGATCTACGTAAC',
 'AACGAGAAACCAAAACTTACATCTTGAAATAATCACATTGATTAGATGAATATTTATCGCGCAGTGACATCATTTTTTAAT',
 'TTAATTTTTTCATCGTGAGCCCTTTTTTTGAACTATTATTAAAAAATGATGTCACTGCGCGATAAATATTCATCTAATCAA',
 'ATATGAAATTTCAACTCATTGTTTAGGGTTTGTTTAATTTTCTACACATACGATTCTGCGAACTTCAAAAAGCATCGGGAA',
 'ATATAAACAGTGGAGCAATATGTAATTGACTCATTAAGTTAGATATAAAAAATACATATTCAATCATTAAAACGATTGAAT',
 'AAAATTGTCATTTTGCCAATAAGCGATTGCCATCTGATCCCGCTACTCTAGAATTGCCCGGGCAACATGCGGAGGAAATAT',
 'TGACAATTTTGTCATTTTTCTGTCACCGGAAAATCAGAGCCTGGCGAGTAAAGTTGGCGGCATAAAATCACCAGAAATTAT',
 'CCCGTTTAACCGTGTGGATTGTGTCTTGCGACGATGGGCACTAAATGTTAAAAGGTGCCCCTCAACAAAAAAGACACACAG',
 'GAAATCTATAGCGCATTTTTCTCGCTTACCATTTCTCGTTGAACCTTGTAATCTGCTGGCACGCAAAATTACTTTCACATG',
 'GAAGGGTAAGATAACGGCGGGTGCCTGAAGCTTTCCGGTTTCAGGTTTACTCTGAGGTCTGGAAAGATGAAGCCCCAGGAG',
 'CCATGTTTACTGTGCAATTTTTCATTGATTGCAGAAATATATTGATAATATTATTGATAACTATTTGCATTTGCAATAGCG',
 'CTTCCCACGGCGCGCCATTACGCTATTGCAAATGCAAATAGTTATCAATAATATTATCAATATATTTCTGCAATCAATGAA',
 'GGTAACGCAATCTGCAACTCGGGGTTGCATCTGGTTGTGGTTACAATGAAAATGAGAAGCATTATTGATGGATTCGCATAA',
 'TTGCAGATTGCGTTACCTCAAGAGTTGACATAGTGCGCGTTTGCTTTTAGGTTAGCGACCGAAAATATAAATGATAATCAT',
 'GACCTCGCCAGCCATATTACCCTACAGGATATTGTGGTCGATGGCGGCTCAACGCTGGGGGCATAAGCATGATCTGGAAAC',
 'ATTTATTGACCGTCTAAATGAGAGTTTTTGATATATAACTACAGACAGCTACTATAACTTTCATCTATTTATTCACAGCGC',
 'AAGTTTTACCTTACAACCTTCGTAAGACAACTTTGTGAACTTTGCACCGCCAGCGGCGATAAAAAGTAAAATGGCCCCCTT',
 'TAGATGTCCTTGATTAACACCAAAATTAAACCTTTTAAAAACCAGGCATTCAAAAACGGCGAATTCATCGAAATCACCGAA',
 'AAACAGTTCGTAAGGAAAAAGAACCAGACAAATATCAGGGATAAATATTATAATCATGGCGAATGATTTGTTCATGATTAA',
 'AATCATCACGCCCGCCAGGTAAGCCCACCTGGCGGGCTTTTTTATGATTTAATAGATAGTATTCAGTGTATGTATGAGTTC',
 'CCAACCGCTAAATATGCGTTTTGTTATCTATGTATAAAAACAGCAACTTCAATGTCTTAATGGCAGTTTTTCTTGATTTTA',
 'ATTATTCTTTATGTTGGGTCTATTAAGGTTATGTTAATTGTAGCTTTGCTATGCTAGTAGTAGATTTTTGATAAATGTTTT',
 'TTACATTTTCGCGACCGCTTTGGCTGCTTTCAGGTCCGTTTCAATGATATACTGCCAGTCGTTAATTCAAAAATAGTTGAT',
 'CACTGGTTTGGTTAAAAATTAAACACTTGAAAGTGTAATTTCCGTCCCCATATACTAAGCATCAGTAAAAAACTCCCGCCT',
 'CGAAAGCCGATTCGGCGACAATTGTCCCGAAATCGCCTCTGGTTCAGGTATACTGACAGACCATTTTTATCTATTTGATTC',
 'TTACAGAGTTTGTGGGCGTATTAGCAAAGCAAGGAACAAAGAACGTCTATTATTATAGTCAGTTAACGACCCGGGAGATGA',
 'AATAGGCTGATTCAAGGCATTTACGGGAGAAAAAATCGGCTCAAACATGAAGAAATGAAATGACTGAGTCAGCCGAGAAGA',
 'TCTCAGGCCTGCCGTTCCGGTGGGCCTTGTTTTTTCTCTCTTTATCCCCATCTTTATTGCAATGCTTGCGCCTTTTTCCTG',
 'TTTATTTTTTCACCGCCAAATCGCTTGCGCACAGTGCTGCTTTGCGGCATTTTTTTAAACAAGCAAACACAACAAGCAACA',
 'CTCAACGGTATTTTGCTCCAGCATTTGCTGGAAAATTAATGTGCTTTTATAGTGGCGCTTATTGTTGTCAATATTCTGGGT',
 'GTTCTTACGGAAAAATTCATCTGTTTATGGGCGGTGTAGGTAACGACGGTCATATTGCATTTAACGAACCGGCGTCTTCTC',
 'ATATCGTTATTATCACTCCCTTTTACTGGCTAAACCAGAAAACTTATTTTATCATTCAAAAAATCAGGTCGGATTGACGCC',
 'ACTCACAAAAGACACGCGTTTAATTTGCGATACGAATTAAATTTTCACACACTCTGTAGCAGATGATCTAACAATCTGATT',
 'GCCAATCAAAATAATTGCTACAAATTTGTAACTTTTGCTGTTGTACCTGTACAATGTCCCGGTGTTCAAGTGGCCTTGCCG',
 'TGTGCAGTCCTGCTCGTTTGCTGATTCCGCAAGACTGCCTGTTCTGCTATGATTGCCTTTATCCGTGGGCAATTTTCCACC',
 'GCGCGTGGGCGTTGGCGTGACTCATCGCGCTGATGTATTATGGCGCGCTATCCATCCGGGCAGAGGCCTGGCTGATTGTTT',
 'TATTCCGAGTTTTTCTGCAAGCCAGGCTTGACGCTATCCGCTGCCGGGATTTATTCATATACTCCTGGCGACTTGTATTCA',
 'ATAAAGTCATTTTTTATTCAAATATAAGGAACTTAATATTTAAAAAATGTTCCATACAATTCCTCATCATAAATGACACCG',
 'TTTACACCCCGCCCGCAGATTTTTGCGAAATCTTTGCAGCCAGAATTCTACCCTTCCGGTATCACTTTTAGGCCACTGGAG',
 'AGTTATCGCCGTGGCGAGCAACCACTTCTTGCGCCGCTGATGCGTATCAAACACTATATGGCGCTTTATCCTGACGCCTGG',
 'TCGCCCGCCGACTACGCTCTGCATTTGCCGAAAAGGGGATTGTTGTCGCAGCATAACCCCGATTAATAAAGAATGAAAAAA',
 'CGACAAACTATATGTAGGTTAATTGTAATGATTTTGTGAACAGCCTATACTGCCGCCAGGTCTCCGGAACACCCTGCAATC',
 'AGGTTTCGAGCAAGCTTCCGCGATTATGGGCAGCTTCTTCGTCAAATTTATCATGTGGGGCATCCTTACCGCTCTGGCGTA',
 'CGTAACAAAGAAATGCAGGAAATCTTTAAAAACTGCCCCTGACACTAAGACAGTTTTTAAAGGTTCCTTCGCGAGCCACTA',
 'CATTATGTGATCAATTTCACTTGATTGAAATTATTTGTATTGTATTTGTATTATTTACAGGATGAATTTATCGGGCATAAT',
 'CTGACGCCAAACTCTGTTTGTAGCGCTGATTCAGTGGGTAACGCATCGCCAGGTTTAAGCTCGCCACGCGCAATTTGTTCA',
 'GCATATAAAACAAATTACACCGATAACAGCGAATATTACGCTAATGTCGGTTTTAACGTTAAGCCTGTAAAACGAGATGGT',
 'TAATCCGTTCATAGTGTAAAACCCCGTTTACACATTCTGACGGAAGATATAGATTGGAAGTATTGCATTCACTAAGATAAG',
 'TTGGGCAAATAGCTTCCTGCCTAACGAAGCTGAGCGCGAAGACCGCCTGCAAAAAGAATATTTTGCCGAACAGAAATCACC',
 'CGCAAAGCTGACCGCACAAAAGGGGAGTGCTTTTCTGTGCTTAGCGGTTAGAATAGTCTCATGACTATATCTGGAGTTGAC',
 'AACAACTTTTTGTCTTTTTACCTTCCCGTTTCGCTCAAGTTAGTATAAAAAAGCAGGCTTCAACGGATTCATTTTTCTATT',
 'GTGAGCCATGGGGCTTCTCCAAAACGTGTTTTTTGTTGTTAATTCGGTGTAGACTTGTAAACCTAAATCTTTTCAATTTGG',
 'GATCGTCCGTTGTCATAATCGACTTGTAAACCAAATTGAAAAGATTTAGGTTTACAAGTCTACACCGAATTAACAACAAAA',
 'CAGCAACAGGCGCTGGAAGCGCGTATTTCAGCGGCGCTGCGGGAGAAGAAACAGACCCATTTCCTGCATCAAAACAACACC',
 'AGTACATACGTTTACGCTGCGTCGATGCACAGCCTCATCATTTTGCAGTATCCTTAAGATATTCCTTATATCTTCAGGAGA',
 'CGGCGTCACAAAAAGGTGCGGTCTTACGGAATTTTCCGTAAAGTTCGGTACTCTGAGTAAGTAGAGATAAATTCTTCAGGA',
 'CGTTGCTAAAATTCTTAGCCATACTGGACAACTCCCCTATGGAGTCATAATCTTAATCAATCATTTGATTAAGAATGGACT',
 'CTGAAAACCGAAAAATGCCACAATATTGGCTGTTTATACAGTATTTCAGGTTTTCTCATGGCATTAACCGCCGCGCTTAAA',
 'TGGTCGGAGATCTGATGCTTGAACTGCCCGAGTTCGTCCCTGGATTAGCTACACTTAACTGTACAAGTATTGATATGGGGA',
 'AAATGTATTTCTTTTTCGCGCAATGGGTGATAGAAAATCGCTCCAAGTGATAATGCTTATCAAAATTATTATCACTTTCAC',
 'AAAAATCAGCATTATGCATGTCATTGATTTGTCTTATTTTGTAAAAATATATCGTTCAAAAAATAAGCACATCTCTGTCAA',
 'ACTGCGTCGTATGCTGCCGCCGCTGGGTAACCAGTGGATCATCAGCATTAAAGACACCTCGCTGTTTATTGTGATCGGCGT',
 'ATTAGTGTGATAGGAACAGCCAGAATAGCGGAACACATAGCCGGTGCTATACTTAATCTCGTTAATTACTGGGACATAACA',
 'ATACCCAATGCTGGTTGAGCATTTGTTGAAAAAATTTTCCCCCGTTTTGACTAAAATGCGCCAGGATTGATGGAATCATTA',
 'CCCGTTAGACATCACAAATCGCGAAGAGTTTCCCATTAATTTTTGATATATTTAAAACTTAGGACTTATTTGAATCACATT',
 'TGATTGCATTACATACAGATATAGCACAGGCTATATTATATAGCTATTGCTAAAACGTTAATTTTTTGTACCTTCGCAACT',
 'ACACATCTGATTTCACTGTGAGCTGGAATGAACTTATAATGCGCTTCCAATACTCTAATATTCTCAACCCAATGGCCTGCC',
 'TAAGCGAGGAGCAGGATCTTCTTTCAGACTTATGGCATAATGCGCGGTTTGTCATATCTCTTTTCAGGATACGCCTGTGTT',
 'ACCCAGCGCTACGCCCGAGGTGGCATACAGTCTGTGGCGTTTTTCTGACATAATAGGCAAATTCGATTTTGCCTCCGCAGG',
 'ATCTTTCTATATTCAAAAATTGAATGAGTAATTCATAAAAATTCTGATATTTATAGCAAAAGTGGCGAACCACCCTTAATG',
 'CCTCCGCCAGCGAATGAGATTGCGATACAAATTTTATCCAGAACTCTGTAGAATCCCTGCCCTGACCTTTCCTGTAACTGA',
 'CTGGTGTCATTTTTTTGCCAGCTGTTGCTTAAAAGTTAACTTTACTTCACCATCGGAGTCCTGTTCAGCCTGTGGCTGCCT',
 'GCAGGATATTGCATAAACTTTAAAAACTTTACCAACTTACGGTTTCTTTAAGTTTGTGTGTGCGTTATTAATCACCAAACT',
 'TTACGAGTATAGCTACGCTTTCTTTAAGTTTTATTTAACCTATGCCCGTTACAATCACCCACCGTAAACAGGCCGCTTGAG',
 'ATTAATGCAACAGGTTAAACCTACTTTCAGCGAATACATTTTAGCGTGATCATTACAGGCATAAATCTATGAGGAGAGAAA',
 'TTAATTGCTAAAAGCTATAACTGTTAAACACAATACAGTGAAAAGTTTTAGACTGAAGGCTCACTTTGCAGAGGGAAGCGT',
 'CTGGAGCGATCATATCCGCCGAACAATCATTAAAGAAAGCCGCCCATTTATTCTGGATTATTTGCACAAACAGGGTTGGGC',
 'CATTTAAATTATTTAATCATGTTTATTGCATATAAATTCACTTGATGGCATTGTTATCCCATGCCGCAGACACGGCCAAAA',
 'CCTTGTTTGCTAAGCCTTCGATCTCAAAAGCATTATCAGACTGATACGCTATTATTGAAAGGATATCATTATTATCGTAGA',
 'CTGTAGCGCATAATGATTTCCTTATAAGCGATCGCTCTGAAAGCGTTCTACGATAATAATGATATCCTTTCAATAATAGCG',
 'GACGCGGTGATGAAGTGATCGAACTGGCGAAAACAAACTGGCTAAGGTAAAAAGGGTGGCATTTCCCGTCATAATAAGGAC',
 'TTAGTGCCTCCTTTCTCTCCCATCCCTTCCCCCTCCGTCAGATGAACTAAACTTGTTACCGTTATCACATTCAGGAGATGG',
 'CATAACATTTCCTTTTAATTGCAACTTTACTCGTCCTTCCGCTTTCAGTAGTGTGTCATCGCGCATTTCGACTTCATCTTT',
 'TTACGTTAGTAATCACACTATTGATGTTTGGTTAAGATACGCAATGGTGAAATCGACGCCATGTATAACCATTGATTTCAT',

In [221]:
encoded_sequences = one_hot_encode_dna(sequences)

In [222]:
labels = df_for_cnn["strength"]

In [223]:
labels = np.array(labels).astype(np.float32).reshape(-1, 1)

In [224]:
labels.shape

(1140, 1)

In [225]:
labelencoder = LabelEncoder()

In [226]:
labels = labelencoder.fit_transform(labels)

c:\Users\Sergio\miniconda3\envs\python3_10_9\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [227]:
labels

array([4, 4, 4, ..., 2, 4, 0], dtype=int64)

In [228]:
labels = to_categorical(labels)

In [229]:
labels

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [230]:
labels.shape

(1140, 5)

In [231]:
encoded_sequences.shape[1]

81

In [232]:
encoded_sequences.shape[2]

4

In [233]:
X_train, X_test, y_train, y_test = train_test_split(encoded_sequences, labels, test_size=0.1, stratify=labels)

In [234]:
encoded_sequences.shape[0]

1140

In [235]:
encoded_sequences.shape[1]

81

In [236]:
encoded_sequences.shape[2]

4

In [237]:
model = Sequential([
    Conv1D(filters=16, kernel_size=7, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    Conv1D(filters=16, kernel_size=6, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    Conv1D(filters=16, kernel_size=5, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    MaxPooling1D(pool_size=4),
    Dropout(0.8),
    Flatten(),
    Dense(16, activation='relu'),
    Dense(5, activation='softmax')  # Salida única para clasificación binaria
])

# Compilar el modelo
model.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])

In [238]:
# Entrenar el modelo
model.fit(X_train, y_train, epochs=500, batch_size=32, validation_split=0.2)

Epoch 1/500
26/26 [==============================] - 1s 15ms/step - loss: 0.5854 - accuracy: 0.1902 - val_loss: 0.5139 - val_accuracy: 0.1990
Epoch 2/500
26/26 [==============================] - 0s 8ms/step - loss: 0.5258 - accuracy: 0.2024 - val_loss: 0.5095 - val_accuracy: 0.1845
Epoch 3/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5171 - accuracy: 0.2049 - val_loss: 0.5068 - val_accuracy: 0.1748
Epoch 4/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5125 - accuracy: 0.2049 - val_loss: 0.5058 - val_accuracy: 0.1553
Epoch 5/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5103 - accuracy: 0.2171 - val_loss: 0.5045 - val_accuracy: 0.1602
Epoch 6/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5107 - accuracy: 0.1854 - val_loss: 0.5046 - val_accuracy: 0.1650
Epoch 7/500
26/26 [==============================] - 0s 8ms/step - loss: 0.5076 - accuracy: 0.2024 - val_loss: 0.5030 - val_accuracy: 0.1796
Epoch 8/500
26/26 [==============================] - 0s 6ms/step - loss: 0.5046 - accuracy: 0.2317 - val_loss: 0.5024 - val_accuracy: 0.1602
Epoch 9/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5021 - accuracy: 0.2195 - val_loss: 0.5022 - val_accuracy: 0.1699
Epoch 10/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5052 - accuracy: 0.2268 - val_loss: 0.5016 - val_accuracy: 0.1893
Epoch 11/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5032 - accuracy: 0.2195 - val_loss: 0.5025 - val_accuracy: 0.1602
Epoch 12/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5036 - accuracy: 0.2341 - val_loss: 0.5030 - val_accuracy: 0.1602
Epoch 13/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5016 - accuracy: 0.2451 - val_loss: 0.5036 - val_accuracy: 0.1602
Epoch 14/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5012 - accuracy: 0.2500 - val_loss: 0.5036 - val_accuracy: 0.1602
Epoch 15/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5015 - accuracy: 0.2195 - val_loss: 0.5033 - val_accuracy: 0.1796
Epoch 16/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5017 - accuracy: 0.2317 - val_loss: 0.5023 - val_accuracy: 0.1748
Epoch 17/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5013 - accuracy: 0.2134 - val_loss: 0.5020 - val_accuracy: 0.1602
Epoch 18/500
26/26 [==============================] - 0s 7ms/step - loss: 0.5018 - accuracy: 0.2402 - val_loss: 0.5022 - val_accuracy: 0.1650
Epoch 19/500
26/26 [==============================] - 0s 8ms/step - loss: 0.5005 - accuracy: 0.2488 - val_loss: 0.5021 - val_accuracy: 0.1845
Epoch 20/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4995 - accuracy: 0.2317 - val_loss: 0.5030 - val_accuracy: 0.1748
Epoch 21/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4973 - accuracy: 0.2671 - val_loss: 0.5022 - val_accuracy: 0.1748
Epoch 22/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4957 - accuracy: 0.2793 - val_loss: 0.5014 - val_accuracy: 0.1942
Epoch 23/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4970 - accuracy: 0.2561 - val_loss: 0.5013 - val_accuracy: 0.2184
Epoch 24/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4969 - accuracy: 0.2561 - val_loss: 0.5021 - val_accuracy: 0.1942
Epoch 25/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4964 - accuracy: 0.2646 - val_loss: 0.5019 - val_accuracy: 0.2136
Epoch 26/500
26/26 [==============================] - 0s 9ms/step - loss: 0.4941 - accuracy: 0.2841 - val_loss: 0.5017 - val_accuracy: 0.2039
Epoch 27/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4937 - accuracy: 0.2805 - val_loss: 0.5027 - val_accuracy: 0.1990
Epoch 28/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4955 - accuracy: 0.2573 - val_loss: 0.5025 - val_accuracy: 0.1990
Epoch 29/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4928 - accuracy: 0.2963 - val_loss: 0.5021 - val_accuracy: 0.1990
Epoch 30/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4949 - accuracy: 0.2622 - val_loss: 0.5022 - val_accuracy: 0.1845
Epoch 31/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4949 - accuracy: 0.2573 - val_loss: 0.5030 - val_accuracy: 0.1893
Epoch 32/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4912 - accuracy: 0.3012 - val_loss: 0.5031 - val_accuracy: 0.1990
Epoch 33/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4869 - accuracy: 0.3049 - val_loss: 0.5030 - val_accuracy: 0.1942
Epoch 34/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4896 - accuracy: 0.3146 - val_loss: 0.5012 - val_accuracy: 0.1893
Epoch 35/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4899 - accuracy: 0.3244 - val_loss: 0.5014 - val_accuracy: 0.2136
Epoch 36/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4875 - accuracy: 0.3085 - val_loss: 0.5017 - val_accuracy: 0.1893
Epoch 37/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4866 - accuracy: 0.3207 - val_loss: 0.5016 - val_accuracy: 0.1942
Epoch 38/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4864 - accuracy: 0.3024 - val_loss: 0.5015 - val_accuracy: 0.2087
Epoch 39/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4836 - accuracy: 0.3110 - val_loss: 0.5027 - val_accuracy: 0.2136
Epoch 40/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4862 - accuracy: 0.3171 - val_loss: 0.5040 - val_accuracy: 0.1893
Epoch 41/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4838 - accuracy: 0.3098 - val_loss: 0.5022 - val_accuracy: 0.2282
Epoch 42/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4821 - accuracy: 0.3305 - val_loss: 0.5029 - val_accuracy: 0.1942
Epoch 43/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4826 - accuracy: 0.3171 - val_loss: 0.5020 - val_accuracy: 0.2233
Epoch 44/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4762 - accuracy: 0.3476 - val_loss: 0.5022 - val_accuracy: 0.2282
Epoch 45/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4814 - accuracy: 0.2988 - val_loss: 0.5019 - val_accuracy: 0.2282
Epoch 46/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4805 - accuracy: 0.3341 - val_loss: 0.5017 - val_accuracy: 0.2087
Epoch 47/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4797 - accuracy: 0.3390 - val_loss: 0.5033 - val_accuracy: 0.2282
Epoch 48/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4810 - accuracy: 0.3317 - val_loss: 0.5014 - val_accuracy: 0.2136
Epoch 49/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4790 - accuracy: 0.3220 - val_loss: 0.5003 - val_accuracy: 0.1893
Epoch 50/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4780 - accuracy: 0.3329 - val_loss: 0.5016 - val_accuracy: 0.2136
Epoch 51/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4742 - accuracy: 0.3354 - val_loss: 0.5003 - val_accuracy: 0.2184
Epoch 52/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4749 - accuracy: 0.3232 - val_loss: 0.5021 - val_accuracy: 0.2233
Epoch 53/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4664 - accuracy: 0.3744 - val_loss: 0.5013 - val_accuracy: 0.1845
Epoch 54/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4765 - accuracy: 0.3415 - val_loss: 0.5013 - val_accuracy: 0.2039
Epoch 55/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4664 - accuracy: 0.3902 - val_loss: 0.5043 - val_accuracy: 0.1796
Epoch 56/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4613 - accuracy: 0.3744 - val_loss: 0.5031 - val_accuracy: 0.2184
Epoch 57/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4719 - accuracy: 0.3463 - val_loss: 0.5067 - val_accuracy: 0.1893
Epoch 58/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4735 - accuracy: 0.3366 - val_loss: 0.5021 - val_accuracy: 0.2330
Epoch 59/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4701 - accuracy: 0.3646 - val_loss: 0.5038 - val_accuracy: 0.1845
Epoch 60/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4594 - accuracy: 0.3976 - val_loss: 0.5035 - val_accuracy: 0.1845
Epoch 61/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4573 - accuracy: 0.4000 - val_loss: 0.5036 - val_accuracy: 0.1845
Epoch 62/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4682 - accuracy: 0.3610 - val_loss: 0.5026 - val_accuracy: 0.2039
Epoch 63/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4592 - accuracy: 0.3927 - val_loss: 0.5071 - val_accuracy: 0.1942
Epoch 64/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4602 - accuracy: 0.3902 - val_loss: 0.5060 - val_accuracy: 0.1990
Epoch 65/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4563 - accuracy: 0.4012 - val_loss: 0.5044 - val_accuracy: 0.2233
Epoch 66/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4569 - accuracy: 0.4012 - val_loss: 0.5064 - val_accuracy: 0.2039
Epoch 67/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4532 - accuracy: 0.3951 - val_loss: 0.5057 - val_accuracy: 0.2330
Epoch 68/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4593 - accuracy: 0.3890 - val_loss: 0.5057 - val_accuracy: 0.2184
Epoch 69/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4509 - accuracy: 0.3976 - val_loss: 0.5076 - val_accuracy: 0.2282
Epoch 70/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4562 - accuracy: 0.3963 - val_loss: 0.5062 - val_accuracy: 0.2039
Epoch 71/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4539 - accuracy: 0.3988 - val_loss: 0.5065 - val_accuracy: 0.2184
Epoch 72/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4478 - accuracy: 0.4049 - val_loss: 0.5070 - val_accuracy: 0.2184
Epoch 73/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4503 - accuracy: 0.3915 - val_loss: 0.5096 - val_accuracy: 0.1942
Epoch 74/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4537 - accuracy: 0.3988 - val_loss: 0.5085 - val_accuracy: 0.1990
Epoch 75/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4529 - accuracy: 0.4134 - val_loss: 0.5112 - val_accuracy: 0.2184
Epoch 76/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4445 - accuracy: 0.4183 - val_loss: 0.5093 - val_accuracy: 0.2087
Epoch 77/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4452 - accuracy: 0.4146 - val_loss: 0.5082 - val_accuracy: 0.2233
Epoch 78/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4475 - accuracy: 0.4098 - val_loss: 0.5101 - val_accuracy: 0.1845
Epoch 79/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4423 - accuracy: 0.4390 - val_loss: 0.5094 - val_accuracy: 0.2087
Epoch 80/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4432 - accuracy: 0.4159 - val_loss: 0.5107 - val_accuracy: 0.2136
Epoch 81/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4454 - accuracy: 0.4207 - val_loss: 0.5068 - val_accuracy: 0.2087
Epoch 82/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4449 - accuracy: 0.4244 - val_loss: 0.5076 - val_accuracy: 0.2379
Epoch 83/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4438 - accuracy: 0.4354 - val_loss: 0.5089 - val_accuracy: 0.2282
Epoch 84/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4439 - accuracy: 0.4085 - val_loss: 0.5082 - val_accuracy: 0.2330
Epoch 85/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4435 - accuracy: 0.4317 - val_loss: 0.5080 - val_accuracy: 0.2039
Epoch 86/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4423 - accuracy: 0.4183 - val_loss: 0.5084 - val_accuracy: 0.2136
Epoch 87/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4370 - accuracy: 0.4390 - val_loss: 0.5112 - val_accuracy: 0.2233
Epoch 88/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4420 - accuracy: 0.4366 - val_loss: 0.5116 - val_accuracy: 0.2330
Epoch 89/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4288 - accuracy: 0.4646 - val_loss: 0.5143 - val_accuracy: 0.2379
Epoch 90/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4397 - accuracy: 0.4232 - val_loss: 0.5124 - val_accuracy: 0.2330
Epoch 91/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4352 - accuracy: 0.4329 - val_loss: 0.5134 - val_accuracy: 0.2233
Epoch 92/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4374 - accuracy: 0.4293 - val_loss: 0.5117 - val_accuracy: 0.2427
Epoch 93/500
26/26 [==============================] - 0s 12ms/step - loss: 0.4365 - accuracy: 0.4220 - val_loss: 0.5082 - val_accuracy: 0.2136
Epoch 94/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4332 - accuracy: 0.4402 - val_loss: 0.5122 - val_accuracy: 0.2330
Epoch 95/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4392 - accuracy: 0.4195 - val_loss: 0.5088 - val_accuracy: 0.2233
Epoch 96/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4279 - accuracy: 0.4488 - val_loss: 0.5128 - val_accuracy: 0.2330
Epoch 97/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4317 - accuracy: 0.4573 - val_loss: 0.5093 - val_accuracy: 0.2233
Epoch 98/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4330 - accuracy: 0.4341 - val_loss: 0.5089 - val_accuracy: 0.2233
Epoch 99/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4252 - accuracy: 0.4683 - val_loss: 0.5117 - val_accuracy: 0.2233
Epoch 100/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4306 - accuracy: 0.4659 - val_loss: 0.5153 - val_accuracy: 0.2233
Epoch 101/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4254 - accuracy: 0.4646 - val_loss: 0.5154 - val_accuracy: 0.2233
Epoch 102/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4273 - accuracy: 0.4585 - val_loss: 0.5163 - val_accuracy: 0.2087
Epoch 103/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4348 - accuracy: 0.4439 - val_loss: 0.5137 - val_accuracy: 0.2136
Epoch 104/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4264 - accuracy: 0.4561 - val_loss: 0.5116 - val_accuracy: 0.2330
Epoch 105/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4252 - accuracy: 0.4671 - val_loss: 0.5149 - val_accuracy: 0.2379
Epoch 106/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4260 - accuracy: 0.4280 - val_loss: 0.5125 - val_accuracy: 0.2233
Epoch 107/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4238 - accuracy: 0.4768 - val_loss: 0.5184 - val_accuracy: 0.2282
Epoch 108/500
26/26 [==============================] - 0s 6ms/step - loss: 0.4157 - accuracy: 0.4805 - val_loss: 0.5198 - val_accuracy: 0.2184
Epoch 109/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4198 - accuracy: 0.4793 - val_loss: 0.5214 - val_accuracy: 0.2184
Epoch 110/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4161 - accuracy: 0.4707 - val_loss: 0.5187 - val_accuracy: 0.2039
Epoch 111/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4261 - accuracy: 0.4366 - val_loss: 0.5162 - val_accuracy: 0.2184
Epoch 112/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4255 - accuracy: 0.4646 - val_loss: 0.5149 - val_accuracy: 0.2039
Epoch 113/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4162 - accuracy: 0.4878 - val_loss: 0.5204 - val_accuracy: 0.2136
Epoch 114/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4111 - accuracy: 0.4939 - val_loss: 0.5212 - val_accuracy: 0.1990
Epoch 115/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4177 - accuracy: 0.4927 - val_loss: 0.5190 - val_accuracy: 0.2039
Epoch 116/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4109 - accuracy: 0.4829 - val_loss: 0.5204 - val_accuracy: 0.2039
Epoch 117/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4073 - accuracy: 0.4841 - val_loss: 0.5199 - val_accuracy: 0.1893
Epoch 118/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4135 - accuracy: 0.4927 - val_loss: 0.5197 - val_accuracy: 0.2039
Epoch 119/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4218 - accuracy: 0.4695 - val_loss: 0.5186 - val_accuracy: 0.2233
Epoch 120/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4032 - accuracy: 0.4805 - val_loss: 0.5222 - val_accuracy: 0.2136
Epoch 121/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4063 - accuracy: 0.4976 - val_loss: 0.5208 - val_accuracy: 0.2233
Epoch 122/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4197 - accuracy: 0.4671 - val_loss: 0.5199 - val_accuracy: 0.2087
Epoch 123/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4230 - accuracy: 0.4622 - val_loss: 0.5180 - val_accuracy: 0.2282
Epoch 124/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4088 - accuracy: 0.5098 - val_loss: 0.5257 - val_accuracy: 0.2184
Epoch 125/500
26/26 [==============================] - 0s 8ms/step - loss: 0.4120 - accuracy: 0.4683 - val_loss: 0.5176 - val_accuracy: 0.2330
Epoch 126/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4147 - accuracy: 0.4744 - val_loss: 0.5197 - val_accuracy: 0.2330
Epoch 127/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4147 - accuracy: 0.4720 - val_loss: 0.5215 - val_accuracy: 0.2330
Epoch 128/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4057 - accuracy: 0.4841 - val_loss: 0.5170 - val_accuracy: 0.2379
Epoch 129/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4120 - accuracy: 0.4841 - val_loss: 0.5186 - val_accuracy: 0.2233
Epoch 130/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4157 - accuracy: 0.4780 - val_loss: 0.5246 - val_accuracy: 0.2136
Epoch 131/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4143 - accuracy: 0.4646 - val_loss: 0.5170 - val_accuracy: 0.2330
Epoch 132/500
26/26 [==============================] - 0s 7ms/step - loss: 0.3953 - accuracy: 0.5024 - val_loss: 0.5243 - val_accuracy: 0.2087
Epoch 133/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4083 - accuracy: 0.4866 - val_loss: 0.5187 - val_accuracy: 0.2233
Epoch 134/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4021 - accuracy: 0.4854 - val_loss: 0.5210 - val_accuracy: 0.2524
Epoch 135/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4016 - accuracy: 0.5037 - val_loss: 0.5239 - val_accuracy: 0.2233
Epoch 136/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4049 - accuracy: 0.4878 - val_loss: 0.5207 - val_accuracy: 0.2184
Epoch 137/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4074 - accuracy: 0.5012 - val_loss: 0.5225 - val_accuracy: 0.2136
Epoch 138/500
26/26 [==============================] - 0s 7ms/step - loss: 0.3982 - accuracy: 0.5085 - val_loss: 0.5212 - val_accuracy: 0.2427
Epoch 139/500
26/26 [==============================] - 0s 7ms/step - loss: 0.3959 - accuracy: 0.5293 - val_loss: 0.5240 - val_accuracy: 0.2233
Epoch 140/500
26/26 [==============================] - 0s 7ms/step - loss: 0.4043 - accuracy: 0.4976 - val_loss: 0.5184 - val_accuracy: 0.2379
Epoch 141/500

In [239]:
# Evaluar el modelo
loss_test, accuracy_test = model.evaluate(X_test, y_test)
print(f'Loss: {loss_test}, Accuracy: {accuracy_test}')

4/4 [==============================] - 0s 4ms/step - loss: 0.6317 - accuracy: 0.1579
Loss: 0.6316535472869873, Accuracy: 0.15789473056793213

# sigma70

In [253]:
tpm_wo_TF = df_tpm[["dataset id"] +genes_in_both]

## Filter wrong datasets

In [254]:
# 10000 is a very high value for TPM, if a put 1000 as threshold almost all the dataset are eliminated. 

threshold = 10000
index_wrong_datasets = tpm_wo_TF[(tpm_wo_TF.drop(columns="dataset id") > threshold).any(axis=1)].index

In [255]:
tpm_wo_TF_curated = tpm_wo_TF.drop(index=index_wrong_datasets)
tpm_wo_TF_curated

,dataset id,thrL,talB,ribF,lspA,carB,caiF,caiT,fixA,yaaU,...,holD,prfC,osmY,deoB,ytjB,serB,slt,trpR,rob,creD
0,GENE_EXPRESSION_ERR1218301,NaN,125.728812,14.672481,8.283922,2.434414,4.007472,0.324927,0.076253,0.232337,...,7.426688,25.759303,762.097680,152.871310,1.965652,6.898852,24.288792,2.492881,92.313130,0.810941
1,GENE_EXPRESSION_ERR1218302,NaN,94.979412,13.584008,4.048387,4.025614,3.316703,0.286131,0.141366,0.076916,...,6.757119,27.780002,434.461472,267.278795,1.442468,4.169862,25.312390,2.143322,96.085111,1.242606
2,GENE_EXPRESSION_ERR1399576,NaN,390.658573,28.281509,21.688995,13.563789,27.467289,1.367853,0.802509,0.698623,...,3.460968,18.613148,2.924724,59.119422,5.729519,8.035470,34.764230,16.327493,82.461126,1.229470
8,GENE_EXPRESSION_ERR1399582,6.636851,464.716255,23.565546,36.076724,13.215864,16.887239,1.968874,0.657782,1.368724,...,3.620969,14.905006,4.153450,80.112855,5.807165,7.287414,37.482123,16.023646,87.637837,2.367772
9,GENE_EXPRESSION_ERR1399583,4.209359,503.412200,25.445917,34.739855,13.788208,20.259933,2.263338,0.763153,0.504917,...,2.896309,15.187347,4.390476,83.451644,8.065745,6.577046,41.260288,12.033436,98.840988,1.219059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,GENE_EXPRESSION_SRR9919243,148.948923,152.714646,24.833296,17.625685,164.517410,2.168428,0.099251,0.151400,0.177423,...,5.056093,36.267601,4.445236,21.141086,3.164742,11.291532,6.295526,7.305722,15.467567,0.788623
1860,GENE_EXPRESSION_SRR9919244,130.236320,128.039858,21.682687,18.566951,91.941032,2.553575,0.199403,0.074188,0.238464,...,4.938713,19.140654,5.177248,24.726398,3.702234,6.706672,6.428653,6.835355,14.472931,0.852143
1861,GENE_EXPRESSION_SRR9919245,77.175933,126.906737,20.455657,18.764994,106.882661,2.136414,0.327560,0.134862,0.170235,...,5.932506,14.954057,5.475841,23.902862,3.092602,5.786205,6.478358,6.709220,15.791694,0.942496
1862,GENE_EXPRESSION_SRR9919246,167.313229,122.605519,23.399676,20.063632,58.707289,1.898784,0.169350,0.162583,0.267347,...,4.986112,21.149352,4.776693,22.016452,3.693050,8.194346,7.250109,6.356556,16.579747,0.773693
1863,GENE_EXPRESSION_SRR9919247,184.258732,120.170441,23.843122,18.557752,63.887982,2.144181,0.219730,0.123956,0.181287,...,4.647282,20.355463,5.798228,21.912910,3.520184,7.736939,7.065605,5.591112,16.101983,0.882420

In [256]:
gene_list = tpm_wo_TF_curated.drop(columns="dataset id").median().index
gene_median = tpm_wo_TF_curated.drop(columns="dataset id").median().values

expression_categorized = pd.DataFrame({"gene":gene_list, "median expression": gene_median})

In [257]:
expression_categorized

      gene  median expression
0     thrL          20.376208
1     talB         132.381025
2     ribF          24.410089
3     lspA          13.209378
4     carB          22.086200
...    ...                ...
1135  serB           7.080661
1136   slt          11.988701
1137  trpR           5.760647
1138   rob          29.567782
1139  creD           1.249324

[1140 rows x 2 columns]

In [258]:
df_for_cnn = expression_categorized.copy()

In [259]:
df_for_cnn = pd.merge(df_for_cnn, df_promoters[["TU first gene", "Promoter sequence", "Sigma factor"]], left_on="gene", right_on="TU first gene")

In [260]:
df_for_cnn.head()

,gene,median expression,TU first gene,Promoter sequence,Sigma factor
0,thrL,20.376208,thrL,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70
1,talB,132.381025,talB,cctggcgataaccgtcttgtcggcggttgcgctgacgttgcgtcgt...,NaN
2,ribF,24.410089,ribF,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70
3,lspA,13.209378,lspA,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70
4,carB,22.086200,carB,agccagccctggtccacacgacgccgcgccgttgttcgaccacttt...,NaN

In [261]:
df_for_cnn.drop(columns="TU first gene", inplace=True)

In [262]:
df_for_cnn = df_for_cnn[df_for_cnn["Sigma factor"]=="sigma70"]

In [264]:
df_for_cnn

,gene,median expression,Promoter sequence,Sigma factor
0,thrL,20.376208,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70
2,ribF,24.410089,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70
3,lspA,13.209378,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70
5,caiF,2.500517,gatgacataagcaggatttagctcacacttatcgacggtgaagttg...,sigma70
6,caiT,0.323250,cgaaacaaaaatgtgataccaatcacagaatacagcttattgaata...,sigma70
...,...,...,...,...
1129,yjjZ,2.468865,cccgatagcaagggatttatctggcttgcaaatgataaaaattatc...,sigma70
1131,prfC,22.610423,tggagcagctcctgtgtaaacactgattgcctcccccccgttgatg...,sigma70
1132,osmY,20.254103,ttgcttatgttttcgctgatatcccgagcggtttcaaaattgtgat...,sigma70
1133,deoB,38.256766,gcaccggaaagcacaccaactgtctatcgccgtatcagcgaataac...,sigma70
1137,trpR,5.760647,gccacggaatggggacgtcgttactgatccgcacgtttatgatatg...,sigma70

In [265]:
df_for_cnn["strength"] = pd.qcut(df_for_cnn['median expression'], q=5, labels=False)

In [266]:
df_for_cnn.head(1)

,gene,median expression,Promoter sequence,Sigma factor,strength
0,thrL,20.376208,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70,4

## Test with Trees

### Libraries

In [267]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [268]:
def sequence_to_onehot(sequence):
    sequence = sequence.upper()
    mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    onehot = np.zeros((len(sequence), len(mapping)))
    for i, nucleotide in enumerate(sequence):
        if nucleotide in mapping:
            onehot[i, mapping[nucleotide]] = 1
    return onehot.flatten()

In [269]:
df_for_cnn["sequence OHE"] = df_for_cnn["Promoter sequence"].apply(sequence_to_onehot)

In [270]:
df_for_cnn

,gene,median expression,Promoter sequence,Sigma factor,strength,sequence OHE
0,thrL,20.376208,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70,4,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
2,ribF,24.410089,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,4,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
3,lspA,13.209378,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,3,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
5,caiF,2.500517,gatgacataagcaggatttagctcacacttatcgacggtgaagttg...,sigma70,1,"[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
6,caiT,0.323250,cgaaacaaaaatgtgataccaatcacagaatacagcttattgaata...,sigma70,0,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, ..."
...,...,...,...,...,...,...
1129,yjjZ,2.468865,cccgatagcaagggatttatctggcttgcaaatgataaaaattatc...,sigma70,1,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
1131,prfC,22.610423,tggagcagctcctgtgtaaacactgattgcctcccccccgttgatg...,sigma70,4,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
1132,osmY,20.254103,ttgcttatgttttcgctgatatcccgagcggtttcaaaattgtgat...,sigma70,3,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
1133,deoB,38.256766,gcaccggaaagcacaccaactgtctatcgccgtatcagcgaataac...,sigma70,4,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, ..."
1137,trpR,5.760647,gccacggaatggggacgtcgttactgatccgcacgtttatgatatg...,sigma70,2,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."

### X and Y

In [271]:
X = list(df_for_cnn["sequence OHE"])
y = list(df_for_cnn["strength"])

In [272]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

### Models

In [273]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
from sklearn.preprocessing import scale, LabelEncoder
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [274]:
KNN_model = KNeighborsClassifier()
Logit_model = LogisticRegression()
DecTree_model = DecisionTreeClassifier()
RF_model = RandomForestClassifier()
GB_model = GradientBoostingClassifier()
XGB_model = XGBClassifier()

In [275]:
list_of_models = [KNN_model, Logit_model, DecTree_model, RF_model, GB_model, XGB_model]

In [276]:
def run_model(model, X_train, y_train):
    L=[]
    model.fit(X_train, y_train)
    y_hat_train = model.predict(X_train)
    y_hat_test = model.predict(X_test)
    accuracy_train = accuracy_score(y_train,y_hat_train)
    accuracy_test = accuracy_score(y_test,y_hat_test)
    L.append(accuracy_train)
    L.append(accuracy_test)
    return L

In [278]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=42)

### Results

In [279]:
L=[]
for elem in list_of_models:
    try:
        L.append(run_model(elem, X_train, y_train))
    except:
        None
L

[[0.4672131147540984, 0.2],
 [0.9897540983606558, 0.14545454545454545],
 [1.0, 0.10909090909090909],
 [1.0, 0.23636363636363636],
 [1.0, 0.21818181818181817],
 [1.0, 0.2727272727272727]]

## Convolutional Neural Network

In [280]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
import tensorflow
import keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [281]:
def one_hot_encode_dna(sequences):
    """
    Codifica una lista de secuencias de ADN en una representación one-hot.

    Parameters:
    sequences (list of str): Lista de secuencias de ADN.

    Returns:
    np.array: Matriz 3D de secuencias codificadas one-hot.
    """
    # Definir el diccionario de codificación one-hot
    mapping = {
        'A': [1, 0, 0, 0],
        'C': [0, 1, 0, 0],
        'G': [0, 0, 1, 0],
        'T': [0, 0, 0, 1],
        'N': [0, 0, 0, 0]  # Para manejar nucleótidos desconocidos
    }
    
    # Obtener la longitud de la secuencia y el número de secuencias
    seq_length = len(sequences[0])
    num_sequences = len(sequences)
    
    # Crear una matriz vacía para almacenar las secuencias codificadas
    one_hot_encoded = np.zeros((num_sequences, seq_length, 4), dtype=np.int8)
    
    # Rellenar la matriz con los valores one-hot
    for i, seq in enumerate(sequences):
        for j, nucleotide in enumerate(seq):
            one_hot_encoded[i, j, :] = mapping.get(nucleotide, [0, 0, 0, 0])
    
    return one_hot_encoded

In [282]:
df_for_cnn["sequence OHE CNN"] = df_for_cnn["Promoter sequence"].apply(lambda x: one_hot_encode_dna(x.upper()))

In [283]:
df_for_cnn

,gene,median expression,Promoter sequence,Sigma factor,strength,sequence OHE,sequence OHE CNN
0,thrL,20.376208,gccgtgagtaaattaaaattttattgacttaggtcactaaatactt...,sigma70,4,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."
2,ribF,24.410089,ttctgatttcggtactcaatcgccggttaaccttgaccgctgtaca...,sigma70,4,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 0, 1]], [[0, 1, 0, 0]..."
3,lspA,13.209378,tgggcgatgaattacgatttgtcctgttgacctccggcgctaccgt...,sigma70,3,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 1, 0]], [[0, 0, 1, 0]..."
5,caiF,2.500517,gatgacataagcaggatttagctcacacttatcgacggtgaagttg...,sigma70,1,"[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[1, 0, 0, 0]], [[0, 0, 0, 1]..."
6,caiT,0.323250,cgaaacaaaaatgtgataccaatcacagaatacagcttattgaata...,sigma70,0,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, ...","[[[0, 1, 0, 0]], [[0, 0, 1, 0]], [[1, 0, 0, 0]..."
...,...,...,...,...,...,...,...
1129,yjjZ,2.468865,cccgatagcaagggatttatctggcttgcaaatgataaaaattatc...,sigma70,1,"[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 1, 0, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."
1131,prfC,22.610423,tggagcagctcctgtgtaaacactgattgcctcccccccgttgatg...,sigma70,4,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 1, 0]], [[0, 0, 1, 0]..."
1132,osmY,20.254103,ttgcttatgttttcgctgatatcccgagcggtttcaaaattgtgat...,sigma70,3,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[[[0, 0, 0, 1]], [[0, 0, 0, 1]], [[0, 0, 1, 0]..."
1133,deoB,38.256766,gcaccggaaagcacaccaactgtctatcgccgtatcagcgaataac...,sigma70,4,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[1, 0, 0, 0]..."
1137,trpR,5.760647,gccacggaatggggacgtcgttactgatccgcacgtttatgatatg...,sigma70,2,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[[[0, 0, 1, 0]], [[0, 1, 0, 0]], [[0, 1, 0, 0]..."

In [284]:
sequences = list(df_for_cnn["Promoter sequence"].str.upper())

In [285]:
sequences

['GCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAA',
 'TTCTGATTTCGGTACTCAATCGCCGGTTAACCTTGACCGCTGTACAAGGTATACTCGGACGATTTTCACTGTTTTGAGCCA',
 'TGGGCGATGAATTACGATTTGTCCTGTTGACCTCCGGCGCTACCGTTGCAGACTATAACGACGCACCTGCTGATGCTCAGC',
 'GATGACATAAGCAGGATTTAGCTCACACTTATCGACGGTGAAGTTGCATACTATCGATATATCCACAATTTTAATATGGCC',
 'CGAAACAAAAATGTGATACCAATCACAGAATACAGCTTATTGAATACCCATTATGAGTTAGCCATTAACGCGTCCACGAGG',
 'TATTGAAAGTTGGATTTATCTGCGTGTGACATTTTCAATATTGGTGATTAAAGTTTTATTTCAAAATTAAAGGGCGTGATA',
 'TTCCTCAACATCATCCTCGCACCAGTCGACGACGGTTTACGCTTTACGTATAGTGGCGACAATTTTTTTTATCGGGAAATC',
 'GGGCAGTAATGACTGTATAAAACCACAGCCAATCAAACGAAACCAGGCTATACTCAAGCCTGGTTTTTTGATGGATTTTCA',
 'CCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATACCCGTTTTTTTGGATGGAGT',
 'TGACGCCGTGCAAATAATCAATGTGGACTTTTCTGCCGTGATTATAGACACTTTTGTTACGCGTTTTTGTCATGGCTTTGG',
 'AACTGACGCATGGGGCACCCCCTTGCTTCATCGTTAGGAATTATTGACTTAATATAGGGAAAATAAAATTGCTGTCTTTTG',
 'TATGCCTTGTGACTGGCTTGACAAGCTTTTCCTCAGCTCCGTAAACTCCTTTCAGTGGGAAATTGTGGGGCAAAGTGGGAA',
 'CTGATGAATTGAAGATTCATCTGGTTGAATATGTGCCGATTGCGCGGTGGAATGATCAACATATGGTAGACGCGGAAGGAA',
 'TGCGTTTTCGCTAATAGTTGACAGATTTATCCGCTCCATCGCGGGCGGATAATCTCCCCTTCCCCAACTTTCTTCGTAACG',
 'TAGACAAATCGGTTGCCGTTTGTTGTTTAAAAATTGTTAACAATTTTGTAAAATACCGACGGATAGAACGACCCGGTGGTG',
 'ATCATGACTTTTGCATGGGCGACAGATAACGACGCCTTACGCCATCTCTCAACCGAAATTATTCAGGCGCGTTTTCTCGCC',
 'GATACCTTTTTGTAGAAATATTGACCGTGCATCCGCGGTCAATGTTAGCTATTATGTTGCGCCCTTTTTTTACGGGTGTTA',
 'GACACAATTTAATCGACAATAATGGTCGTCGCCTCGCTCGCAGTGTGCTAACGTTTATCTTCTTTAAGCCCCTGGTAGAAG',
 'ACAATTCGAGCTTTATTAACAGATTCCGCGAATGAATAGTTTTACTGGTATACTGCGTGTCTTGCGCTTTGTTGCGGTGCC',
 'TGGCAGTGCTGCTACGGATAAATCATTGCCCCCACCAATGTGACTGATAAAATGCCAGACAGCACAACATCAATTTATCAG',
 'ACCCTTTACGCCTCCTCGTTTGCCCGTGGACGCACACGCTACACGCCGCTAAAACGCTGGGCGCTAACGCAATAACAAGGA',
 'TGCGTACCGCTTGCGAACCCGCCAGCGTTTCGAATATTATCTTATCTTTATAATAATCATTCTCGTTTACGTTATCATTCA',
 'GTGCCATGTCCTCTCCCGCGTGAGAAATACGCTTCCCCGTAAGCGCATGGTAAACTATGCCTTCAAATCGGGCTTATCGCG',
 'TTGCAGCAGGAAGTGCATCAGCGGTTGACAGAGGCCCTCAATCCAAACGATAAAGGGTGATGTGTTTACTGATATGAAAAG',
 'ATCTTGTAAATTCAGCTAACCCTTGTGGGGCTGCGCTGAAAAGCGACGTACAATGTCGCTAGTATTAATTCATTTCAATCG',
 'AATAGCCTAATAATCCAGACGATTACCCGTAATATGTTTAATCAGGGCTATACTTAGCACACTTCCACTGTGTGTGACTGT',
 'AACCGCGTTAAATTCACGCCCTTCTCTTTTGACATTTCTTTTGCACTGGTAAACTAAATCACTTTTTTTTGTCCCAGGCTC',
 'AAAGTGCTCTTCGCATAAACCTGATTGATTTAGACGTCTGGATGCCTTAACATCCATTTCATTGACGGCGTTGCCCGTTTC',
 'GTATCCCGGATCGTTTCTGAACAAACTTAATAAACCATTATTATAAAATTAACATATATATTTCAGTTAATTATGTAAAAA',
 'CGCGTTAAATGCTGAATCTTTACGCATTTCTCAAACCCTGAAATCACTGTATACTTTACCAGTGTTGAGAGGTGAGCAATG',
 'TTGCTTGACCCGCAAATGGAAAGACAACTGGTGCTGGGATTATGATGTATACTATTATGTATATTCTGGTGTGCATTATTA',
 'TAAAAAGACGCGGACTCATGTGAAATACTGGTTTTTAGTGCGCCAGATCTCTATAATCTCGCGCAACCTATTTTCCCCTCG',
 'CAACGCCTGGCACTGCCGGGCGTTGTTCTTTTTAACTTCAGGCGGGTTACAATAGTTTCCAGTAAGTATTCTGGAGGCTGC',
 'TTTTAAGAATATTATTAATCTGTAATATATCTTTAACAATCTCAGGTTAAAAACTTTCCTGTTTTCAACGGGACTCTCCCG',
 'GTAAGAAAGAATTGTGAAATGGGGTTGCAAATGAATAATTACACATATAAAGTGAATTTTAATTCAATAAGTGGCGTTCGC',
 'CAGGCTGGGGCTACCTTCGTCTCAAATTTAGATGTTGGATAGGTATTATATAATGGCATTGTGTACTCTTACTACCTGTAT',
 'GCAACCTAAATCGATTGCCAGAATTGAAAATTGTAGTGTGAAGACAGTGTATACCCATCGGCGTAATGCTGAGGCCAAGCT',
 'CCACAAAGAGTCACAGGGATTGAGTGTTGAAATGATCCGGATGAGCATGTATCTTTATGGTTATGTTATAACATAACAGGT',
 'CTATTCAAATTTGTGATACATGTCAAAAAATTGGTTGACCAAACTCGTTATTTATATAAGGGCACTTACGAAGTGCACTCT',
 'CGTAACAATTAAGACACATTTTATATTGAACGTCCAATCAATAACCGCTTTAATAGATAAACACCGCTGATGAATGGAGTG',
 'TTTATCTATTAAAGCGGTTATTGATTGGACGTTCAATATAAAATGTGTCTTAATTGTTACGAATTTGATTTTAAATAGTAA',
 'TTTCAGGCAATGTTTCACCGCGTTTCATTGCAACAATTATGAAACAAGACTAAACCCAATATTCGGTTTCTTAACTTTGCG',
 'AAAAATATATTTCCCCACGAAAACGATTGCTTTTTATCTTCAGATGAATAGAATGCGGCGGATTTTTTGGGTTTCAAACAG',
 'AGGCAGACTACTCGCCGATTGTCATAAGGTAAAAGTCTCATTTATGATGAGTTCCATTGGATTTACTTATAGGTTGCGAAT',
 'ATGGAACTCATCATAAATGAGACTTTTACCTTATGACAATCGGCGAGTAGTCTGCCTCTCATTCCAGAGACAGACAGAGGT',
 'CCTGGTGCACATTCGGGCATGTTTTGATTGTAGCCGAAAACACCCTTCCTATACTGAGCGCACAATAAAAAATCATTTACA',
 'TGTCAACATCGCGACAACTTTCGTAAAACATCCCTACCCTGCTTCAGGTATACTATGCCCCTCGATTCCACAAACATCAGG',
 'AAAGTTAATCTTTTCAACAGCTGTCATAAAGTTGTCACGGCCGAGACTTATAGTCGCTTTGTTTTTATTTTTTAATGTATT',
 'CCGGCAGTGAATTTTCGCTGCCGGGTGGTTTTTTTGCTGTTAGCAACCAGACTTAATGGCAGATCACGGGCGCATACGCTC',
 'TGTCATTTGTAGCACAAGTAAGTGTCAGCAGTGGTGCTTCACACTTGCCCGGTAATTAACGACGAAAGAAAAGTAAGGTGG',
 'GAATACAGAGGGGCGAATTATCTCTTGGCCTTGCTGGTCGTTATCCTGCAAGCTATCACTTTATTGGCTACGGTGATTGGT',
 'TATTGATTTCCGTGGCGCAGAAAAAAGCAAATGGCACATCTGTTTGGGTATAATCGCGCCCATGCTTTTTCGCCAGGGAAC',
 'TGAAGATATGTGCGACGAGCTTTTCATAAATCTGTCATAAATCTGACGCATAATGACGTCGCATTAATGATCGCAACCTAT',
 'CTTTATCTCAAAAGCGTTGCGCCTTTGTTGTATCGTCAGTTCAGGGTAAAATAGATTTCCGTTAACCACCTGGTCAGGACG',
 'CACATCACCTTACCATTGCGCGTTATTTGCTATTTGCCCTGAGTCCGTTACCATGACGGGGCGAAAAATATTGAGAGTCAG',
 'TCCAAGTAACAGGAATTTAATCATGTTTACAGTAATGTAACCTTCCCGTAAAATGCCCACACACTTTAAACGCCACCAGAT',
 'CATGATGAATTTACATGCCTTACCCACTTCCCCTCGCCGTTGGCAATGTTATGATGGCGGGAATTTTTACCAAACACGCTT',
 'TGCCGTGGTGTTTAAACCGCACAGAATAAATTGTCGTGATTTCACCTTTAAAATAAAATTAAAAGAGAAAAAAATTCTCTG',
 'ATTGTAATTTTTCGTAATAATGCGATGAAAACCTGCAAAGAGTGGCTTATAGTTAAGCTAACAAACGAGAGGGCAAGTCCA',
 'GTTCGTGAATTTACAGGCGTTAGATTTACATACATTTGTGAATGTATGTACCATAGCACGACGATAATATAAACGCAGCAA',
 'GATTTCAAATTGGTCAATGGTCAAAAGTTAATAAACCCATTGCTGCGTTTATATTATCGTCGTGCTATGGTACATACATTC',
 'AAAGCACTGAAGCACAACAATCGCAGTTGCAATTATTGCGTACAGCCAGTACATTCTGGCGTTTTCGAGCACAGGCGCAGG',
 'TGATTTGACCTCTCACAGCAATTAGTTCTTCTTCCTCACTTTTCCGCTACAATTATCAACAAGTTGAATCGATAAGAGGCG',
 'GTTTGTTTTCCGGCTTCATACAAAAACTCCTTTCAAATTACGTCATTGTAAGGAACCACTGCCATGAAAATGCGATCCCGC',
 'ACCCGCCTGGTTTATTAATTTCTTGACCTTCCCCTTGCTGGAAGGTTTAACCTTTATCACAGCCAGTCAAAACTGTCTTAA',
 'GCGGAGCGGGTTTTTTTGACAAAATTTGAAAGTTGGAAAAATTTTCCAATAAATAGAGGTAGGAATAAAATGGCAAAAATG',
 'AATAAATTCTAACTATATTTTTTTGCCTGTCTGGATCACATAATCCAGATATTTTCCCTGTATGTTAATTGCAGTCATGCT',
 'GCTGATTTCACAGCCACGCAACCGTTTTCCTTGCTCTCTTTCCGTGCTATTCTCTGTGCCCTCTAAAGCCGAGAGTTGTGC',
 'AAAATTGTCATTTTGCCAATAAGCGATTGCCATCTGATCCCGCTACTCTAGAATTGCCCGGGCAACATGCGGAGGAAATAT',
 'TGACAATTTTGTCATTTTTCTGTCACCGGAAAATCAGAGCCTGGCGAGTAAAGTTGGCGGCATAAAATCACCAGAAATTAT',
 'CCCGTTTAACCGTGTGGATTGTGTCTTGCGACGATGGGCACTAAATGTTAAAAGGTGCCCCTCAACAAAAAAGACACACAG',
 'GAAATCTATAGCGCATTTTTCTCGCTTACCATTTCTCGTTGAACCTTGTAATCTGCTGGCACGCAAAATTACTTTCACATG',
 'CCATGTTTACTGTGCAATTTTTCATTGATTGCAGAAATATATTGATAATATTATTGATAACTATTTGCATTTGCAATAGCG',
 'CTTCCCACGGCGCGCCATTACGCTATTGCAAATGCAAATAGTTATCAATAATATTATCAATATATTTCTGCAATCAATGAA',
 'GGTAACGCAATCTGCAACTCGGGGTTGCATCTGGTTGTGGTTACAATGAAAATGAGAAGCATTATTGATGGATTCGCATAA',
 'TTGCAGATTGCGTTACCTCAAGAGTTGACATAGTGCGCGTTTGCTTTTAGGTTAGCGACCGAAAATATAAATGATAATCAT',
 'ATTTATTGACCGTCTAAATGAGAGTTTTTGATATATAACTACAGACAGCTACTATAACTTTCATCTATTTATTCACAGCGC',
 'CACTGGTTTGGTTAAAAATTAAACACTTGAAAGTGTAATTTCCGTCCCCATATACTAAGCATCAGTAAAAAACTCCCGCCT',
 'AATAGGCTGATTCAAGGCATTTACGGGAGAAAAAATCGGCTCAAACATGAAGAAATGAAATGACTGAGTCAGCCGAGAAGA',
 'ATATCGTTATTATCACTCCCTTTTACTGGCTAAACCAGAAAACTTATTTTATCATTCAAAAAATCAGGTCGGATTGACGCC',
 'ACTCACAAAAGACACGCGTTTAATTTGCGATACGAATTAAATTTTCACACACTCTGTAGCAGATGATCTAACAATCTGATT',
 'TTTACACCCCGCCCGCAGATTTTTGCGAAATCTTTGCAGCCAGAATTCTACCCTTCCGGTATCACTTTTAGGCCACTGGAG',
 'TCGCCCGCCGACTACGCTCTGCATTTGCCGAAAAGGGGATTGTTGTCGCAGCATAACCCCGATTAATAAAGAATGAAAAAA',
 'CGACAAACTATATGTAGGTTAATTGTAATGATTTTGTGAACAGCCTATACTGCCGCCAGGTCTCCGGAACACCCTGCAATC',
 'AGGTTTCGAGCAAGCTTCCGCGATTATGGGCAGCTTCTTCGTCAAATTTATCATGTGGGGCATCCTTACCGCTCTGGCGTA',
 'CATTATGTGATCAATTTCACTTGATTGAAATTATTTGTATTGTATTTGTATTATTTACAGGATGAATTTATCGGGCATAAT',
 'TAATCCGTTCATAGTGTAAAACCCCGTTTACACATTCTGACGGAAGATATAGATTGGAAGTATTGCATTCACTAAGATAAG',
 'CGCAAAGCTGACCGCACAAAAGGGGAGTGCTTTTCTGTGCTTAGCGGTTAGAATAGTCTCATGACTATATCTGGAGTTGAC',
 'GTGAGCCATGGGGCTTCTCCAAAACGTGTTTTTTGTTGTTAATTCGGTGTAGACTTGTAAACCTAAATCTTTTCAATTTGG',
 'GATCGTCCGTTGTCATAATCGACTTGTAAACCAAATTGAAAAGATTTAGGTTTACAAGTCTACACCGAATTAACAACAAAA',
 'AGTACATACGTTTACGCTGCGTCGATGCACAGCCTCATCATTTTGCAGTATCCTTAAGATATTCCTTATATCTTCAGGAGA',
 'CGTTGCTAAAATTCTTAGCCATACTGGACAACTCCCCTATGGAGTCATAATCTTAATCAATCATTTGATTAAGAATGGACT',
 'CTGAAAACCGAAAAATGCCACAATATTGGCTGTTTATACAGTATTTCAGGTTTTCTCATGGCATTAACCGCCGCGCTTAAA',
 'AAATGTATTTCTTTTTCGCGCAATGGGTGATAGAAAATCGCTCCAAGTGATAATGCTTATCAAAATTATTATCACTTTCAC',
 'AAAAATCAGCATTATGCATGTCATTGATTTGTCTTATTTTGTAAAAATATATCGTTCAAAAAATAAGCACATCTCTGTCAA',
 'ACTGCGTCGTATGCTGCCGCCGCTGGGTAACCAGTGGATCATCAGCATTAAAGACACCTCGCTGTTTATTGTGATCGGCGT',
 'ATACCCAATGCTGGTTGAGCATTTGTTGAAAAAATTTTCCCCCGTTTTGACTAAAATGCGCCAGGATTGATGGAATCATTA',
 'ACCCAGCGCTACGCCCGAGGTGGCATACAGTCTGTGGCGTTTTTCTGACATAATAGGCAAATTCGATTTTGCCTCCGCAGG',
 'GCAGGATATTGCATAAACTTTAAAAACTTTACCAACTTACGGTTTCTTTAAGTTTGTGTGTGCGTTATTAATCACCAAACT',
 'TTAATTGCTAAAAGCTATAACTGTTAAACACAATACAGTGAAAAGTTTTAGACTGAAGGCTCACTTTGCAGAGGGAAGCGT',
 'CTGGAGCGATCATATCCGCCGAACAATCATTAAAGAAAGCCGCCCATTTATTCTGGATTATTTGCACAAACAGGGTTGGGC',
 'CATTTAAATTATTTAATCATGTTTATTGCATATAAATTCACTTGATGGCATTGTTATCCCATGCCGCAGACACGGCCAAAA',
 'CATAACATTTCCTTTTAATTGCAACTTTACTCGTCCTTCCGCTTTCAGTAGTGTGTCATCGCGCATTTCGACTTCATCTTT',
 'TGCCCCTTGTCCCCTGTCAAATGCTTGACGGCTCGCCCTAATTCTCTAAATTGTATTTCTAGAGTTGGCGAGGTTTTGAAC',
 'AAAATAATTTTACAAATCAGTAACAAAAGTAAAGAAGGCGACACCATGCGACTATGGGTCGCCTTTATTTTTTCCCCGTTG',
 'TTGTACTAAAAATCGATGTTTTGCTTTGACAATCCCCTGGTGTTTTGCGAAAACATTCGAGGAAGAAAAAAAACAGTATTC',
 'AACTGAAAATTCAGTATTTTCTTCTTTCCTCAAGCTGATTATTAGCCTGGAATAGAGAGTAGAGGGAACTCCCGATCGGGA',
 'CATGGCGATCTGGCGGCCGTTGCGCCGTTGCCGCGAGCTCACTTTACCAAACCGAATATTGTGATCAAACCCAATGCCAAT',
 'GGGCCTTTTTTAGCGCGAGAGCCTTTTTTGTCAGCTATCTATACTTTAAGGTGACTGCCAAAACAGACTCGACGTAGCCTT',
 'AAACTGGTTTTTGCACACAACGTTAACGATTTGTGGCGTCGGCGCGTATAATGCGCGCGGTTATGTTAACGGTACGCCTGT',
 'TGATTGCCGCACCGGCTGGGAAATAGACCCCGTCGCATAAATGATTATGATAAGATTTATGCATTCATAACCCGATCCATC',
 'ACATCAGCGGAAGTGGCAGCAACATATTGCCAATCACTTTTTTCAGTGTAAAAAGCATCCTTTCTGGTTCCTTTTTTAACC',
 'AAAGGTGGCATATGGTGTGATCGGGGTTCAATAAATTGCGAAACAAGGTATACTCCAGCAGTTCCTGAAGATGTTTATTGT',
 'CAGAAAAAGATACACAAAATTTATATTTGGAATTTTCTTGTCTCTCCGACAGACTGACCGAATTGTTATCAATGTTAACAA',
 'ACGTTTGCGTTTTTTTTGCCGCAGGTCAATTCCCTTTTGGTCCGAACTCGCACATAATACGCCCCCGGTTTGCACACCGGG',
 'ACTGGTTTATTCCGAACTGATCGGACTTGTTCAGCGTACACGTGTTAGCTATCCTGCGTGCTTCAATAAAATAAGGCTTAC',
 'CGAGGCTCTTTCCGAAAATAGGGTTGATCTTTGTTGTCACTGGATGTACTGTACATCCATACAGTAACTCACAGGGGCTGG',
 'GTGACGGGAAAACATAAATTAATCTTGCCCCTTAAGAATAAGTTGCCTATTTTCGTAGTTAACGGATCCGTTAATGTGAAT',
 'GTAAAGATGGGTAAAACTTCTGGGTGCCCTTACGCATTATCATTATGCTGCTTAATTAATTACATCTGTCATAGAGAGTGA',
 'TTCGTAACAATTTCCTTATCTTTAATTTGTATTTTGCTAAGATTTATCTTATGCTCACAAGTCGTATTTCCAGAGGGGGAT',
 'AATGAGCAAATATGAACAGCGGCACTGGTCAGGATGAACGGCTTACGGCAGAATATGAACAGATATGAACAGAATGAGTAA',
 'GCCGTAAGCCGTTCATCCTGACCAGTGCCGCTGTTCATATTTGCTCATTAAGATCGCTTCACTAAACCATAATTCTACAGG',
 'TTGCTACGCATGTCACATTTAACATGGTTGCACAAAGTTGCAACATCATGGATATTTCACGATAACGTTAAGTTGCACCTT',
 'TTATAAACATTCCGCTTGTGTTTTTCTTTGCCGTAATGATAATCGCTATCACTGCGATTTACTTTTCTTTGCATAGATTGA',
 'TTGTTTGTGGGCGGAATTTCATATTGACAACAGTACAGTTCTTATATCTATTAATAATAGAAAGGGATCTACAACCTACAG',
 'TAAGTGTGATCTACGTCACTCATAACTGCAACGGATAATTTGTTGTTGCATAAAATGTGTGCTCGATCTCATTCATGGCCG',
 'AGTAGCAACCGGGCAAAGATTGACCAGACAGGAGATTATAACCTTGCATATATTGATCAGGCGGGCAGTGCCAACGATGCC',
 'ATCATTCAATTTGTTATTTTTGTGTTGCAATTCATTCTCCGACACGCCATTTTCTTTCTCTCGCAAATTCGTTTTGGATGC',
 'AAACAATAAAAATCGTAGCTTCCTGTTGTCATTAGGTTATTTTACCTGTATAAATAACCAGTATATTCAACAGGGGGCTAT',
 'CGCATTCGCGCCCTTTATTTTTCGTGCAAAGGAAAACGTTTCCGCTTATCCTTTGTGTCCGGCAAAAACATCCCTTCAGCC',
 'TAGCCAGAAACGCGCCGCGCGTCGTTTGCTTGAACGCGACGCCTGATTTGATACTCCCCCCTGACTCCTTCATACTGAAAG',
 'CGCAAAATGGGTCGCTATTTATGCCGTTGATGGTCATTGCGGACAGGTACAATTCACGTTGTAGAAATGGCTGGGGGCGAA',
 'GACCCATTTTGCGTTTATTCCGCCGATAACGCGCGCGTAAAGGCATTTAAGCTGATGGCAGAATTTTGATACCTGCGGAGG',
 'GGCCGCAAGGTCATCGCTAAGTAATCACGCATCTGCGTGATGAAGCTTAGTGAGGATTTTCCCCAGGCAACTGGGGAAAGA',
 'ATCGTGGTAAGACCTGCCGGGATTTAGTTGCAAATTTTTCAACATTTTATACACTACGAAAACCATCGCGAAAGCGAGTTT',
 'AACTTGATTAACATCAATTTTGGTATGACCAATGCACCATTCATGTTATTCTCAATAGCGAAGAACATTTTCATTGCTGTA',
 'TTACAAATTCTTTGCACTTCCCTGCACTATCCGACACTGTCACCATCCATAATTCAGGCTTATCTGTTTATTACAATAACC',
 'GCCAGTCTGCCGTCTTCTATAACGGTGAAGTGTGCCTCGGTGGCGGTATTATTGAGCAGCGTCTGCCGCTGCCGGTCTGAT',
 'TCATCCAATTTAGCTGAAATCTTATTTATACTTTGTACAATTTTAGCGTATATTGTACAAAGTATTATTGGGTCGTGTACA',
 'AAACGGTTATGTTTTGGTATTAAAAGAAAGACACAAGAAGATATGTCTGTTACCGTCTTACTCTCGCCTCACCCATTACCC',
 'GCAAAAAATTAATTTATCATTCTGTACACATATTTCGTACAAGTTTGCTATTGTTACTTCACTTAACATTGATTAACATTT',
 'GACAAATATTGATAGCCTGAATCAGTATTGATCTGCTGGCAAGAACAGACTACTGTATATAAAAACAGTATAACTTCAGGC',
 'TTAAAGCGCAATAAGTCGTTGTCTGCGGCATTTTTGCCGAGTGCCGTGTATAATAGGCAAAGTTATTTCCATTTCTGCAAT',
 'TATCTGCATTTGATACGCAGTTTTTTGTCAAGCGGGGCCGCAACCAGTAAACTACGCGCCAGTTATGTACACACTCAGGAC',
 'AGGGTTGTAATTGTGATCACGCCCGCACATAACCCACTGGGTGTTGTCTATACTTTACACATAAGGAAGAGGGGTATTCCC',
 'TCGCAAGAAAACGTTTTCGCGAGGTTGATGCGGTGCTTTCCTGGCTGTTAGAATACGCCCCGTCGCGCCTGACTGGGACAG',
 'CATTTATCCTCGCGGGGTATCATGACGTCGAAACCTGCCGTGACTATGGTGATAACGAGCGCGTAACGCTCGGCCGCTATT',
 'AATATCAGCCCGTCGGCGGAACTGTTTTATGAAGACCTTGATGAAGCTGATAACATTGAGGTAATCCGCAAATTGCTGGAT',
 'CGCGAGAAAATACGACAAAAGTTGCCAGTAATCGTTATTCTTTAAGGCTATGGTTTTTCATTATTACCGGAAGTTACCGAC',
 'GTGAGTACAGTGACTTCATAAAAATTATGAGATTTTTCACGGTGCTGTAAAATCCCTACCCTTACCGATGTAAAGCGACTA',
 'TCCCCATCACTCTTGATCGTTATCAATTCCCACGCTGTTTCAGAGCGTTACCTTGCCCTTAAACATTAGCAATGTCGATTT',
 'GGTGCAATAATTGAACGTTCGCGATTTTTGAAAGAAAACGGTCAATGGTACTATATTGACGGTACACGTCCGCAGTTTGGT',
 'TTTGAATTCCTTACATTCCTGGCTATTGCACAACTGAATTTAAGGCTCTATTATTACCTCAACAAACCACCCCAATATAAG',
 'TTCACTGATCCTGATCGTCTTGCCTTATTGAATATGATTGCTATTTGCATTTAAAATCGAGACCTGGTTTTTCTACTGAAA',
 'TGCTTTTCCATACAAGACCTGATGCTGCCACCCGAGGCTTAACCAGGGTACAATTGCCCGCTAATTAACACCTGCATAAAA',
 'AGCACAGAAAGTCGAGCATTATGAGATTGCCAGTTACGGGACATTAGCGACGCTGGCTGAACAATTAGGTTACCGTAAAGC',
 'GCAGGCGGAACACCGGAAGAAAACCGTGACATTTTAACACGTTTGTTACAAGGTAAAGGCGACGCCGCCCATGAAGCAGCC',
 'TGGCAAATATTCTGAAATGAGCTGTTGACAATTAATCATCGAACTAGTTAACTAGTACGCAAGTTCACGTAAAAAGGGTAT',
 'ATACACTAAGGCTATAAATGATATAGTGGTTATAGTTAGCACCTTTTTTATTATTAAATCGTATTAGTCACCCGCCAGGTG',
 'ACTGGAGACGATTCGTAAATTCGCTGGATTTTTGACTAAAGTTTCTTTAGGATTTGTCTCATCGTATGATTAATTACACCA',
 'CGGAATGGCACAAATCTGTCAATTTTTCCTGGAACTGGCGTTTTCAGTTATGATTGTGGGACTTATCAAAAAGGAGAGGCC',
 'GCCTGCCAGGGGAGAAATCGCAACTGTTAATTTTTTATTTCCACGGGTAGAATGCTCGCCGTTTACCTGTTTCGCGCCACT',
 'CTGATATTTGTTATCGCCGATCCGTCTTTCTCCCCTTCCCGCCTTGCGTCAGGATAACGATTTCCTTTACGACCAAGGAGC',
 'TGTCAATGATTGTTGACAGAAACCTTCCTGCTATCCAAATAGTGTCATATCATCATATTAATTGTTCTTTTTTCAGGTGAA',
 'CTGCGGATTAAGCGCAAATAGCGTTTGCTGTGTTATTGACAGTTAGCATAAACTAGGTGTGACGTTAACTATATGTAAACA',
 'CTCTGCTGTTAAGGTTTGCTTAGACTTACTTGCTCCCTAAAAAGATGTTAAAATTGACAAATATCAATTACGGCTTGAGCA',
 'TATGTATTATCTTCGATACATTCACCAGACTTATTATCATTTCAGAGGAATTATTTGATTAAGGTTTTACTTAAGGCGTAA',
 'CTGCATTCCAGGGGAGCTGATTCAGATAATCCCCAATGACCTTTCATCCTCTATTCTTAAAATAGTCCTGAGTCAGAAACT',
 'GCCAAACAACCTGGCAGGTGCAGGCAATCCCCTTTGCATCAGTACTGATAATGTGAACCTGACTAAACCGCCCACAGAGCG',
 'ATCCGTCACAGTTCAAACATACAAAATTTGTGATTTTACTTAACTATTGTGTAACTTTCATAAAACAATGTGATTCGTGTT',
 'GGCCCTGGTGGGGTAAAGCGCCAGGGCCAGAAGTCGATACGACCTGTGCTATGATTCATAAATCACAACAATAACAACAGA',
 'GAACATAGGCTTCGATTTATTGCGCTATCTCTGTGGCAGGATTGTGAATAAAGTGTCAACAAGCAACGGGGCATCGCCCAT',
 'CCCTTCACAGAATTGTCCTTTCACGATTCCGTCTCTCTGATGATTGATGTTAATTAACAATGTATTCACCGAAAACAAACA',
 'GTGCGTTATAGCGTACAGGCACCGTAGCATTTGTCCGTTATAACGCACAAGTGATAAACTTCCGTTTTGCCGGAGGAGTCG',
 'AGATGTTCTTTTTGATTTCGCGCAAAAAGATTCAGAATTTTACTGTTAGTTTCCTCGCGCAGTAATACCCCTGAAAAAAGA',
 'ATCTCTTTATGTGACTAACTTCACTTACATCCACTTATTTCTCTTCGTAAAATTACTTTGGAATTAAGTACAATAAGAAGA',
 'TGCCTACAGCTGTAAGAAACTCCGCTCAGTACTGAAGCACCAGTCCTATTTCCTCTTTTCTCCAGCCTGTTATATTAAGCA',
 'GCGCACAATTGAAGCCAGAGTCTTATTTTTTATATTGAAAAATATGTTAATTTAAACACTATGAGAGATGATGCTTAACTT',
 'GTAGAGCGGATAAGATGTGTTTCCAGATTGACTTATCCTCACTAAAGGATAAAACTTATAATATCCCCTTAAGCGGATAAA',
 'CCATCACAGATATAAATGAGCAAGAACTGAACAATTGCATTAAAGATTTAAATATGTTCAAAGTGAAGAATGAATTATGAC',
 'CATCAGGAGTTGATCAAAACAGGGGTTCGGCGTATTAAAGTTTGCTAACCTGTCGTACCAATTCAAACAGGTTGTATGACT',
 'CGTGGCATCGGTCAATTCATTCATTTGACTTATACTTGCCTGGGCAATATTATCCCCTGCAACTAATTACTTGCCAGGGCA',
 'GAACACAATAAAGATTTAATTCAGCCTTCGTTTAGGTTACCTCTGCTAATATCTTTCTCATTGAGATGAAAATTAAGGTAA',
 'AACTTCGGATTTCTATGAAAATATTGACGTAATTTTGCTTTTCTCTCGTTAGAATAGCGCGCACAAGGAACTGTGAAAAAG',
 'TATTTGACAGCTAGTTGGCTGATTTTAAATGCCTTATAACAATTGGCAATATTCTTATTTGGCAATTATAAAAATAGCAAC',
 'ATTTAACTCACTAAAGTTAAGAAGATTGAAAAGTCTTAAACATATTTTCAGAATAATCGGATTTATATGTTTGAAAATTAT',
 'CATAATTGATTATTTGACGTGGTTTGATGGCCTCCACGCACGTTGTGATATGTAGATGATAATCATTATCACTTTACGGGT',
 'GATGGCTGGATGTCTAAAATAAACATTGCTTCATATGTTCAACTATGCGTTAATGATTGCGTCGGTTTGAAGAACAGACGA',
 'CGACTACTTTCTGACTTCCTTCGTGACTTGCCCTAAGCATGTTGTAGTGCGATACTTGTAATGACATTTGTAATTACAAGA',
 'CATAGTTAGCTAATGCTAAATCGTATTGACTATGTTTTTGTTAACATCTATCTTGTTAGTTATGACTAACAATAAAGGTGT',
 'GTTAGCTATAGCATACAAAATCACTTGACCGATATGTTAGTCATGGCTAATCTTGTTTGCATCAACACACCGCACGGTGTT',
 'ATTGTTAACTGGTTAACGTCACCTGGAGGCACCAGGCACTGCATCACAAAATTCATTGTTGAGGACGCGATAATGAAAACG',
 'GTTACACGCTGAAACCAACCACTCACGGAAGTCTGCCATTCCCAGGGATATAGTTATTTCAACGGCCCCGCAGTGGGGTTA',
 'CGCTCAGGTAAAGAAGTGAAAATATTTTGAGTTAATTCTTAAGCTATGATACAAATCAGGCGTGTTCAACTACCGAGGACA',
 'ATTTTCAGTACGTTATAGGGCGTTTGTTACTAATTTATTTTAACGGAGTAACATTTAGCTCGTACATGAGCAGCTTGTGTG',
 'CAAAAAGTCGTACTAGTCTCAGTTTTTGTTAAAAAAGTGTGTAGGATATTGTTACTCGCTTTTAACAGGGCAACGGAACAC',
 'CGACTTTTTGCGGCTCCAGGTTACTTCCCGTAGGATTCTTGCTTTAATAGTGGGATTAATTTCCACATTAAAACAGGGATT',
 'GCCTTCGCACTATTCAACAGCAATGATAGGCGCTCACCTGACAACGCGGTAAACTAGTTATTCACGCTAACTATAATGGTT',
 'AAATTTTAGTGAGGCATAAATCACATTACGCAACGATAATAGCGGGTATAAGATAAATAAAAGGTAAAACGTTTTATCTGT',
 'TCGTTGCGTAATGTGATTTATGCCTCACTAAAATTTGATAAAACGTTTTATCTTCTCGCGCAATTTACTGAATCCAGATTG',
 'CGTTTGTCTGTGAAAGATATGTCGCTTGTTAATGTGCAGGCACTGAAGGACAATCGGGCAATTGGCGTAGTACAACTTAAT',
 'AACGTAAAAAATCGTTGCGCAATCGTGGATTTTTACCCTGCTTTGTTTTTATAATGGTGCGCACTTTTATATCCAGAAAAA',
 'TATATGTAACAGATTATTACAAAGGACTTGTCTGAAAGTGCAAGATAGTGAACATTACCTGCCGTTTCCCCTCCCACTATA',
 'GTTAATGTCCAAAGTAGCAACTTTGCTTGCACTAGACCGACTGGTCTACTACACTCCAACGCATGAACAAACACACCGAAC',
 'TTACCCGACGTTGTAATCCAACATTGCGAGCGGCGTAAAGCCGCCGCTATACTAAAACAACATTTTGAATCTGTTAGCCAT',
 'GAACTCATCGCGCCCGCATCTTTACTGCATCGACAAGTAATATTTGTCATAATGCGCGCTGCAATTTATCCGTATTAAGAG',
 'GCAACAAATAGAGCAAAGGGATAAAATAGCAAAAGCGTGATGAAAATGTTATTTTCCGATGCCGCACTGACCCGCTACAAT',
 'ATTTTTTTGCGCTCGCCAACGAAACGTATTTTTTAACAATAAAAGCTATTAACTTTCTCTTCTTCTATGCATTAGAATCAT',
 'TTGTTACGGCAACAGGGTAAGTTCATCTTTTGTCTCACCTTTTAATTTGCTACCCTATCCATACGCACAATAAGGCTATTG',
 'ATAATGATAAGTGTTTTTACCACTTCCCCTTTTCGTCAAGATCGGCCAAAATTCCACGCTTACACTATTTGCGTACTGGCC',
 'ACGGTAAAGCCCCTGCGTTTGCTGGGTTGAACTGATAATCATTATCACTAACATGCTGTTATACGCTGAAAGCGATGAAGT',
 'ATTGCAGCAGGCGCAACAAGCTGGTTGCAAAACGATTGATGGATACGGCATGTTGTTGTGGCAAGGGGCTGAACAGTTCAC',
 'TATATTTGCTTGAACGATTCACCGTTTTTTTCATCCGGTTAAATATGCAAAGATAAATGCGCAGAAATGTGTTTCTCAAAC',
 'GAAAAGTCATCCAGCGTTTTTCCCCGGATATGACGCCGGAAGATCCCATTGTGATGGAAAGCATTAAACTGGCGTTGGCAA',
 'TAGACTTAGTCGAGATCAGCCCTAACGCCGAGCCGCCGGTTTGTCGTATAATGGATTACGGCAAATTCCTCTATGAAAAGA',
 'GATTAATCGTCAATTTAAGAGAAAGAGTTACACCGTCACCACTTCCGTGCACTGTATAAAAATCCTATACTGTACGTATCG',
 'TAGACCACCAGCCAGATCCCGCTTCGGAGACTATTCTGGAAACGGTGTTATGAAATACACGCAAAGCGGGACGTACAGGGG',
 'CATATTCTTGTTCATATTCCGTCCTCTTGTTTATCAGCGTGTTAGATAAGCCTGGAATACATTGGGCGCTTTTTCAAGCCC',
 'GTAACCTTTGTCATCGACCCGCCTCTTTTTTAATCGCTTCCCGCCTGTTACACTGGATAGATAACCAGCATTCGGAGTCAA',
 'ACACTTTCATTGTTTTACCGTTGCTCTGATTAATTGACGCTAAAGTCAGTAAAGTTAATCTCGTCAACACGGCACGCTACT',
 'CTTTCCTGGGTCATTTTTTTCTTGCTTACCGTCACATTCTTGATGGTATAGTCGAAAACTGCAAAAGCACATGACATAAAC',
 'AGATCAAGTTTAGGACAAAATTTTGCCAGTTGGTGTTAATGTTTTGTTAGAATCAGTCACGTAATGTGAGCACGATTAAAG',
 'CGATGGTGGATAAATCCTGGACTGGCCTGATTTCTACCGGGATCACCTACAAATTCTGATAATGCATCTTTCCAGGGCATT',
 'GCTAAAAAGTAACCAATAAATGGTATTTAAAATGCAAATTATCAGGCGTACCCTGAAACGGCTGGAATAAACCGTTTTCAG',
 'AAAAATTTTGCGACGAGAATTACGTGACGAAGCGCGCGGCAAAGTGGACAATAAAGCCTGAGCGTTAAGTCAGTCGTCAGA',
 'CGCTTCGCAACCTTTTCGTTGGGTAATTATCAAGCTGGTATGATGAGTTAATATTATGTTAACGGCATGTATATCATTTGG',
 'TTCGTTTGCAAAGGAAGGTAAATCTTTGCCAAATCAGAGGCGTCTCTGATATGTTTAACTCCCGTTTAACAACCATGGAGT',
 'GAAAGTTAAATTACGGATCTTCATCACATAAAATAATTTTTTCGATATCTAAAATAAATCGCGAAACGCAGGGGTTTTTGG',
 'AAGCAATGAAATAATATATTCCAACAGTTGTTTTATATTCTCAAAATATGTTAAGGTTGCGCCCTCATTTGGGGAGTAGCC',
 'TGCGCATCTTTTGTCTCGATATACATTTTCTGACATCCTCATCCGCTATGCTACAGGCACTAAAAATGGTTATTGAGGAGC',
 'GTCTTTATTGCTGATGTTGATTTCTCAACCGAAAAGAAATATACTGTATAAAATCACAGTTATTATGAGAGGCTGCAAATG',
 'GTTGAGAAATCAACATCAGCAATAAAGACACACGCAAACGTTTTCGTTTATACTGCGCGCGGAATTAATCAGGGGATATTC',

In [286]:
encoded_sequences = one_hot_encode_dna(sequences)

In [287]:
labels = df_for_cnn["strength"]

In [288]:
labels = np.array(labels).astype(np.float32).reshape(-1, 1)

In [289]:
labels.shape

(543, 1)

In [290]:
labelencoder = LabelEncoder()

In [291]:
labels = labelencoder.fit_transform(labels)

c:\Users\Sergio\miniconda3\envs\python3_10_9\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [292]:
labels

array([4, 4, 3, 1, 0, 0, 2, 2, 0, 1, 1, 3, 4, 0, 4, 3, 4, 2, 3, 3, 2, 4,
       4, 4, 3, 4, 4, 2, 3, 1, 1, 3, 3, 0, 1, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 3, 1, 1, 1, 1, 1, 1, 3, 3, 4, 3, 1, 3, 4, 2, 3, 2, 3, 3, 0,
       0, 1, 1, 0, 2, 3, 2, 1, 1, 1, 0, 3, 4, 2, 3, 1, 1, 3, 3, 1, 4, 3,
       1, 2, 3, 1, 2, 1, 1, 3, 4, 2, 3, 1, 2, 2, 1, 4, 2, 4, 3, 1, 3, 4,
       3, 2, 4, 0, 2, 4, 2, 1, 4, 0, 1, 0, 3, 1, 0, 2, 0, 0, 2, 3, 3, 0,
       0, 4, 4, 3, 1, 3, 2, 1, 1, 0, 4, 2, 3, 4, 1, 4, 1, 2, 2, 3, 4, 2,
       2, 0, 2, 4, 3, 3, 2, 2, 1, 3, 4, 4, 0, 2, 0, 0, 1, 1, 3, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 3, 1, 0, 0, 0, 2, 3, 0, 0, 0, 0, 1, 4, 4, 3, 2,
       1, 1, 2, 2, 2, 0, 3, 1, 4, 2, 4, 3, 1, 2, 4, 2, 4, 0, 1, 4, 1, 1,
       4, 3, 1, 0, 2, 2, 2, 4, 0, 1, 3, 2, 2, 4, 2, 2, 4, 3, 4, 0, 3, 3,
       3, 0, 3, 0, 0, 0, 2, 1, 3, 3, 4, 0, 4, 1, 0, 4, 0, 1, 3, 2, 0, 1,
       0, 4, 3, 2, 0, 2, 1, 4, 2, 0, 4, 4, 3, 4, 2, 1, 0, 1, 4, 3, 4, 4,
       3, 1, 1, 0, 0, 1, 0, 0, 2, 2, 3, 2, 0, 2, 3, 3, 4, 4, 3, 3, 3, 4,
       3, 4, 2, 4, 1, 4, 2, 4, 1, 1, 3, 2, 2, 3, 4, 4, 3, 1, 4, 2, 1, 1,
       3, 4, 0, 0, 3, 3, 0, 3, 1, 0, 0, 1, 2, 2, 3, 3, 3, 3, 2, 2, 1, 1,
       0, 0, 2, 3, 3, 3, 0, 1, 2, 4, 4, 2, 2, 0, 1, 0, 1, 4, 2, 2, 0, 0,
       1, 0, 0, 3, 0, 2, 3, 0, 0, 4, 4, 4, 4, 3, 4, 2, 4, 1, 2, 0, 4, 0,
       4, 2, 4, 1, 3, 2, 0, 1, 0, 4, 4, 4, 2, 2, 3, 4, 2, 4, 4, 0, 0, 2,
       2, 3, 3, 0, 2, 0, 2, 1, 2, 3, 4, 2, 0, 4, 1, 2, 3, 1, 4, 4, 0, 3,
       2, 3, 4, 4, 1, 0, 3, 1, 4, 1, 2, 1, 2, 4, 4, 1, 2, 3, 4, 2, 3, 4,
       3, 2, 2, 3, 4, 4, 1, 3, 4, 3, 3, 2, 0, 1, 0, 0, 4, 3, 3, 3, 2, 2,
       2, 2, 4, 1, 3, 3, 4, 1, 0, 3, 1, 2, 4, 3, 4, 2, 0, 0, 0, 0, 1, 1,
       0, 1, 2, 2, 0, 1, 2, 4, 4, 4, 1, 1, 4, 0, 4, 2, 3, 1, 0, 1, 1, 0,
       1, 0, 4, 0, 1, 2, 1, 1, 0, 0, 1, 4, 3, 4, 2], dtype=int64)

In [293]:
labels = to_categorical(labels)

In [294]:
labels

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [298]:
X_train, X_test, y_train, y_test = train_test_split(encoded_sequences, labels, test_size=0.1, stratify=labels, random_state=42)

In [310]:
model = Sequential([
    # Conv1D(filters=200, kernel_size=7, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    Conv1D(filters=200, kernel_size=6, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    # Conv1D(filters=200, kernel_size=5, activation='relu', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    MaxPooling1D(pool_size=6),
    Dropout(0.8),
    Flatten(),
    Dense(200, activation='relu'),
    Dense(5, activation='softmax')  # Salida única para clasificación binaria
])

# Compilar el modelo
model.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])

In [318]:
model = Sequential([
    Conv1D(filters=200, kernel_size=6, activation='relu', 
           input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2]),
           kernel_regularizer=regularizers.l2(0.01)),  # Regularización L2 en la capa Conv1D
    MaxPooling1D(pool_size=6),
    Dropout(0.5),  # Ajusta la tasa de Dropout según sea necesario
    Flatten(),
    Dense(200, activation='relu', kernel_regularizer=regularizers.l2(0.01)),  # Regularización L2 en la capa Dense
    Dropout(0.5),  # Agregar Dropout también después de la capa Dense
    Dense(5, activation='softmax')  # Salida única para clasificación múltiple
])

# Compilar el modelo
model.compile(optimizer="rmsprop", loss='categorical_crossentropy', metrics=['accuracy'])  # Cambia 'binary_crossentropy' por 'categorical_crossentropy' si tienes más de dos clases

In [319]:
# Entrenar el modelo
model.fit(X_train, y_train, epochs=500, batch_size=32, validation_split=0.2)

Epoch 1/500
13/13 [==============================] - 1s 48ms/step - loss: 4.7306 - accuracy: 0.2179 - val_loss: 4.0443 - val_accuracy: 0.2041
Epoch 2/500
13/13 [==============================] - 0s 14ms/step - loss: 3.5597 - accuracy: 0.2462 - val_loss: 3.1190 - val_accuracy: 0.2143
Epoch 3/500
13/13 [==============================] - 0s 15ms/step - loss: 2.8825 - accuracy: 0.2615 - val_loss: 2.6529 - val_accuracy: 0.2449
Epoch 4/500
13/13 [==============================] - 0s 14ms/step - loss: 2.4522 - accuracy: 0.2410 - val_loss: 2.2714 - val_accuracy: 0.1939
Epoch 5/500
13/13 [==============================] - 0s 14ms/step - loss: 2.1888 - accuracy: 0.2538 - val_loss: 2.1302 - val_accuracy: 0.2041
Epoch 6/500
13/13 [==============================] - 0s 15ms/step - loss: 2.0146 - accuracy: 0.2923 - val_loss: 1.9777 - val_accuracy: 0.2041
Epoch 7/500
13/13 [==============================] - 0s 14ms/step - loss: 1.8887 - accuracy: 0.2821 - val_loss: 1.8944 - val_accuracy: 0.2143
Epoch 8/500
13/13 [==============================] - 0s 14ms/step - loss: 1.8369 - accuracy: 0.3103 - val_loss: 1.8547 - val_accuracy: 0.2041
Epoch 9/500
13/13 [==============================] - 0s 14ms/step - loss: 1.7714 - accuracy: 0.3538 - val_loss: 1.8371 - val_accuracy: 0.2857
Epoch 10/500
13/13 [==============================] - 0s 14ms/step - loss: 1.7356 - accuracy: 0.3436 - val_loss: 1.8568 - val_accuracy: 0.1327
Epoch 11/500
13/13 [==============================] - 0s 14ms/step - loss: 1.6877 - accuracy: 0.3692 - val_loss: 1.8004 - val_accuracy: 0.2449
Epoch 12/500
13/13 [==============================] - 0s 14ms/step - loss: 1.6832 - accuracy: 0.3744 - val_loss: 1.7842 - val_accuracy: 0.2041
Epoch 13/500
13/13 [==============================] - 0s 14ms/step - loss: 1.6608 - accuracy: 0.3538 - val_loss: 1.8542 - val_accuracy: 0.1939
Epoch 14/500
13/13 [==============================] - 0s 14ms/step - loss: 1.6507 - accuracy: 0.4026 - val_loss: 1.7839 - val_accuracy: 0.2449
Epoch 15/500
13/13 [==============================] - 0s 14ms/step - loss: 1.6112 - accuracy: 0.4282 - val_loss: 1.7656 - val_accuracy: 0.2755
Epoch 16/500
13/13 [==============================] - 0s 15ms/step - loss: 1.6066 - accuracy: 0.4462 - val_loss: 1.7984 - val_accuracy: 0.2449
Epoch 17/500
13/13 [==============================] - 0s 14ms/step - loss: 1.5931 - accuracy: 0.4462 - val_loss: 1.8370 - val_accuracy: 0.1735
Epoch 18/500
13/13 [==============================] - 0s 14ms/step - loss: 1.5702 - accuracy: 0.4692 - val_loss: 1.9449 - val_accuracy: 0.2449
Epoch 19/500
13/13 [==============================] - 0s 15ms/step - loss: 1.5537 - accuracy: 0.4897 - val_loss: 1.8766 - val_accuracy: 0.1633
Epoch 20/500
13/13 [==============================] - 0s 15ms/step - loss: 1.5287 - accuracy: 0.5103 - val_loss: 1.9465 - val_accuracy: 0.1429
Epoch 21/500
13/13 [==============================] - 0s 14ms/step - loss: 1.5336 - accuracy: 0.4615 - val_loss: 1.8007 - val_accuracy: 0.2857
Epoch 22/500
13/13 [==============================] - 0s 14ms/step - loss: 1.5225 - accuracy: 0.5410 - val_loss: 1.8882 - val_accuracy: 0.2755
Epoch 23/500
13/13 [==============================] - 0s 13ms/step - loss: 1.4764 - accuracy: 0.5564 - val_loss: 1.9062 - val_accuracy: 0.2245
Epoch 24/500
13/13 [==============================] - 0s 13ms/step - loss: 1.4805 - accuracy: 0.5308 - val_loss: 2.0151 - val_accuracy: 0.2551
Epoch 25/500
13/13 [==============================] - 0s 14ms/step - loss: 1.4893 - accuracy: 0.5718 - val_loss: 1.9019 - val_accuracy: 0.2449
Epoch 26/500
13/13 [==============================] - 0s 16ms/step - loss: 1.4374 - accuracy: 0.5538 - val_loss: 1.9485 - val_accuracy: 0.2347
Epoch 27/500
13/13 [==============================] - 0s 14ms/step - loss: 1.4573 - accuracy: 0.5462 - val_loss: 2.1098 - val_accuracy: 0.1939
Epoch 28/500
13/13 [==============================] - 0s 14ms/step - loss: 1.4154 - accuracy: 0.6231 - val_loss: 1.9141 - val_accuracy: 0.2347
Epoch 29/500
13/13 [==============================] - 0s 14ms/step - loss: 1.4095 - accuracy: 0.6359 - val_loss: 1.9416 - val_accuracy: 0.1939
Epoch 30/500
13/13 [==============================] - 0s 14ms/step - loss: 1.4153 - accuracy: 0.6103 - val_loss: 1.9299 - val_accuracy: 0.2653
Epoch 31/500
13/13 [==============================] - 0s 14ms/step - loss: 1.3407 - accuracy: 0.6769 - val_loss: 2.0108 - val_accuracy: 0.2347
Epoch 32/500
13/13 [==============================] - 0s 15ms/step - loss: 1.3670 - accuracy: 0.6513 - val_loss: 1.9756 - val_accuracy: 0.2551
Epoch 33/500
13/13 [==============================] - 0s 15ms/step - loss: 1.3702 - accuracy: 0.6513 - val_loss: 2.0866 - val_accuracy: 0.1633
Epoch 34/500
13/13 [==============================] - 0s 15ms/step - loss: 1.3689 - accuracy: 0.6718 - val_loss: 1.9508 - val_accuracy: 0.2857
Epoch 35/500
13/13 [==============================] - 0s 13ms/step - loss: 1.3178 - accuracy: 0.6949 - val_loss: 2.0148 - val_accuracy: 0.2143
Epoch 36/500
13/13 [==============================] - 0s 14ms/step - loss: 1.3055 - accuracy: 0.7000 - val_loss: 2.0159 - val_accuracy: 0.2041
Epoch 37/500
13/13 [==============================] - 0s 14ms/step - loss: 1.2961 - accuracy: 0.7103 - val_loss: 2.1283 - val_accuracy: 0.1939
Epoch 38/500
13/13 [==============================] - 0s 14ms/step - loss: 1.3270 - accuracy: 0.6974 - val_loss: 2.0848 - val_accuracy: 0.1837
Epoch 39/500
13/13 [==============================] - 0s 14ms/step - loss: 1.2523 - accuracy: 0.7462 - val_loss: 2.1280 - val_accuracy: 0.2143
Epoch 40/500
13/13 [==============================] - 0s 13ms/step - loss: 1.2530 - accuracy: 0.7205 - val_loss: 2.0881 - val_accuracy: 0.2143
Epoch 41/500
13/13 [==============================] - 0s 13ms/step - loss: 1.2202 - accuracy: 0.7538 - val_loss: 2.0882 - val_accuracy: 0.2143
Epoch 42/500
13/13 [==============================] - 0s 13ms/step - loss: 1.2620 - accuracy: 0.7487 - val_loss: 2.1078 - val_accuracy: 0.2449
Epoch 43/500
13/13 [==============================] - 0s 14ms/step - loss: 1.2035 - accuracy: 0.7949 - val_loss: 2.3497 - val_accuracy: 0.2653
Epoch 44/500
13/13 [==============================] - 0s 14ms/step - loss: 1.2587 - accuracy: 0.7436 - val_loss: 2.2693 - val_accuracy: 0.1939
Epoch 45/500
13/13 [==============================] - 0s 15ms/step - loss: 1.2113 - accuracy: 0.7564 - val_loss: 2.0739 - val_accuracy: 0.2551
Epoch 46/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1615 - accuracy: 0.7667 - val_loss: 2.3499 - val_accuracy: 0.2959
Epoch 47/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1996 - accuracy: 0.7564 - val_loss: 2.2336 - val_accuracy: 0.1633
Epoch 48/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1375 - accuracy: 0.8128 - val_loss: 2.1612 - val_accuracy: 0.2347
Epoch 49/500
13/13 [==============================] - 0s 13ms/step - loss: 1.1762 - accuracy: 0.7846 - val_loss: 2.4021 - val_accuracy: 0.1735
Epoch 50/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1597 - accuracy: 0.8103 - val_loss: 2.1898 - val_accuracy: 0.1939
Epoch 51/500
13/13 [==============================] - 0s 13ms/step - loss: 1.1490 - accuracy: 0.8077 - val_loss: 2.4426 - val_accuracy: 0.2143
Epoch 52/500
13/13 [==============================] - 0s 13ms/step - loss: 1.1109 - accuracy: 0.8308 - val_loss: 2.2768 - val_accuracy: 0.2347
Epoch 53/500
13/13 [==============================] - 0s 16ms/step - loss: 1.1427 - accuracy: 0.8103 - val_loss: 2.2549 - val_accuracy: 0.2143
Epoch 54/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0493 - accuracy: 0.8410 - val_loss: 2.4817 - val_accuracy: 0.2143
Epoch 55/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0927 - accuracy: 0.8179 - val_loss: 2.5686 - val_accuracy: 0.1939
Epoch 56/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1409 - accuracy: 0.8103 - val_loss: 2.3153 - val_accuracy: 0.2245
Epoch 57/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0693 - accuracy: 0.8410 - val_loss: 2.6600 - val_accuracy: 0.2551
Epoch 58/500
13/13 [==============================] - 0s 15ms/step - loss: 1.0943 - accuracy: 0.8385 - val_loss: 2.4167 - val_accuracy: 0.2245
Epoch 59/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0343 - accuracy: 0.8590 - val_loss: 2.3363 - val_accuracy: 0.2449
Epoch 60/500
13/13 [==============================] - 0s 14ms/step - loss: 1.1148 - accuracy: 0.8128 - val_loss: 2.3038 - val_accuracy: 0.2041
Epoch 61/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0189 - accuracy: 0.8590 - val_loss: 2.4535 - val_accuracy: 0.1837
Epoch 62/500
13/13 [==============================] - 0s 13ms/step - loss: 1.0605 - accuracy: 0.8538 - val_loss: 2.3143 - val_accuracy: 0.2857
Epoch 63/500
13/13 [==============================] - 0s 13ms/step - loss: 1.0308 - accuracy: 0.8513 - val_loss: 2.4681 - val_accuracy: 0.1939
Epoch 64/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0616 - accuracy: 0.8179 - val_loss: 2.3583 - val_accuracy: 0.2347
Epoch 65/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0186 - accuracy: 0.8692 - val_loss: 2.4252 - val_accuracy: 0.2347
Epoch 66/500
13/13 [==============================] - 0s 13ms/step - loss: 1.0400 - accuracy: 0.8179 - val_loss: 2.4269 - val_accuracy: 0.1837
Epoch 67/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0350 - accuracy: 0.8410 - val_loss: 2.3263 - val_accuracy: 0.2551
Epoch 68/500
13/13 [==============================] - 0s 13ms/step - loss: 1.0131 - accuracy: 0.8667 - val_loss: 2.2857 - val_accuracy: 0.2143
Epoch 69/500
13/13 [==============================] - 0s 13ms/step - loss: 0.9417 - accuracy: 0.9103 - val_loss: 2.3382 - val_accuracy: 0.2143
Epoch 70/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0141 - accuracy: 0.8590 - val_loss: 2.4601 - val_accuracy: 0.2653
Epoch 71/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0323 - accuracy: 0.8538 - val_loss: 2.6458 - val_accuracy: 0.2143
Epoch 72/500
13/13 [==============================] - 0s 15ms/step - loss: 0.9737 - accuracy: 0.8949 - val_loss: 2.4068 - val_accuracy: 0.2653
Epoch 73/500
13/13 [==============================] - 0s 14ms/step - loss: 1.0080 - accuracy: 0.8718 - val_loss: 2.3581 - val_accuracy: 0.2551
Epoch 74/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9664 - accuracy: 0.8949 - val_loss: 2.7920 - val_accuracy: 0.2551
Epoch 75/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9242 - accuracy: 0.8974 - val_loss: 2.4860 - val_accuracy: 0.2551
Epoch 76/500
13/13 [==============================] - 0s 13ms/step - loss: 0.9798 - accuracy: 0.8821 - val_loss: 2.5890 - val_accuracy: 0.1939
Epoch 77/500
13/13 [==============================] - 0s 13ms/step - loss: 0.9498 - accuracy: 0.8897 - val_loss: 2.5114 - val_accuracy: 0.2041
Epoch 78/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9277 - accuracy: 0.9000 - val_loss: 2.3666 - val_accuracy: 0.2449
Epoch 79/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9356 - accuracy: 0.8718 - val_loss: 2.9215 - val_accuracy: 0.1735
Epoch 80/500
13/13 [==============================] - 0s 16ms/step - loss: 0.9470 - accuracy: 0.8718 - val_loss: 2.3223 - val_accuracy: 0.2245
Epoch 81/500
13/13 [==============================] - 0s 16ms/step - loss: 0.9518 - accuracy: 0.8872 - val_loss: 2.4221 - val_accuracy: 0.2551
Epoch 82/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9184 - accuracy: 0.9026 - val_loss: 2.5616 - val_accuracy: 0.2347
Epoch 83/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9770 - accuracy: 0.8821 - val_loss: 2.6151 - val_accuracy: 0.2143
Epoch 84/500
13/13 [==============================] - 0s 15ms/step - loss: 0.9140 - accuracy: 0.9026 - val_loss: 2.6844 - val_accuracy: 0.1837
Epoch 85/500
13/13 [==============================] - 0s 16ms/step - loss: 0.9604 - accuracy: 0.8564 - val_loss: 2.3866 - val_accuracy: 0.2449
Epoch 86/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9229 - accuracy: 0.9154 - val_loss: 2.4420 - val_accuracy: 0.2449
Epoch 87/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8857 - accuracy: 0.9154 - val_loss: 3.4172 - val_accuracy: 0.2245
Epoch 88/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9441 - accuracy: 0.8872 - val_loss: 2.5613 - val_accuracy: 0.1939
Epoch 89/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9240 - accuracy: 0.8897 - val_loss: 2.5489 - val_accuracy: 0.1735
Epoch 90/500
13/13 [==============================] - 0s 15ms/step - loss: 0.8812 - accuracy: 0.9103 - val_loss: 2.4332 - val_accuracy: 0.2449
Epoch 91/500
13/13 [==============================] - 0s 13ms/step - loss: 0.9241 - accuracy: 0.8795 - val_loss: 2.4964 - val_accuracy: 0.2143
Epoch 92/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8935 - accuracy: 0.9026 - val_loss: 2.5625 - val_accuracy: 0.2959
Epoch 93/500
13/13 [==============================] - 0s 13ms/step - loss: 0.9360 - accuracy: 0.8667 - val_loss: 2.5893 - val_accuracy: 0.2347
Epoch 94/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9095 - accuracy: 0.9128 - val_loss: 2.4698 - val_accuracy: 0.2347
Epoch 95/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8939 - accuracy: 0.8949 - val_loss: 2.3965 - val_accuracy: 0.2347
Epoch 96/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8822 - accuracy: 0.9026 - val_loss: 2.4155 - val_accuracy: 0.1837
Epoch 97/500
13/13 [==============================] - 0s 15ms/step - loss: 0.8418 - accuracy: 0.9256 - val_loss: 2.6191 - val_accuracy: 0.1939
Epoch 98/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8755 - accuracy: 0.8923 - val_loss: 2.4596 - val_accuracy: 0.2551
Epoch 99/500
13/13 [==============================] - 0s 14ms/step - loss: 0.9110 - accuracy: 0.8846 - val_loss: 2.5813 - val_accuracy: 0.2551
Epoch 100/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8387 - accuracy: 0.9051 - val_loss: 2.9096 - val_accuracy: 0.2245
Epoch 101/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8914 - accuracy: 0.8923 - val_loss: 2.6713 - val_accuracy: 0.1633
Epoch 102/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8947 - accuracy: 0.8821 - val_loss: 2.4857 - val_accuracy: 0.2347
Epoch 103/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8629 - accuracy: 0.9000 - val_loss: 2.4216 - val_accuracy: 0.2755
Epoch 104/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8274 - accuracy: 0.9231 - val_loss: 2.6034 - val_accuracy: 0.1837
Epoch 105/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8431 - accuracy: 0.9154 - val_loss: 2.7679 - val_accuracy: 0.2857
Epoch 106/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8808 - accuracy: 0.8974 - val_loss: 2.5439 - val_accuracy: 0.2143
Epoch 107/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8202 - accuracy: 0.9179 - val_loss: 3.3388 - val_accuracy: 0.2041
Epoch 108/500
13/13 [==============================] - 0s 16ms/step - loss: 0.9270 - accuracy: 0.8795 - val_loss: 2.7631 - val_accuracy: 0.1735
Epoch 109/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8548 - accuracy: 0.9000 - val_loss: 2.4514 - val_accuracy: 0.2347
Epoch 110/500
13/13 [==============================] - 0s 16ms/step - loss: 0.7538 - accuracy: 0.9513 - val_loss: 2.8382 - val_accuracy: 0.1837
Epoch 111/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8798 - accuracy: 0.8795 - val_loss: 2.6995 - val_accuracy: 0.2245
Epoch 112/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8269 - accuracy: 0.9205 - val_loss: 2.7381 - val_accuracy: 0.1633
Epoch 113/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8546 - accuracy: 0.8974 - val_loss: 2.4988 - val_accuracy: 0.1939
Epoch 114/500
13/13 [==============================] - 0s 13ms/step - loss: 0.7649 - accuracy: 0.9462 - val_loss: 2.5312 - val_accuracy: 0.2653
Epoch 115/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8158 - accuracy: 0.9256 - val_loss: 2.5535 - val_accuracy: 0.2041
Epoch 116/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8309 - accuracy: 0.9256 - val_loss: 2.4807 - val_accuracy: 0.2245
Epoch 117/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8349 - accuracy: 0.9000 - val_loss: 2.5676 - val_accuracy: 0.2755
Epoch 118/500
13/13 [==============================] - 0s 13ms/step - loss: 0.7891 - accuracy: 0.9487 - val_loss: 2.4012 - val_accuracy: 0.2449
Epoch 119/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7909 - accuracy: 0.9333 - val_loss: 2.6400 - val_accuracy: 0.1837
Epoch 120/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7802 - accuracy: 0.9359 - val_loss: 2.6043 - val_accuracy: 0.2449
Epoch 121/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8377 - accuracy: 0.9179 - val_loss: 2.6109 - val_accuracy: 0.2245
Epoch 122/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7792 - accuracy: 0.9436 - val_loss: 2.5759 - val_accuracy: 0.2551
Epoch 123/500
13/13 [==============================] - 0s 15ms/step - loss: 0.8420 - accuracy: 0.9077 - val_loss: 2.6722 - val_accuracy: 0.2143
Epoch 124/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7941 - accuracy: 0.9256 - val_loss: 2.8264 - val_accuracy: 0.1633
Epoch 125/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7860 - accuracy: 0.9308 - val_loss: 2.4739 - val_accuracy: 0.2245
Epoch 126/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7868 - accuracy: 0.9205 - val_loss: 2.7673 - val_accuracy: 0.2449
Epoch 127/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7524 - accuracy: 0.9359 - val_loss: 3.1102 - val_accuracy: 0.1531
Epoch 128/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7976 - accuracy: 0.9128 - val_loss: 2.6484 - val_accuracy: 0.2041
Epoch 129/500
13/13 [==============================] - 0s 15ms/step - loss: 0.7704 - accuracy: 0.9385 - val_loss: 2.6549 - val_accuracy: 0.1735
Epoch 130/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8027 - accuracy: 0.9231 - val_loss: 2.7374 - val_accuracy: 0.2143
Epoch 131/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7938 - accuracy: 0.9256 - val_loss: 2.7453 - val_accuracy: 0.2143
Epoch 132/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8196 - accuracy: 0.9103 - val_loss: 2.7685 - val_accuracy: 0.2449
Epoch 133/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7383 - accuracy: 0.9487 - val_loss: 2.9387 - val_accuracy: 0.2041
Epoch 134/500
13/13 [==============================] - 0s 13ms/step - loss: 0.8251 - accuracy: 0.8974 - val_loss: 2.7137 - val_accuracy: 0.2245
Epoch 135/500
13/13 [==============================] - 0s 14ms/step - loss: 0.8013 - accuracy: 0.9051 - val_loss: 2.7276 - val_accuracy: 0.1429
Epoch 136/500
13/13 [==============================] - 0s 18ms/step - loss: 0.7538 - accuracy: 0.9462 - val_loss: 2.5362 - val_accuracy: 0.2347
Epoch 137/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7975 - accuracy: 0.9205 - val_loss: 2.7776 - val_accuracy: 0.1633
Epoch 138/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7836 - accuracy: 0.9256 - val_loss: 2.7853 - val_accuracy: 0.2245
Epoch 139/500
13/13 [==============================] - 0s 14ms/step - loss: 0.7652 - accuracy: 0.9359 - val_loss: 3.1334 - val_accuracy: 0.2041
Epoch 140/500

In [320]:
# Evaluar el modelo
loss_test, accuracy_test = model.evaluate(X_test, y_test)
print(f'Loss: {loss_test}, Accuracy: {accuracy_test}')

2/2 [==============================] - 0s 6ms/step - loss: 3.0026 - accuracy: 0.2909
Loss: 3.0026443004608154, Accuracy: 0.290909081697464

In [314]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout, Flatten, Dense, BatchNormalization
from tensorflow.keras import regularizers

# Construir el modelo
model = Sequential([
    Conv1D(filters=64, kernel_size=7, activation='relu', padding='same', input_shape=(encoded_sequences.shape[1], encoded_sequences.shape[2])),
    BatchNormalization(),
    MaxPooling1D(pool_size=3),
    Dropout(0.5),

    Conv1D(filters=128, kernel_size=5, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(pool_size=3),
    Dropout(0.5),

    Conv1D(filters=256, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(pool_size=3),
    Dropout(0.5),

    Flatten(),
    Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dropout(0.5),
    Dense(5, activation='softmax')  # Capa de salida para clasificación múltiple con 5 categorías
])

# Compilar el modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Mostrar el resumen del modelo
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_19 (Conv1D)          (None, 81, 64)            1856

 batch_normalization (BatchN  (None, 81, 64)           256
 ormalization)

 max_pooling1d_7 (MaxPooling  (None, 27, 64)           0
 1D)

 dropout_7 (Dropout)         (None, 27, 64)            0

 conv1d_20 (Conv1D)          (None, 27, 128)           41088

 batch_normalization_1 (Batc  (None, 27, 128)          512
 hNormalization)

 max_pooling1d_8 (MaxPooling  (None, 9, 128)           0
 1D)

 dropout_8 (Dropout)         (None, 9, 128)            0

 conv1d_21 (Conv1D)          (None, 9, 256)            98560

 batch_normalization_2 (Batc  (None, 9, 256)           1024
 hNormalization)

 max_pooling1d_9 (MaxPooling  (None, 3, 256)           0
 1D)

 dropout_9 (Dropout)         (None, 3, 256)            0

 flatten_7 (Flatten)         (None, 768)               0

 dense_14 (Dense)            (None, 512)               393728

 dropout_10 (Dropout)        (None, 512)               0

 dense_15 (Dense)            (None, 5)                 2565

=================================================================
Total params: 539,589
Trainable params: 538,693
Non-trainable params: 896
_________________________________________________________________

In [315]:
model.fit(X_train, y_train, epochs=500, batch_size=32, validation_split=0.2)

Epoch 1/500
13/13 [==============================] - 3s 46ms/step - loss: 9.8710 - accuracy: 0.1846 - val_loss: 7.6113 - val_accuracy: 0.1633
Epoch 2/500
13/13 [==============================] - 0s 25ms/step - loss: 8.7555 - accuracy: 0.2231 - val_loss: 7.6034 - val_accuracy: 0.1327
Epoch 3/500
13/13 [==============================] - 0s 25ms/step - loss: 8.5753 - accuracy: 0.1949 - val_loss: 7.5808 - val_accuracy: 0.1327
Epoch 4/500
13/13 [==============================] - 0s 23ms/step - loss: 8.0527 - accuracy: 0.2103 - val_loss: 7.8217 - val_accuracy: 0.1327
Epoch 5/500
13/13 [==============================] - 0s 22ms/step - loss: 7.4884 - accuracy: 0.2410 - val_loss: 7.8403 - val_accuracy: 0.1327
Epoch 6/500
13/13 [==============================] - 1s 64ms/step - loss: 7.3417 - accuracy: 0.1667 - val_loss: 8.1363 - val_accuracy: 0.1327
Epoch 7/500
13/13 [==============================] - 1s 37ms/step - loss: 6.9471 - accuracy: 0.1949 - val_loss: 8.4559 - val_accuracy: 0.1327
Epoch 8/500
13/13 [==============================] - 0s 26ms/step - loss: 6.6634 - accuracy: 0.2205 - val_loss: 8.1817 - val_accuracy: 0.1327
Epoch 9/500
13/13 [==============================] - 0s 22ms/step - loss: 6.4254 - accuracy: 0.2333 - val_loss: 8.4042 - val_accuracy: 0.1327
Epoch 10/500
13/13 [==============================] - 0s 24ms/step - loss: 6.2566 - accuracy: 0.2282 - val_loss: 8.5646 - val_accuracy: 0.1327
Epoch 11/500
13/13 [==============================] - 0s 22ms/step - loss: 6.0416 - accuracy: 0.2179 - val_loss: 8.5048 - val_accuracy: 0.1327
Epoch 12/500
13/13 [==============================] - 0s 21ms/step - loss: 5.8324 - accuracy: 0.2282 - val_loss: 8.8139 - val_accuracy: 0.1327
Epoch 13/500
13/13 [==============================] - 0s 22ms/step - loss: 5.6520 - accuracy: 0.2385 - val_loss: 8.5820 - val_accuracy: 0.1327
Epoch 14/500
13/13 [==============================] - 0s 22ms/step - loss: 5.4844 - accuracy: 0.2436 - val_loss: 8.9194 - val_accuracy: 0.1327
Epoch 15/500
13/13 [==============================] - 0s 23ms/step - loss: 5.3235 - accuracy: 0.2744 - val_loss: 8.9962 - val_accuracy: 0.1327
Epoch 16/500
13/13 [==============================] - 0s 27ms/step - loss: 5.1830 - accuracy: 0.2462 - val_loss: 8.9583 - val_accuracy: 0.1327
Epoch 17/500
13/13 [==============================] - 0s 22ms/step - loss: 5.0075 - accuracy: 0.2359 - val_loss: 8.4890 - val_accuracy: 0.1327
Epoch 18/500
13/13 [==============================] - 0s 21ms/step - loss: 4.8827 - accuracy: 0.2205 - val_loss: 8.0463 - val_accuracy: 0.1327
Epoch 19/500
13/13 [==============================] - 0s 21ms/step - loss: 4.7031 - accuracy: 0.2308 - val_loss: 7.7314 - val_accuracy: 0.1327
Epoch 20/500
13/13 [==============================] - 0s 22ms/step - loss: 4.5563 - accuracy: 0.2615 - val_loss: 7.5792 - val_accuracy: 0.1327
Epoch 21/500
13/13 [==============================] - 1s 85ms/step - loss: 4.4136 - accuracy: 0.2205 - val_loss: 7.7052 - val_accuracy: 0.1327
Epoch 22/500
13/13 [==============================] - 0s 24ms/step - loss: 4.3190 - accuracy: 0.2256 - val_loss: 7.4301 - val_accuracy: 0.1327
Epoch 23/500
13/13 [==============================] - 0s 22ms/step - loss: 4.1517 - accuracy: 0.2846 - val_loss: 7.1636 - val_accuracy: 0.1327
Epoch 24/500
13/13 [==============================] - 0s 22ms/step - loss: 4.0436 - accuracy: 0.2615 - val_loss: 7.0656 - val_accuracy: 0.1327
Epoch 25/500
13/13 [==============================] - 0s 21ms/step - loss: 3.9673 - accuracy: 0.2487 - val_loss: 6.9656 - val_accuracy: 0.1327
Epoch 26/500
13/13 [==============================] - 0s 25ms/step - loss: 3.8306 - accuracy: 0.2308 - val_loss: 6.6507 - val_accuracy: 0.1327
Epoch 27/500
13/13 [==============================] - 0s 23ms/step - loss: 3.6960 - accuracy: 0.2410 - val_loss: 6.4278 - val_accuracy: 0.1327
Epoch 28/500
13/13 [==============================] - 0s 22ms/step - loss: 3.6092 - accuracy: 0.2410 - val_loss: 5.8182 - val_accuracy: 0.1327
Epoch 29/500
13/13 [==============================] - 0s 25ms/step - loss: 3.5305 - accuracy: 0.2179 - val_loss: 5.9128 - val_accuracy: 0.1327
Epoch 30/500
13/13 [==============================] - 0s 25ms/step - loss: 3.4432 - accuracy: 0.2590 - val_loss: 5.6874 - val_accuracy: 0.1327
Epoch 31/500
13/13 [==============================] - 0s 22ms/step - loss: 3.3567 - accuracy: 0.2282 - val_loss: 5.7745 - val_accuracy: 0.1327
Epoch 32/500
13/13 [==============================] - 1s 92ms/step - loss: 3.2509 - accuracy: 0.2846 - val_loss: 5.3478 - val_accuracy: 0.1327
Epoch 33/500
13/13 [==============================] - 1s 75ms/step - loss: 3.1727 - accuracy: 0.2821 - val_loss: 5.1161 - val_accuracy: 0.1327
Epoch 34/500
13/13 [==============================] - 0s 23ms/step - loss: 3.1119 - accuracy: 0.2590 - val_loss: 4.9376 - val_accuracy: 0.1327
Epoch 35/500
13/13 [==============================] - 0s 21ms/step - loss: 3.0692 - accuracy: 0.2564 - val_loss: 4.5083 - val_accuracy: 0.1327
Epoch 36/500
13/13 [==============================] - 0s 24ms/step - loss: 3.0002 - accuracy: 0.2385 - val_loss: 4.2504 - val_accuracy: 0.1327
Epoch 37/500
13/13 [==============================] - 0s 22ms/step - loss: 2.8992 - accuracy: 0.2641 - val_loss: 4.0651 - val_accuracy: 0.1327
Epoch 38/500
13/13 [==============================] - 0s 25ms/step - loss: 2.9002 - accuracy: 0.2462 - val_loss: 3.7710 - val_accuracy: 0.1327
Epoch 39/500
13/13 [==============================] - 0s 25ms/step - loss: 2.8127 - accuracy: 0.2564 - val_loss: 3.5867 - val_accuracy: 0.1327
Epoch 40/500
13/13 [==============================] - 0s 24ms/step - loss: 2.7338 - accuracy: 0.2590 - val_loss: 3.3879 - val_accuracy: 0.1531
Epoch 41/500
13/13 [==============================] - 0s 32ms/step - loss: 2.6791 - accuracy: 0.2974 - val_loss: 3.2149 - val_accuracy: 0.1429
Epoch 42/500
13/13 [==============================] - 0s 26ms/step - loss: 2.6444 - accuracy: 0.2846 - val_loss: 3.1228 - val_accuracy: 0.1531
Epoch 43/500
13/13 [==============================] - 1s 100ms/step - loss: 2.6010 - accuracy: 0.2821 - val_loss: 3.0429 - val_accuracy: 0.1531
Epoch 44/500
13/13 [==============================] - 1s 74ms/step - loss: 2.5465 - accuracy: 0.2538 - val_loss: 2.9735 - val_accuracy: 0.1429
Epoch 45/500
13/13 [==============================] - 0s 25ms/step - loss: 2.5737 - accuracy: 0.2308 - val_loss: 2.9170 - val_accuracy: 0.1327
Epoch 46/500
13/13 [==============================] - 0s 22ms/step - loss: 2.4747 - accuracy: 0.2974 - val_loss: 2.7988 - val_accuracy: 0.1531
Epoch 47/500
13/13 [==============================] - 0s 22ms/step - loss: 2.4495 - accuracy: 0.3103 - val_loss: 2.8258 - val_accuracy: 0.1531
Epoch 48/500
13/13 [==============================] - 0s 24ms/step - loss: 2.3964 - accuracy: 0.2795 - val_loss: 2.8065 - val_accuracy: 0.1429
Epoch 49/500
13/13 [==============================] - 0s 24ms/step - loss: 2.3522 - accuracy: 0.2974 - val_loss: 2.7273 - val_accuracy: 0.1735
Epoch 50/500
13/13 [==============================] - 0s 24ms/step - loss: 2.3723 - accuracy: 0.2590 - val_loss: 2.6718 - val_accuracy: 0.1735
Epoch 51/500
13/13 [==============================] - 0s 25ms/step - loss: 2.3728 - accuracy: 0.2333 - val_loss: 2.6224 - val_accuracy: 0.2041
Epoch 52/500
13/13 [==============================] - 0s 24ms/step - loss: 2.2413 - accuracy: 0.3256 - val_loss: 2.5901 - val_accuracy: 0.2245
Epoch 53/500
13/13 [==============================] - 1s 50ms/step - loss: 2.1994 - accuracy: 0.3333 - val_loss: 2.5080 - val_accuracy: 0.2041
Epoch 54/500
13/13 [==============================] - 1s 95ms/step - loss: 2.2201 - accuracy: 0.3154 - val_loss: 2.4658 - val_accuracy: 0.2347
Epoch 55/500
13/13 [==============================] - 1s 53ms/step - loss: 2.2254 - accuracy: 0.3103 - val_loss: 2.4567 - val_accuracy: 0.2347
Epoch 56/500
13/13 [==============================] - 0s 21ms/step - loss: 2.1415 - accuracy: 0.2949 - val_loss: 2.3729 - val_accuracy: 0.2449
Epoch 57/500
13/13 [==============================] - 0s 21ms/step - loss: 2.1622 - accuracy: 0.3103 - val_loss: 2.3318 - val_accuracy: 0.2449
Epoch 58/500
13/13 [==============================] - 0s 21ms/step - loss: 2.1038 - accuracy: 0.3487 - val_loss: 2.3220 - val_accuracy: 0.2551
Epoch 59/500
13/13 [==============================] - 0s 22ms/step - loss: 2.0795 - accuracy: 0.3410 - val_loss: 2.2977 - val_accuracy: 0.2449
Epoch 60/500
13/13 [==============================] - 0s 24ms/step - loss: 2.1386 - accuracy: 0.2821 - val_loss: 2.2708 - val_accuracy: 0.2857
Epoch 61/500
13/13 [==============================] - 0s 24ms/step - loss: 2.0893 - accuracy: 0.2667 - val_loss: 2.2915 - val_accuracy: 0.2653
Epoch 62/500
13/13 [==============================] - 0s 22ms/step - loss: 2.0331 - accuracy: 0.3487 - val_loss: 2.3274 - val_accuracy: 0.2653
Epoch 63/500
13/13 [==============================] - 0s 22ms/step - loss: 2.0278 - accuracy: 0.3333 - val_loss: 2.3024 - val_accuracy: 0.2755
Epoch 64/500
13/13 [==============================] - 0s 21ms/step - loss: 2.0261 - accuracy: 0.3179 - val_loss: 2.3019 - val_accuracy: 0.2755
Epoch 65/500
13/13 [==============================] - 0s 21ms/step - loss: 1.9982 - accuracy: 0.3487 - val_loss: 2.2937 - val_accuracy: 0.2755
Epoch 66/500
13/13 [==============================] - 1s 99ms/step - loss: 1.9628 - accuracy: 0.3718 - val_loss: 2.3040 - val_accuracy: 0.2857
Epoch 67/500
13/13 [==============================] - 1s 66ms/step - loss: 1.9740 - accuracy: 0.3564 - val_loss: 2.2803 - val_accuracy: 0.2857
Epoch 68/500
13/13 [==============================] - 0s 23ms/step - loss: 1.9317 - accuracy: 0.3641 - val_loss: 2.2516 - val_accuracy: 0.2653
Epoch 69/500
13/13 [==============================] - 0s 22ms/step - loss: 1.9486 - accuracy: 0.3154 - val_loss: 2.2646 - val_accuracy: 0.2449
Epoch 70/500
13/13 [==============================] - 0s 24ms/step - loss: 1.9280 - accuracy: 0.3385 - val_loss: 2.2616 - val_accuracy: 0.2551
Epoch 71/500
13/13 [==============================] - 0s 23ms/step - loss: 1.9472 - accuracy: 0.3256 - val_loss: 2.2387 - val_accuracy: 0.2347
Epoch 72/500
13/13 [==============================] - 0s 23ms/step - loss: 1.8902 - accuracy: 0.3590 - val_loss: 2.2287 - val_accuracy: 0.2755
Epoch 73/500
13/13 [==============================] - 0s 24ms/step - loss: 1.8828 - accuracy: 0.3667 - val_loss: 2.1915 - val_accuracy: 0.3061
Epoch 74/500
13/13 [==============================] - 0s 25ms/step - loss: 1.8074 - accuracy: 0.4103 - val_loss: 2.1825 - val_accuracy: 0.2857
Epoch 75/500
13/13 [==============================] - 0s 26ms/step - loss: 1.8094 - accuracy: 0.3769 - val_loss: 2.1564 - val_accuracy: 0.2959
Epoch 76/500
13/13 [==============================] - 0s 21ms/step - loss: 1.8007 - accuracy: 0.3744 - val_loss: 2.1743 - val_accuracy: 0.2857
Epoch 77/500
13/13 [==============================] - 1s 48ms/step - loss: 1.7847 - accuracy: 0.4179 - val_loss: 2.1379 - val_accuracy: 0.3265
Epoch 78/500
13/13 [==============================] - 1s 80ms/step - loss: 1.8497 - accuracy: 0.3821 - val_loss: 2.1537 - val_accuracy: 0.3061
Epoch 79/500
13/13 [==============================] - 1s 51ms/step - loss: 1.7467 - accuracy: 0.4051 - val_loss: 2.1690 - val_accuracy: 0.2551
Epoch 80/500
13/13 [==============================] - 0s 20ms/step - loss: 1.7692 - accuracy: 0.4103 - val_loss: 2.1556 - val_accuracy: 0.3061
Epoch 81/500
13/13 [==============================] - 0s 21ms/step - loss: 1.7852 - accuracy: 0.3974 - val_loss: 2.1584 - val_accuracy: 0.2755
Epoch 82/500
13/13 [==============================] - 0s 21ms/step - loss: 1.7182 - accuracy: 0.4256 - val_loss: 2.1343 - val_accuracy: 0.2653
Epoch 83/500
13/13 [==============================] - 0s 21ms/step - loss: 1.6684 - accuracy: 0.4462 - val_loss: 2.1305 - val_accuracy: 0.2857
Epoch 84/500
13/13 [==============================] - 0s 20ms/step - loss: 1.7303 - accuracy: 0.4359 - val_loss: 2.1961 - val_accuracy: 0.2755
Epoch 85/500
13/13 [==============================] - 0s 20ms/step - loss: 1.6624 - accuracy: 0.4641 - val_loss: 2.1938 - val_accuracy: 0.2755
Epoch 86/500
13/13 [==============================] - 0s 20ms/step - loss: 1.7155 - accuracy: 0.4205 - val_loss: 2.1516 - val_accuracy: 0.2551
Epoch 87/500
13/13 [==============================] - 0s 20ms/step - loss: 1.6539 - accuracy: 0.4923 - val_loss: 2.1864 - val_accuracy: 0.2449
Epoch 88/500
13/13 [==============================] - 0s 21ms/step - loss: 1.7252 - accuracy: 0.4436 - val_loss: 2.2089 - val_accuracy: 0.2347
Epoch 89/500
13/13 [==============================] - 0s 20ms/step - loss: 1.6252 - accuracy: 0.4667 - val_loss: 2.2166 - val_accuracy: 0.2347
Epoch 90/500
13/13 [==============================] - 0s 19ms/step - loss: 1.6588 - accuracy: 0.4872 - val_loss: 2.2105 - val_accuracy: 0.2245
Epoch 91/500
13/13 [==============================] - 0s 23ms/step - loss: 1.6298 - accuracy: 0.4949 - val_loss: 2.2416 - val_accuracy: 0.2245
Epoch 92/500
13/13 [==============================] - 0s 20ms/step - loss: 1.6298 - accuracy: 0.5077 - val_loss: 2.2657 - val_accuracy: 0.2143
Epoch 93/500
13/13 [==============================] - 0s 20ms/step - loss: 1.5867 - accuracy: 0.5000 - val_loss: 2.2718 - val_accuracy: 0.2347
Epoch 94/500
13/13 [==============================] - 0s 37ms/step - loss: 1.6526 - accuracy: 0.4385 - val_loss: 2.2906 - val_accuracy: 0.2449
Epoch 95/500
13/13 [==============================] - 1s 95ms/step - loss: 1.5831 - accuracy: 0.5154 - val_loss: 2.2537 - val_accuracy: 0.2143
Epoch 96/500
13/13 [==============================] - 1s 53ms/step - loss: 1.5601 - accuracy: 0.5385 - val_loss: 2.2669 - val_accuracy: 0.2449
Epoch 97/500
13/13 [==============================] - 0s 24ms/step - loss: 1.5548 - accuracy: 0.4949 - val_loss: 2.2514 - val_accuracy: 0.2551
Epoch 98/500
13/13 [==============================] - 0s 23ms/step - loss: 1.5179 - accuracy: 0.5615 - val_loss: 2.2336 - val_accuracy: 0.2653
Epoch 99/500
13/13 [==============================] - 0s 22ms/step - loss: 1.5125 - accuracy: 0.5385 - val_loss: 2.1988 - val_accuracy: 0.2449
Epoch 100/500
13/13 [==============================] - 0s 21ms/step - loss: 1.4748 - accuracy: 0.5538 - val_loss: 2.1447 - val_accuracy: 0.2653
Epoch 101/500
13/13 [==============================] - 0s 38ms/step - loss: 1.5152 - accuracy: 0.5282 - val_loss: 2.1640 - val_accuracy: 0.2449
Epoch 102/500
13/13 [==============================] - 0s 24ms/step - loss: 1.5560 - accuracy: 0.5154 - val_loss: 2.2093 - val_accuracy: 0.2245
Epoch 103/500
13/13 [==============================] - 0s 22ms/step - loss: 1.5322 - accuracy: 0.5564 - val_loss: 2.2830 - val_accuracy: 0.1837
Epoch 104/500
13/13 [==============================] - 0s 22ms/step - loss: 1.4593 - accuracy: 0.5590 - val_loss: 2.3331 - val_accuracy: 0.2041
Epoch 105/500
13/13 [==============================] - 0s 23ms/step - loss: 1.3958 - accuracy: 0.5897 - val_loss: 2.3641 - val_accuracy: 0.2245
Epoch 106/500
13/13 [==============================] - 1s 90ms/step - loss: 1.4541 - accuracy: 0.5615 - val_loss: 2.3237 - val_accuracy: 0.2143
Epoch 107/500
13/13 [==============================] - 1s 70ms/step - loss: 1.4364 - accuracy: 0.5846 - val_loss: 2.3004 - val_accuracy: 0.2143
Epoch 108/500
13/13 [==============================] - 0s 21ms/step - loss: 1.4811 - accuracy: 0.5949 - val_loss: 2.2319 - val_accuracy: 0.2449
Epoch 109/500
13/13 [==============================] - 0s 21ms/step - loss: 1.4687 - accuracy: 0.6103 - val_loss: 2.2417 - val_accuracy: 0.2653
Epoch 110/500
13/13 [==============================] - 0s 23ms/step - loss: 1.4386 - accuracy: 0.6179 - val_loss: 2.2258 - val_accuracy: 0.2551
Epoch 111/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3294 - accuracy: 0.6205 - val_loss: 2.2665 - val_accuracy: 0.2551
Epoch 112/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3342 - accuracy: 0.6103 - val_loss: 2.2666 - val_accuracy: 0.2755
Epoch 113/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3992 - accuracy: 0.6051 - val_loss: 2.2512 - val_accuracy: 0.2653
Epoch 114/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3567 - accuracy: 0.6051 - val_loss: 2.2151 - val_accuracy: 0.2143
Epoch 115/500
13/13 [==============================] - 0s 23ms/step - loss: 1.4160 - accuracy: 0.5949 - val_loss: 2.2777 - val_accuracy: 0.2041
Epoch 116/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3763 - accuracy: 0.6103 - val_loss: 2.3112 - val_accuracy: 0.2041
Epoch 117/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3054 - accuracy: 0.6538 - val_loss: 2.2887 - val_accuracy: 0.2245
Epoch 118/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3460 - accuracy: 0.6641 - val_loss: 2.2390 - val_accuracy: 0.2245
Epoch 119/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3818 - accuracy: 0.6128 - val_loss: 2.2153 - val_accuracy: 0.2347
Epoch 120/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2647 - accuracy: 0.6897 - val_loss: 2.2312 - val_accuracy: 0.2347
Epoch 121/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2562 - accuracy: 0.6385 - val_loss: 2.2222 - val_accuracy: 0.2551
Epoch 122/500
13/13 [==============================] - 1s 75ms/step - loss: 1.2935 - accuracy: 0.6692 - val_loss: 2.2035 - val_accuracy: 0.2449
Epoch 123/500
13/13 [==============================] - 0s 27ms/step - loss: 1.3391 - accuracy: 0.6538 - val_loss: 2.1443 - val_accuracy: 0.2755
Epoch 124/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2928 - accuracy: 0.6359 - val_loss: 2.1838 - val_accuracy: 0.2959
Epoch 125/500
13/13 [==============================] - 0s 23ms/step - loss: 1.2028 - accuracy: 0.6846 - val_loss: 2.1947 - val_accuracy: 0.3265
Epoch 126/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2523 - accuracy: 0.6795 - val_loss: 2.2558 - val_accuracy: 0.3061
Epoch 127/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2985 - accuracy: 0.6308 - val_loss: 2.2920 - val_accuracy: 0.2857
Epoch 128/500
13/13 [==============================] - 0s 21ms/step - loss: 1.1773 - accuracy: 0.7154 - val_loss: 2.3695 - val_accuracy: 0.2653
Epoch 129/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2422 - accuracy: 0.6795 - val_loss: 2.4326 - val_accuracy: 0.2449
Epoch 130/500
13/13 [==============================] - 0s 21ms/step - loss: 1.3002 - accuracy: 0.6385 - val_loss: 2.4472 - val_accuracy: 0.2347
Epoch 131/500
13/13 [==============================] - 0s 24ms/step - loss: 1.2499 - accuracy: 0.6744 - val_loss: 2.4181 - val_accuracy: 0.2347
Epoch 132/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2307 - accuracy: 0.6872 - val_loss: 2.3497 - val_accuracy: 0.2143
Epoch 133/500
13/13 [==============================] - 0s 26ms/step - loss: 1.1302 - accuracy: 0.7051 - val_loss: 2.3223 - val_accuracy: 0.2245
Epoch 134/500
13/13 [==============================] - 1s 89ms/step - loss: 1.1255 - accuracy: 0.7282 - val_loss: 2.3866 - val_accuracy: 0.2143
Epoch 135/500
13/13 [==============================] - 1s 68ms/step - loss: 1.1838 - accuracy: 0.7128 - val_loss: 2.3693 - val_accuracy: 0.2347
Epoch 136/500
13/13 [==============================] - 0s 21ms/step - loss: 1.2108 - accuracy: 0.7256 - val_loss: 2.3495 - val_accuracy: 0.2143
Epoch 137/500
13/13 [==============================] - 0s 21ms/step - loss: 1.1629 - accuracy: 0.7103 - val_loss: 2.4158 - val_accuracy: 0.2245
Epoch 138/500
13/13 [==============================] - 0s 21ms/step - loss: 1.0984 - accuracy: 0.7256 - val_loss: 2.3713 - val_accuracy: 0.2041
Epoch 139/500
13/13 [==============================] - 0s 23ms/step - loss: 1.0950 - accuracy: 0.7538 - val_loss: 2.3522 - val_accuracy: 0.2347
Epoch 140/500

In [317]:
# Evaluar el modelo
loss_test, accuracy_test = model.evaluate(X_test, y_test)
print(f'Loss: {loss_test}, Accuracy: {accuracy_test}')

2/2 [==============================] - 0s 8ms/step - loss: 3.0726 - accuracy: 0.2000
Loss: 3.0725929737091064, Accuracy: 0.20000000298023224