# Libraries

In [1]:
import pandas as pd
import numpy as np

# Promoters

In [2]:
df_promoters = pd.read_csv("dataframes/19_df_sigma70_phiscore.csv")

In [4]:
df_promoters = pd.read_csv("dataframes/12_regulonDB_parsed_and_checked_locusTag_TF.csv")

In [3]:
df_promoters.head(2)

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,...,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced,locus tag,activator,repressor
0,RDBECOLIOPC00001,ispDF,reverse,RDBECOLITUC01454,ispDF,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,...,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT,b1032,1.0,0.0

In [5]:
df_promoters = df_promoters.dropna(subset="Promoter sequence")

In [6]:
df_promoters = df_promoters.drop_duplicates(subset="Promoter sequence", keep="first")

In [7]:
df_promoters

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,...,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced,locus tag,phisite score
0,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,...,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT,b1032,6.63
1,RDBECOLIOPC00006,folA,forward,RDBECOLITUC02413,folA,folA,RDBECOLIPMC03546,folAp,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,...,49768.0,GTCGAC,49787.0,49792.0,TATAGT,W,GACGGTTTACGCTTTACG,GTCGACGACGGTTTACGCTTTACGTATAGT,b0048,5.68
2,RDBECOLIOPC00013,argD,reverse,RDBECOLITUC03147,argD,argD,RDBECOLIPMC03433,argDp,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,...,3490258.0,TTGCCA,3490228.0,3490233.0,TATTTT,W,TTTAGTGATTTTTTATGCA,TTGCCATTTAGTGATTTTTTATGCATATTTT,b3359,6.63
3,RDBECOLIOPC00017,proL,forward,RDBECOLITUC03512,proL,proL,RDBECOLIPMC03856,proLp,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,...,2286174.0,TTGCAA,2286194.0,2286199.0,TATTAG,W,TCGGTGTGGAAAACGGTAG,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,b2189,5.56
4,RDBECOLIOPC00019,cusCFBA,forward,RDBECOLITUC01807,cusCFBA,cusC,RDBECOLIPMC00440,cusCp,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,...,595539.0,GTCACC,595561.0,595566.0,TAAAGT,S,GGAAAATCAGAGCCTGGCGAG,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,b0572,2.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01708,pstS,pstS,RDBECOLIPMC03521,pstSp,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,...,3911608.0,TTACAT,3911576.0,3911581.0,TATTTT,S,ATAACTGTCACCTGTTTGTCC,TTACATATAACTGTCACCTGTTTGTCCTATTTT,b3728,3.14
1119,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01710,pstB-phoU,pstB,RDBECOLIPMC00234,pstBp3,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,...,3908479.0,TTTTTG,3908453.0,3908458.0,AACACT,W,ACTCTGTACACGGTT,TTTTTGACTCTGTACACGGTTAACACT,b3725,3.43
1120,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01907,pstCAB-phoU,pstC,RDBECOLIPMC00511,pstCp,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,...,3910580.0,CTGGAT,3910552.0,3910557.0,TAGTGT,S,TACGCCAGCCTGCCGGA,CTGGATTACGCCAGCCTGCCGGATAGTGT,b3727,2.78
1121,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01908,pstB-phoU,pstB,RDBECOLIPMC00512,pstBp1,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,...,3908589.0,TTCTGG,3908561.0,3908566.0,AAGAAT,S,CGCGCGTTGTTTTTGCG,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,b3725,4.19
1122,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC01909,phoU,phoU,RDBECOLIPMC00513,phoUp,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,...,3907702.0,CGGCGT,3907672.0,3907677.0,GATTGA,S,TTATGTACCTGGGCGAATT,CGGCGTTTATGTACCTGGGCGAATTGATTGA,b3724,2.96

In [8]:
df_promoters_reduced = df_promoters[["Promoter ID", 
                                    "TU first gene",
                                    "locus tag",
                                    "Sigma factor",
                                    "Promoter sequence",
                                    "Promoter confidence",
                                    "promoter sequence reduced",
                                    # "activator",
                                    # "repressor",
                                    "phisite score"]]

In [9]:
df_promoters_reduced = df_promoters_reduced.dropna(subset="locus tag")

In [10]:
df_promoters_reduced

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score
0,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,6.63
1,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68
2,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63
3,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,5.56
4,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95
...,...,...,...,...,...,...,...,...
1117,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14
1119,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43
1120,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78
1121,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19
1122,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96

# Gene Expression

In [11]:
df_geneExpression = pd.read_csv("dataframes/9_geneExpressionK12.csv")

In [12]:
df_geneExpression.drop(columns="b4711", inplace=True)

In [13]:
df_geneExpression_statistics = pd.DataFrame({"locus tag" : df_geneExpression.drop(columns="index").columns,
                                            "std_dev" : df_geneExpression.drop(columns="index").std().values,
                                            "cv" : df_geneExpression.drop(columns="index").std().values / df_geneExpression.drop(columns="index").mean().values})

In [14]:
df_geneExpression_statistics

     locus tag   std_dev        cv
0        b0002  1.922467  0.212390
1        b0003  1.635333  0.183417
2        b0004  1.631041  0.186248
3        b0005  1.247063  0.208016
4        b0006  0.607906  0.101112
...        ...       ...       ...
4251     b4747  1.008434  1.046580
4252     b4748  2.005360  0.983759
4253     b4751  0.780246  0.155568
4254     b4755  1.791341  1.076811
4255     b4756  1.394692  0.278688

[4256 rows x 3 columns]

In [51]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df_geneExpression_statistics[['cv']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df_geneExpression_statistics['cluster cv'] = kmeans.labels_

In [52]:
threshold_low = df_geneExpression_statistics['cv'].quantile(0.33)
threshold_high = df_geneExpression_statistics['cv'].quantile(0.66)

print(f"Umbral bajo (percentil 33): {threshold_low}")
print(f"Umbral alto (percentil 66): {threshold_high}")

# Función para categorizar en función de CV
def categorize_cv(cv, low, high):
    if cv <= low:
        return 'bajo'
    elif cv <= high:
        return 'medio'
    else:
        return 'alto'

# Aplicar la función de categorización
df_geneExpression_statistics['cv_category'] = df_geneExpression_statistics['cv'].apply(categorize_cv, args=(threshold_low, threshold_high))

Umbral bajo (percentil 33): 0.13352700194639075
Umbral alto (percentil 66): 0.2923655941753293

In [53]:
df_geneExpression_statistics

     locus tag   std_dev        cv  cluster cv cv_category
0        b0002  1.922467  0.212390           1       medio
1        b0003  1.635333  0.183417           1       medio
2        b0004  1.631041  0.186248           1       medio
3        b0005  1.247063  0.208016           1       medio
4        b0006  0.607906  0.101112           1        bajo
...        ...       ...       ...         ...         ...
4251     b4747  1.008434  1.046580           2        alto
4252     b4748  2.005360  0.983759           2        alto
4253     b4751  0.780246  0.155568           1       medio
4254     b4755  1.791341  1.076811           2        alto
4255     b4756  1.394692  0.278688           1       medio

[4256 rows x 5 columns]

In [54]:
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==0].min()["cv"])
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==0].max()["cv"])

0.31604692744817087
0.814590230823067

In [55]:
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==1].min()["cv"])
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==1].max()["cv"])

0.02762727380769907
0.3157421819509239

In [56]:
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==2].min()["cv"])
print(df_geneExpression_statistics[df_geneExpression_statistics["cluster cv"]==2].max()["cv"])

0.823843868737295
3.2495314971234235

In [57]:
# Rename of K-means clusters

df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: "low" if x==1 else x)
df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: "medium" if x==0 else x)
df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: "high" if x==2 else x)

df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: 0 if x=="low" else x)
df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: 1 if x=="medium" else x)
df_geneExpression_statistics["cluster cv"] = df_geneExpression_statistics["cluster cv"].apply(lambda x: 2 if x=="high" else x)

In [58]:
df_geneExpression_statistics

     locus tag   std_dev        cv  cluster cv cv_category
0        b0002  1.922467  0.212390           0       medio
1        b0003  1.635333  0.183417           0       medio
2        b0004  1.631041  0.186248           0       medio
3        b0005  1.247063  0.208016           0       medio
4        b0006  0.607906  0.101112           0        bajo
...        ...       ...       ...         ...         ...
4251     b4747  1.008434  1.046580           2        alto
4252     b4748  2.005360  0.983759           2        alto
4253     b4751  0.780246  0.155568           0       medio
4254     b4755  1.791341  1.076811           2        alto
4255     b4756  1.394692  0.278688           0       medio

[4256 rows x 5 columns]

# Subsets

## Low and medium CV and Sigma70

### Low and medium CV

In [71]:
## genes with low and medium CV

genes_subset = list(df_geneExpression_statistics[(df_geneExpression_statistics["cluster cv"]==0) | (df_geneExpression_statistics["cluster cv"]==1)]["locus tag"].values)

df_geneExpression_subset = df_geneExpression[genes_subset]

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0011,...,b4725,b4729,b4735,b4737,b4740,b4742,b4743,b4744,b4751,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,1.635656,...,6.981666,3.414025,9.433344,2.344123,3.437496,7.137727,5.265698,2.779449,5.559890,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,2.170886,...,6.902602,3.460030,9.368557,1.600958,3.260379,7.253462,4.894757,4.213492,5.638994,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,2.767142,...,6.578612,2.402150,8.036826,2.298669,3.249260,5.125056,6.477672,3.241691,4.309421,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,2.238453,...,6.472961,1.748576,7.634247,2.155117,3.445236,5.354380,6.569912,5.600386,4.301115,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,2.014957,...,6.917032,2.256099,9.170651,0.821856,2.903060,6.391959,5.558479,3.654893,5.117821,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,2.506075,...,7.017253,3.074976,9.090410,1.327401,3.780517,4.114063,5.924942,4.111593,4.735521,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,1.266167,...,8.225574,2.697835,9.999464,1.527276,3.669952,5.135280,5.460251,9.114042,5.723015,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,2.065161,...,7.722098,2.597704,10.095544,0.824001,3.296394,4.836078,4.364785,9.397053,5.609553,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,1.959288,...,7.218039,2.607075,8.365892,2.969313,1.699004,3.483538,2.837202,1.589891,5.107107,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,2.538160,...,7.106772,2.496721,9.360890,2.691794,2.923249,4.385632,3.961997,3.345654,5.259949,4.979692

In [72]:
## median values of the expression of the selected genes

df_geneExpression_subset_medians = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "median": df_geneExpression_subset.median().values})
df_geneExpression_subset_medians

     locus tag    median
0        b0002  9.852221
1        b0003  9.576424
2        b0004  9.467885
3        b0005  6.186119
4        b0006  6.235849
...        ...       ...
4087     b4742  4.587304
4088     b4743  5.064567
4089     b4744  3.796092
4090     b4751  5.064633
4091     b4756  4.800457

[4092 rows x 2 columns]

### Sigma70 promoters

In [73]:
df = df_promoters_reduced[df_promoters_reduced["Sigma factor"]=="sigma70"]

In [74]:
## drop duplicated in locus tag

df[df.duplicated(subset="locus tag", keep=False)].index

df= df.drop(df[df.duplicated(subset="locus tag", keep=False)].index)

In [75]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor
1,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,1.0,0.0
5,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0
12,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0
16,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,1.0,0.0
18,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0
...,...,...,...,...,...,...,...,...,...
3685,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0
3698,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0
3703,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0
3706,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0
3708,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0

In [76]:
df = pd.merge(df, df_geneExpression_subset_medians, on="locus tag")

In [77]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444
...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496

In [78]:
df = pd.merge(df, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [79]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0
...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0

In [80]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df[['median']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df['cluster median'] = kmeans.labels_

In [81]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,1
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,2
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,1
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,1
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,1

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Promoter ID                620 non-null    object
 1   TU first gene              620 non-null    object
 2   locus tag                  620 non-null    object
 3   Sigma factor               620 non-null    object
 4   Promoter sequence          620 non-null    object
 5   Promoter confidence        620 non-null    object
 6   promoter sequence reduced  588 non-null    object
 7   activator                  620 non-null    float64
 8   repressor                  620 non-null    float64
 9   median                     620 non-null    float64
 10  cluster cv                 620 non-null    int64
 11  cluster median             620 non-null    int32
dtypes: float64(3), int32(1), int64(1), object(7)
memory usage: 55.8+ KB

In [83]:
print(df[df["cluster median"]==0]["median"].min())
print(df[df["cluster median"]==0]["median"].max())
print(df[df["cluster median"]==1]["median"].min())
print(df[df["cluster median"]==1]["median"].max())
print(df[df["cluster median"]==2]["median"].min())
print(df[df["cluster median"]==2]["median"].max())

0.59990764
4.371548000000001
4.412948
7.4265336
7.4357735
13.454511

In [34]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,1
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,2
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,1
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,1
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,1

### Save dataset

In [35]:
df.to_csv("dataframes/14_df_sigma70_low_medium_cv.csv", index=False)

## Low CV and Sigma70

### Low CV

In [36]:
## genes with low and medium CV

genes_subset = list(df_geneExpression_statistics[(df_geneExpression_statistics["cluster cv"]==0)]["locus tag"].values)

df_geneExpression_subset = df_geneExpression[genes_subset]

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0014,...,b4688,b4696,b4705,b4709,b4725,b4729,b4735,b4740,b4751,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,9.562502,...,5.220591,2.104056,8.383966,3.497895,6.981666,3.414025,9.433344,3.437496,5.559890,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,9.578656,...,5.085797,2.015978,8.058668,3.194701,6.902602,3.460030,9.368557,3.260379,5.638994,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,10.427753,...,3.995560,3.184660,7.283006,3.230428,6.578612,2.402150,8.036826,3.249260,4.309421,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,10.422943,...,4.375760,3.215085,7.407578,2.914955,6.472961,1.748576,7.634247,3.445236,4.301115,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,9.344848,...,5.053407,1.744607,7.960806,3.306709,6.917032,2.256099,9.170651,2.903060,5.117821,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,10.091426,...,4.010115,4.086763,7.296120,2.009780,7.017253,3.074976,9.090410,3.780517,4.735521,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,8.560539,...,4.604851,3.121149,10.134403,4.725013,8.225574,2.697835,9.999464,3.669952,5.723015,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,8.611441,...,3.753409,3.074978,9.674207,4.499990,7.722098,2.597704,10.095544,3.296394,5.609553,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,10.236332,...,3.543382,3.389820,6.554142,2.580619,7.218039,2.607075,8.365892,1.699004,5.107107,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,10.272300,...,3.512772,3.537683,6.739833,2.617764,7.106772,2.496721,9.360890,2.923249,5.259949,4.979692

In [37]:
## median values of the expression of the selected genes

df_geneExpression_subset_medians = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "median": df_geneExpression_subset.median().values})
df_geneExpression_subset_medians

     locus tag    median
0        b0002  9.852221
1        b0003  9.576424
2        b0004  9.467885
3        b0005  6.186119
4        b0006  6.235849
...        ...       ...
2940     b4729  2.621913
2941     b4735  7.705439
2942     b4740  3.332853
2943     b4751  5.064633
2944     b4756  4.800457

[2945 rows x 2 columns]

### Sigma70 promoters

In [38]:
df_sigma70 = df_promoters_reduced[df_promoters_reduced["Sigma factor"]=="sigma70"]

In [39]:
## drop duplicated in locus tag

df_sigma70[df_sigma70.duplicated(subset="locus tag", keep=False)].index

df_sigma70= df_sigma70.drop(df_sigma70[df_sigma70.duplicated(subset="locus tag", keep=False)].index)

In [40]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor
1,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,1.0,0.0
5,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0
12,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0
16,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,1.0,0.0
18,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0
...,...,...,...,...,...,...,...,...,...
3685,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0
3698,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0
3703,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0
3706,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0
3708,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0

In [41]:
df_sigma70 = pd.merge(df_sigma70, df_geneExpression_subset_medians, on="locus tag")

In [42]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328
2,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637
3,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444
4,RDBECOLIPMC03836,yhfA,b3356,sigma70,gcacggtaatgtgacgtcctttgcatacatgcagtacatcaatgta...,S,ATGCAGTACATCAATGTATTACTGTAGCAT,0.0,0.0,7.549638
...,...,...,...,...,...,...,...,...,...,...
484,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626
485,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884
486,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474
487,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745
488,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496

In [43]:
df_sigma70 = pd.merge(df_sigma70, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [44]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0
2,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0
3,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0
4,RDBECOLIPMC03836,yhfA,b3356,sigma70,gcacggtaatgtgacgtcctttgcatacatgcagtacatcaatgta...,S,ATGCAGTACATCAATGTATTACTGTAGCAT,0.0,0.0,7.549638,0
...,...,...,...,...,...,...,...,...,...,...,...
484,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0
485,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0
486,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0
487,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0
488,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0

In [45]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df_sigma70[['median']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df_sigma70['cluster median'] = kmeans.labels_

In [46]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,0
2,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,2
3,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,1
4,RDBECOLIPMC03836,yhfA,b3356,sigma70,gcacggtaatgtgacgtcctttgcatacatgcagtacatcaatgta...,S,ATGCAGTACATCAATGTATTACTGTAGCAT,0.0,0.0,7.549638,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
484,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,2
485,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,0
486,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,0
487,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,2
488,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,0

In [47]:
df_sigma70.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Promoter ID                489 non-null    object
 1   TU first gene              489 non-null    object
 2   locus tag                  489 non-null    object
 3   Sigma factor               489 non-null    object
 4   Promoter sequence          489 non-null    object
 5   Promoter confidence        489 non-null    object
 6   promoter sequence reduced  463 non-null    object
 7   activator                  489 non-null    float64
 8   repressor                  489 non-null    float64
 9   median                     489 non-null    float64
 10  cluster cv                 489 non-null    int64
 11  cluster median             489 non-null    int32
dtypes: float64(3), int32(1), int64(1), object(7)
memory usage: 44.1+ KB

In [48]:
print(df_sigma70[df_sigma70["cluster median"]==0]["median"].min())
print(df_sigma70[df_sigma70["cluster median"]==0]["median"].max())
print(df_sigma70[df_sigma70["cluster median"]==1]["median"].min())
print(df_sigma70[df_sigma70["cluster median"]==1]["median"].max())
print(df_sigma70[df_sigma70["cluster median"]==2]["median"].min())
print(df_sigma70[df_sigma70["cluster median"]==2]["median"].max())

5.8214118
8.526156
8.5355155
13.454511
1.6764776000000001
5.78272065

In [50]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,0
2,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,2
3,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,1
4,RDBECOLIPMC03836,yhfA,b3356,sigma70,gcacggtaatgtgacgtcctttgcatacatgcagtacatcaatgta...,S,ATGCAGTACATCAATGTATTACTGTAGCAT,0.0,0.0,7.549638,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
484,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,2
485,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,0
486,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,0
487,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,2
488,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,0

### Save dataset

In [36]:
df_sigma70.to_csv("dataframes/15_df_sigma70_low_cv.csv", index=False)

## Low and medium CV and Sigma70, K-means 5

### Low and medium CV

In [171]:
## genes with low and medium CV

genes_subset = list(df_geneExpression_statistics[(df_geneExpression_statistics["cluster cv"]==0) | (df_geneExpression_statistics["cluster cv"]==1)]["locus tag"].values)

df_geneExpression_subset = df_geneExpression[genes_subset]

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0011,...,b4725,b4729,b4735,b4737,b4740,b4742,b4743,b4744,b4751,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,1.635656,...,6.981666,3.414025,9.433344,2.344123,3.437496,7.137727,5.265698,2.779449,5.559890,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,2.170886,...,6.902602,3.460030,9.368557,1.600958,3.260379,7.253462,4.894757,4.213492,5.638994,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,2.767142,...,6.578612,2.402150,8.036826,2.298669,3.249260,5.125056,6.477672,3.241691,4.309421,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,2.238453,...,6.472961,1.748576,7.634247,2.155117,3.445236,5.354380,6.569912,5.600386,4.301115,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,2.014957,...,6.917032,2.256099,9.170651,0.821856,2.903060,6.391959,5.558479,3.654893,5.117821,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,2.506075,...,7.017253,3.074976,9.090410,1.327401,3.780517,4.114063,5.924942,4.111593,4.735521,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,1.266167,...,8.225574,2.697835,9.999464,1.527276,3.669952,5.135280,5.460251,9.114042,5.723015,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,2.065161,...,7.722098,2.597704,10.095544,0.824001,3.296394,4.836078,4.364785,9.397053,5.609553,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,1.959288,...,7.218039,2.607075,8.365892,2.969313,1.699004,3.483538,2.837202,1.589891,5.107107,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,2.538160,...,7.106772,2.496721,9.360890,2.691794,2.923249,4.385632,3.961997,3.345654,5.259949,4.979692

In [172]:
## median values of the expression of the selected genes

df_geneExpression_subset_medians = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "median": df_geneExpression_subset.median().values})
df_geneExpression_subset_medians

     locus tag    median
0        b0002  9.852221
1        b0003  9.576424
2        b0004  9.467885
3        b0005  6.186119
4        b0006  6.235849
...        ...       ...
4087     b4742  4.587304
4088     b4743  5.064567
4089     b4744  3.796092
4090     b4751  5.064633
4091     b4756  4.800457

[4092 rows x 2 columns]

### Sigma70 promoters

In [173]:
df_sigma70 = df_promoters_reduced[df_promoters_reduced["Sigma factor"]=="sigma70"]

In [174]:
## drop duplicated in locus tag

df_sigma70[df_sigma70.duplicated(subset="locus tag", keep=False)].index

df_sigma70= df_sigma70.drop(df_sigma70[df_sigma70.duplicated(subset="locus tag", keep=False)].index)

In [175]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor
1,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,1.0,0.0
5,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0
12,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0
16,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,1.0,0.0
18,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0
...,...,...,...,...,...,...,...,...,...
3685,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0
3698,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0
3703,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0
3706,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0
3708,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0

In [176]:
df_sigma70 = pd.merge(df_sigma70, df_geneExpression_subset_medians, on="locus tag")

In [177]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444
...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496

In [178]:
df_sigma70 = pd.merge(df_sigma70, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [179]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0
...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0

In [191]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df_sigma70[['median']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=5, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df_sigma70['cluster median'] = kmeans.labels_

In [181]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,4
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,3
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,4
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,1
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,3
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,1

In [ ]:
df_sigma70.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Promoter ID                620 non-null    object
 1   TU first gene              620 non-null    object
 2   locus tag                  620 non-null    object
 3   Sigma factor               620 non-null    object
 4   Promoter sequence          620 non-null    object
 5   Promoter confidence        620 non-null    object
 6   promoter sequence reduced  588 non-null    object
 7   activator                  620 non-null    float64
 8   repressor                  620 non-null    float64
 9   median                     620 non-null    float64
 10  cluster cv                 620 non-null    int64
 11  cluster median             620 non-null    int32
dtypes: float64(3), int32(1), int64(1), object(7)
memory usage: 55.8+ KB

In [192]:
print("0", df_sigma70[df_sigma70["cluster median"]==0]["median"].min())
print("0", df_sigma70[df_sigma70["cluster median"]==0]["median"].max())
print("1", df_sigma70[df_sigma70["cluster median"]==1]["median"].min())
print("1", df_sigma70[df_sigma70["cluster median"]==1]["median"].max())
print("2", df_sigma70[df_sigma70["cluster median"]==2]["median"].min())
print("2", df_sigma70[df_sigma70["cluster median"]==2]["median"].max())
print("3", df_sigma70[df_sigma70["cluster median"]==3]["median"].min())
print("3", df_sigma70[df_sigma70["cluster median"]==3]["median"].max())
print("4", df_sigma70[df_sigma70["cluster median"]==4]["median"].min())
print("4", df_sigma70[df_sigma70["cluster median"]==4]["median"].max())

0 0.59990764
0 3.48862555
1 5.602815
1 7.3036315
2 9.4216865
2 13.454511
3 3.5221066
3 5.57175395
4 7.313638
4 9.317854

In [193]:
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: "a" if x==0 else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: "b" if x==3 else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: "c" if x==1 else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: "d" if x==4 else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: "e" if x==2 else x)

In [194]:

df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: 0 if x=="a" else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: 1 if x=="b" else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: 2 if x=="c" else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: 3 if x=="d"else x)
df_sigma70["cluster median"] = df_sigma70["cluster median"].apply(lambda x: 4 if x=="e" else x)

In [195]:
print("0", df_sigma70[df_sigma70["cluster median"]==0]["median"].min())
print("0", df_sigma70[df_sigma70["cluster median"]==0]["median"].max())
print("1", df_sigma70[df_sigma70["cluster median"]==1]["median"].min())
print("1", df_sigma70[df_sigma70["cluster median"]==1]["median"].max())
print("2", df_sigma70[df_sigma70["cluster median"]==2]["median"].min())
print("2", df_sigma70[df_sigma70["cluster median"]==2]["median"].max())
print("3", df_sigma70[df_sigma70["cluster median"]==3]["median"].min())
print("3", df_sigma70[df_sigma70["cluster median"]==3]["median"].max())
print("4", df_sigma70[df_sigma70["cluster median"]==4]["median"].min())
print("4", df_sigma70[df_sigma70["cluster median"]==4]["median"].max())

0 0.59990764
0 3.48862555
1 3.5221066
1 5.57175395
2 5.602815
2 7.3036315
3 7.313638
3 9.317854
4 9.4216865
4 13.454511

In [196]:
df_sigma70

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,2
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,3
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.930068,1,2
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.656637,0,1
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.126444,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.699884,0,3
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,2
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,1
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,2

### Save dataset

In [197]:
df_sigma70.to_csv("dataframes/16_df_sigma70_low_medium_cv_k-means5.csv", index=False)

## Low and medium CV and all sigma and K-means 5

### Low and medium CV

In [259]:
## genes with low and medium CV

genes_subset = list(df_geneExpression_statistics[(df_geneExpression_statistics["cluster cv"]==0) | (df_geneExpression_statistics["cluster cv"]==1)]["locus tag"].values)

df_geneExpression_subset = df_geneExpression[genes_subset]

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0011,...,b4725,b4729,b4735,b4737,b4740,b4742,b4743,b4744,b4751,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,1.635656,...,6.981666,3.414025,9.433344,2.344123,3.437496,7.137727,5.265698,2.779449,5.559890,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,2.170886,...,6.902602,3.460030,9.368557,1.600958,3.260379,7.253462,4.894757,4.213492,5.638994,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,2.767142,...,6.578612,2.402150,8.036826,2.298669,3.249260,5.125056,6.477672,3.241691,4.309421,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,2.238453,...,6.472961,1.748576,7.634247,2.155117,3.445236,5.354380,6.569912,5.600386,4.301115,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,2.014957,...,6.917032,2.256099,9.170651,0.821856,2.903060,6.391959,5.558479,3.654893,5.117821,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,2.506075,...,7.017253,3.074976,9.090410,1.327401,3.780517,4.114063,5.924942,4.111593,4.735521,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,1.266167,...,8.225574,2.697835,9.999464,1.527276,3.669952,5.135280,5.460251,9.114042,5.723015,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,2.065161,...,7.722098,2.597704,10.095544,0.824001,3.296394,4.836078,4.364785,9.397053,5.609553,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,1.959288,...,7.218039,2.607075,8.365892,2.969313,1.699004,3.483538,2.837202,1.589891,5.107107,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,2.538160,...,7.106772,2.496721,9.360890,2.691794,2.923249,4.385632,3.961997,3.345654,5.259949,4.979692

In [260]:
## median values of the expression of the selected genes

df_geneExpression_subset_medians = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "median": df_geneExpression_subset.median().values})
df_geneExpression_subset_medians

     locus tag    median
0        b0002  9.852221
1        b0003  9.576424
2        b0004  9.467885
3        b0005  6.186119
4        b0006  6.235849
...        ...       ...
4087     b4742  4.587304
4088     b4743  5.064567
4089     b4744  3.796092
4090     b4751  5.064633
4091     b4756  4.800457

[4092 rows x 2 columns]

### Sigma promoters

In [261]:
df = df_promoters_reduced

In [262]:
## drop duplicated in locus tag

df[df.duplicated(subset="locus tag", keep=False)].index

df= df.drop(df[df.duplicated(subset="locus tag", keep=False)].index)

In [263]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor
1,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,1.0,0.0
5,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0
6,RDBECOLIPMC00539,ybaB,b0471,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,S,CAACTTTCGCTACCAAAACTGGTCGAA,0.0,0.0
9,RDBECOLIPMC03716,ytjB,b4387,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,S,NaN,1.0,0.0
11,RDBECOLIPMC00555,yohJ,b2141,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,W,NaN,0.0,1.0
...,...,...,...,...,...,...,...,...,...
3681,RDBECOLIPMC02961,rimP,b3170,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,C,TTCCCTTAGAGTCCTTTTTCAAATATACT,1.0,1.0
3685,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0
3703,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0
3706,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0
3708,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0

In [264]:
df = pd.merge(df, df_geneExpression_subset_medians, on="locus tag")

In [265]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292
1,RDBECOLIPMC00539,ybaB,b0471,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,S,CAACTTTCGCTACCAAAACTGGTCGAA,0.0,0.0,8.893792
2,RDBECOLIPMC03716,ytjB,b4387,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,S,NaN,1.0,0.0,4.633977
3,RDBECOLIPMC00555,yohJ,b2141,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,W,NaN,0.0,1.0,4.046088
4,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328
...,...,...,...,...,...,...,...,...,...,...
1067,RDBECOLIPMC02961,rimP,b3170,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,C,TTCCCTTAGAGTCCTTTTTCAAATATACT,1.0,1.0,8.423423
1068,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626
1069,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474
1070,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745
1071,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496

In [266]:
df = pd.merge(df, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [267]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0
1,RDBECOLIPMC00539,ybaB,b0471,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,S,CAACTTTCGCTACCAAAACTGGTCGAA,0.0,0.0,8.893792,0
2,RDBECOLIPMC03716,ytjB,b4387,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,S,NaN,1.0,0.0,4.633977,0
3,RDBECOLIPMC00555,yohJ,b2141,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,W,NaN,0.0,1.0,4.046088,0
4,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0
...,...,...,...,...,...,...,...,...,...,...,...
1067,RDBECOLIPMC02961,rimP,b3170,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,C,TTCCCTTAGAGTCCTTTTTCAAATATACT,1.0,1.0,8.423423,0
1068,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0
1069,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0
1070,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0
1071,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0

In [269]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df[['median']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=5, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df['cluster median'] = kmeans.labels_

In [270]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv,cluster median
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0,0
1,RDBECOLIPMC00539,ybaB,b0471,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,S,CAACTTTCGCTACCAAAACTGGTCGAA,0.0,0.0,8.893792,0,2
2,RDBECOLIPMC03716,ytjB,b4387,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,S,NaN,1.0,0.0,4.633977,0,4
3,RDBECOLIPMC00555,yohJ,b2141,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,W,NaN,0.0,1.0,4.046088,0,4
4,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1067,RDBECOLIPMC02961,rimP,b3170,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,C,TTCCCTTAGAGTCCTTTTTCAAATATACT,1.0,1.0,8.423423,0,2
1068,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0,4
1069,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0,0
1070,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0,4
1071,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0,0

In [271]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072 entries, 0 to 1071
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Promoter ID                1072 non-null   object
 1   TU first gene              1072 non-null   object
 2   locus tag                  1072 non-null   object
 3   Sigma factor               728 non-null    object
 4   Promoter sequence          1072 non-null   object
 5   Promoter confidence        1072 non-null   object
 6   promoter sequence reduced  683 non-null    object
 7   activator                  1072 non-null   float64
 8   repressor                  1072 non-null   float64
 9   median                     1072 non-null   float64
 10  cluster cv                 1072 non-null   int64
 11  cluster median             1072 non-null   int32
dtypes: float64(3), int32(1), int64(1), object(7)
memory usage: 96.4+ KB

In [272]:
print("0", df[df["cluster median"]==0]["median"].min())
print("0", df[df["cluster median"]==0]["median"].max())
print("1", df[df["cluster median"]==1]["median"].min())
print("1", df[df["cluster median"]==1]["median"].max())
print("2", df[df["cluster median"]==2]["median"].min())
print("2", df[df["cluster median"]==2]["median"].max())
print("3", df[df["cluster median"]==3]["median"].min())
print("3", df[df["cluster median"]==3]["median"].max())
print("4", df[df["cluster median"]==4]["median"].min())
print("4", df[df["cluster median"]==4]["median"].max())

0 5.26583
0 7.097891499999999
1 0.50746522
1 3.1811998
2 7.1013374
2 9.267637
3 9.288853
3 12.8823685
4 3.2185988
4 5.2571595

In [273]:
df["cluster median"] = df["cluster median"].apply(lambda x: "a" if x==1 else x)
df["cluster median"] = df["cluster median"].apply(lambda x: "b" if x==4 else x)
df["cluster median"] = df["cluster median"].apply(lambda x: "c" if x==0 else x)
df["cluster median"] = df["cluster median"].apply(lambda x: "d" if x==2 else x)
df["cluster median"] = df["cluster median"].apply(lambda x: "e" if x==3 else x)

In [274]:

df["cluster median"] = df["cluster median"].apply(lambda x: 0 if x=="a" else x)
df["cluster median"] = df["cluster median"].apply(lambda x: 1 if x=="b" else x)
df["cluster median"] = df["cluster median"].apply(lambda x: 2 if x=="c" else x)
df["cluster median"] = df["cluster median"].apply(lambda x: 3 if x=="d" else x)
df["cluster median"] = df["cluster median"].apply(lambda x: 4 if x=="e" else x)

In [275]:
print("0", df[df["cluster median"]==0]["median"].min())
print("0", df[df["cluster median"]==0]["median"].max())
print("1", df[df["cluster median"]==1]["median"].min())
print("1", df[df["cluster median"]==1]["median"].max())
print("2", df[df["cluster median"]==2]["median"].min())
print("2", df[df["cluster median"]==2]["median"].max())
print("3", df[df["cluster median"]==3]["median"].min())
print("3", df[df["cluster median"]==3]["median"].max())
print("4", df[df["cluster median"]==4]["median"].min())
print("4", df[df["cluster median"]==4]["median"].max())

0 0.50746522
0 3.1811998
1 3.2185988
1 5.2571595
2 5.26583
2 7.097891499999999
3 7.1013374
3 9.267637
4 9.288853
4 12.8823685

In [237]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,median,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.678292,0
1,RDBECOLIPMC00539,ybaB,b0471,sigma24,cgcgacccgtgggcggcacaggtgagccaactttcgctaccaaaac...,S,CAACTTTCGCTACCAAAACTGGTCGAA,0.0,0.0,8.893792,0
2,RDBECOLIPMC03716,ytjB,b4387,NaN,taacgcatgaggctaccttgtatccattgcttctggcaacattaag...,S,NaN,1.0,0.0,4.633977,0
3,RDBECOLIPMC00555,yohJ,b2141,NaN,caaagagggattgctgcaaactgcaatccctctctatgcttgatgt...,W,NaN,0.0,1.0,4.046088,0
4,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,7.348328,0
...,...,...,...,...,...,...,...,...,...,...,...
1067,RDBECOLIPMC02961,rimP,b3170,sigma70,ttcaaatccggcccccgcaaccactttcccttagagtcctttttca...,C,TTCCCTTAGAGTCCTTTTTCAAATATACT,1.0,1.0,8.423423,0
1068,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,3.488626,0
1069,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,6.609474,0
1070,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.234745,0
1071,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.397496,0

### Save dataset

In [276]:
df.to_csv("dataframes/17_df_allsigma_low_medium_cv_k-means5.csv", index=False)

## Low and medium CV and Sigma70, mode

### Low and medium CV

In [20]:
## genes with low and medium CV

genes_subset = list(df_geneExpression_statistics[(df_geneExpression_statistics["cluster cv"]==0) | (df_geneExpression_statistics["cluster cv"]==1)]["locus tag"].values)

df_geneExpression_subset = df_geneExpression[genes_subset]

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0011,...,b4725,b4729,b4735,b4737,b4740,b4742,b4743,b4744,b4751,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,1.635656,...,6.981666,3.414025,9.433344,2.344123,3.437496,7.137727,5.265698,2.779449,5.559890,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,2.170886,...,6.902602,3.460030,9.368557,1.600958,3.260379,7.253462,4.894757,4.213492,5.638994,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,2.767142,...,6.578612,2.402150,8.036826,2.298669,3.249260,5.125056,6.477672,3.241691,4.309421,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,2.238453,...,6.472961,1.748576,7.634247,2.155117,3.445236,5.354380,6.569912,5.600386,4.301115,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,2.014957,...,6.917032,2.256099,9.170651,0.821856,2.903060,6.391959,5.558479,3.654893,5.117821,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,2.506075,...,7.017253,3.074976,9.090410,1.327401,3.780517,4.114063,5.924942,4.111593,4.735521,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,1.266167,...,8.225574,2.697835,9.999464,1.527276,3.669952,5.135280,5.460251,9.114042,5.723015,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,2.065161,...,7.722098,2.597704,10.095544,0.824001,3.296394,4.836078,4.364785,9.397053,5.609553,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,1.959288,...,7.218039,2.607075,8.365892,2.969313,1.699004,3.483538,2.837202,1.589891,5.107107,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,2.538160,...,7.106772,2.496721,9.360890,2.691794,2.923249,4.385632,3.961997,3.345654,5.259949,4.979692

In [29]:
## mode values of the expression of the selected genes

df_geneExpression_subset_modes = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "mode": df_geneExpression_subset.mode().mean().values})
df_geneExpression_subset_modes

     locus tag       mode
0        b0002  10.666804
1        b0003  10.293287
2        b0004  10.199198
3        b0005   6.842348
4        b0006   6.530679
...        ...        ...
4087     b4742   0.000000
4088     b4743   0.000000
4089     b4744   1.645182
4090     b4751   5.183528
4091     b4756   4.911260

[4092 rows x 2 columns]

### Sigma70 promoters

In [43]:
df = df_promoters_reduced[df_promoters_reduced["Sigma factor"]=="sigma70"]

In [44]:
## drop duplicated in locus tag

df[df.duplicated(subset="locus tag", keep=False)].index

df= df.drop(df[df.duplicated(subset="locus tag", keep=False)].index)

In [45]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor
1,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,1.0,0.0
5,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0
12,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0
16,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,1.0,0.0
18,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0
...,...,...,...,...,...,...,...,...,...
3685,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0
3698,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0
3703,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0
3706,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0
3708,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0

In [46]:
df = pd.merge(df, df_geneExpression_subset_modes, on="locus tag")

In [47]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.856762
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,8.794103
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.444932
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.347304
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.004269
...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,4.006688
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.280023
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,7.188195
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.653280
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.578791

In [48]:
df = pd.merge(df, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [49]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,mode,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.856762,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,8.794103,0
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.444932,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.347304,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.004269,0
...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,4.006688,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.280023,0
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,7.188195,0
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.653280,0
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.578791,0

In [50]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df[['mode']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df['cluster mode'] = kmeans.labels_

In [51]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,mode,cluster cv,cluster mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.856762,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,8.794103,0,2
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.444932,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.347304,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.004269,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,4.006688,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.280023,0,1
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,7.188195,0,1
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.653280,0,1
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.578791,0,1

In [53]:
print("0", df[df["cluster mode"]==0]["mode"].min())
print("0", df[df["cluster mode"]==0]["mode"].max())
print("1", df[df["cluster mode"]==1]["mode"].min())
print("1", df[df["cluster mode"]==1]["mode"].max())
print("2", df[df["cluster mode"]==2]["mode"].min())
print("2", df[df["cluster mode"]==2]["mode"].max())

0 0.0
0 4.1422678
1 4.1592042
1 7.48486365
2 7.505895
2 13.480670499999999

In [54]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,activator,repressor,mode,cluster cv,cluster mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,1.0,0.0,6.856762,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,0.0,1.0,8.794103,0,2
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,1.0,0.0,5.444932,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,0.0,1.0,3.347304,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,1.0,1.0,10.004269,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
615,RDBECOLIPMC03147,yceJ,b1057,sigma70,atcattcaatttgttatttttgtgttgcaattcattctccgacacg...,W,TTGCAATTCATTCTCCGACACGCCATTTT,0.0,0.0,4.006688,0,0
616,RDBECOLIPMC03675,dnaA,b3702,sigma70,ataaatcgggaaaatctgtgagaaacagaagatctcttgcgcagtt...,S,AGATCTCTTGCGCAGTTTAGGCTATGAT,1.0,1.0,7.280023,0,1
617,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,1.0,1.0,7.188195,0,1
618,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,1.0,1.0,5.653280,0,1
619,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,1.0,0.0,6.578791,0,1

#### Save dataset

In [56]:
df.to_csv("dataframes/18_df_sigma70_low_medium_cv_mode.csv", index=False)

### All Sigma70 promoters

In [59]:
df = df_promoters_reduced[df_promoters_reduced["Sigma factor"]=="sigma70"]

In [62]:
df.drop(index=df[df['phisite score'] == 'Unmatched'].index, inplace=True)

In [ ]:
## drop duplicated in locus tag

df[df.duplicated(subset="locus tag", keep=False)].index

df= df.drop(df[df.duplicated(subset="locus tag", keep=False)].index)

In [63]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score
0,RDBECOLIPMC03869,serX,b1032,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,W,TTGACCTCAGGTCATGATTTCCCTAAATT,6.63
1,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68
2,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63
3,RDBECOLIPMC03856,proL,b2189,sigma70,atcagttagcgaaatatcttacttgcaatcggtgtggaaaacggta...,W,TTGCAATCGGTGTGGAAAACGGTAGTATTAG,5.56
4,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95
...,...,...,...,...,...,...,...,...
1119,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43
1120,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78
1121,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19
1122,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96
1123,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14

In [64]:
df_geneExpression_subset = df_geneExpression.drop(columns='index')

df_geneExpression_subset

,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,b0010,b0011,...,b4740,b4742,b4743,b4744,b4745,b4747,b4748,b4751,b4755,b4756
0,10.260570,9.920278,9.936694,7.027514,6.537183,3.043208,10.664771,5.818691,4.654060,1.635656,...,3.437496,7.137727,5.265698,2.779449,1.484198,1.238282,0.000000,5.559890,2.164426,4.553727
1,10.368555,10.044224,10.010638,7.237449,6.452700,2.933902,10.702458,6.109742,4.779633,2.170886,...,3.260379,7.253462,4.894757,4.213492,0.000000,0.000000,0.000000,5.638994,2.634758,3.824146
2,11.193605,11.045581,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,3.689891,2.767142,...,3.249260,5.125056,6.477672,3.241691,0.000000,0.000000,0.000000,4.309421,5.021240,2.602982
3,11.404162,11.460139,10.330368,5.854518,6.387164,3.264503,10.388623,6.110583,3.699180,2.238453,...,3.445236,5.354380,6.569912,5.600386,0.000000,0.000000,0.000000,4.301115,5.655869,2.037598
4,10.497016,10.374824,9.876910,6.950936,6.321764,3.091241,10.540921,5.821780,4.379725,2.014957,...,2.903060,6.391959,5.558479,3.654893,1.011007,0.821856,0.000000,5.117821,2.097149,4.222657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,10.808621,10.161210,9.998448,6.452578,6.472753,3.305636,10.349686,5.310376,3.882960,2.506075,...,3.780517,4.114063,5.924942,4.111593,0.000000,0.811266,0.000000,4.735521,0.000000,5.760310
162,9.917893,10.004788,9.746955,7.738543,5.375955,2.880520,9.595741,5.297445,4.160163,1.266167,...,3.669952,5.135280,5.460251,9.114042,0.500741,2.048708,3.720950,5.723015,1.652536,4.586060
163,10.049220,10.034962,9.847780,7.863723,5.608833,2.904712,9.614549,5.501834,4.018498,2.065161,...,3.296394,4.836078,4.364785,9.397053,0.593973,2.029006,4.649763,5.609553,1.211601,4.349993
164,10.639470,10.269375,10.192219,6.831792,6.505559,2.651878,10.615775,5.761955,4.905267,1.959288,...,1.699004,3.483538,2.837202,1.589891,0.496411,1.517615,1.226617,5.107107,1.043326,4.842827
165,10.694139,10.317198,10.206178,6.852904,6.555798,2.880311,10.639299,5.672740,5.066664,2.538160,...,2.923249,4.385632,3.961997,3.345654,0.000000,1.146389,0.726571,5.259949,0.602462,4.979692

In [65]:
df_geneExpression_subset_modes = pd.DataFrame({"locus tag": df_geneExpression_subset.columns, "mode": df_geneExpression_subset.mode().mean().values})
df_geneExpression_subset_modes

     locus tag       mode
0        b0002  10.666804
1        b0003  10.293287
2        b0004  10.199198
3        b0005   6.842348
4        b0006   6.530679
...        ...        ...
4251     b4747   0.000000
4252     b4748   0.000000
4253     b4751   5.183528
4254     b4755   0.000000
4255     b4756   4.911260

[4256 rows x 2 columns]

In [66]:
df = pd.merge(df, df_geneExpression_subset_modes, on="locus tag")

In [67]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score,mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68,6.856762
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63,8.794103
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95,5.444932
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,5.65,3.347304
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,5.17,10.004269
...,...,...,...,...,...,...,...,...,...
991,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43,6.568758
992,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78,5.653280
993,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19,6.568758
994,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96,6.578791
995,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14,7.188195

In [68]:
df = pd.merge(df, df_geneExpression_statistics[["locus tag", "cluster cv"]], on="locus tag")

In [69]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score,mode,cluster cv
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68,6.856762,0
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63,8.794103,0
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95,5.444932,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,5.65,3.347304,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,5.17,10.004269,0
...,...,...,...,...,...,...,...,...,...,...
991,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43,6.568758,0
992,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78,5.653280,0
993,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19,6.568758,0
994,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96,6.578791,0
995,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14,7.188195,0

In [70]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df[['mode']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df['cluster mode'] = kmeans.labels_

In [71]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score,mode,cluster cv,cluster mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68,6.856762,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63,8.794103,0,2
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95,5.444932,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,5.65,3.347304,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,5.17,10.004269,0,2
...,...,...,...,...,...,...,...,...,...,...,...
991,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43,6.568758,0,1
992,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78,5.653280,0,1
993,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19,6.568758,0,1
994,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96,6.578791,0,1
995,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14,7.188195,0,1

In [72]:
print("0", df[df["cluster mode"]==0]["mode"].min())
print("0", df[df["cluster mode"]==0]["mode"].max())
print("1", df[df["cluster mode"]==1]["mode"].min())
print("1", df[df["cluster mode"]==1]["mode"].max())
print("2", df[df["cluster mode"]==2]["mode"].min())
print("2", df[df["cluster mode"]==2]["mode"].max())

0 0.0
0 4.2880006999999996
1 4.320224550000001
1 7.80999385
2 7.8683755
2 14.1038235

In [37]:
df["cluster mode"] = df["cluster mode"].apply(lambda x: "a" if x==1 else x)
df["cluster mode"] = df["cluster mode"].apply(lambda x: "b" if x==2 else x)
df["cluster mode"] = df["cluster mode"].apply(lambda x: "c" if x==0 else x)

In [38]:
df["cluster mode"] = df["cluster mode"].apply(lambda x: 0 if x=="a" else x)
df["cluster mode"] = df["cluster mode"].apply(lambda x: 1 if x=='b' else x)
df["cluster mode"] = df["cluster mode"].apply(lambda x: 2 if x=='c' else x)

In [73]:
df

,Promoter ID,TU first gene,locus tag,Sigma factor,Promoter sequence,Promoter confidence,promoter sequence reduced,phisite score,mode,cluster cv,cluster mode
0,RDBECOLIPMC03546,folA,b0048,sigma70,ttcctcaacatcatcctcgcaccagtcgacgacggtttacgcttta...,W,GTCGACGACGGTTTACGCTTTACGTATAGT,5.68,6.856762,0,1
1,RDBECOLIPMC03433,argD,b3359,sigma70,tttcctgcatcgctgatttctgattgccatttagtgattttttatg...,W,TTGCCATTTAGTGATTTTTTATGCATATTTT,6.63,8.794103,0,2
2,RDBECOLIPMC00440,cusC,b0572,sigma70,tgacaattttgtcatttttctgtcaccggaaaatcagagcctggcg...,S,GTCACCGGAAAATCAGAGCCTGGCGAGTAAAGT,2.95,5.444932,1,1
3,RDBECOLIPMC00480,chiA,b3338,sigma70,ttttaatgccgtaatttaattcatattgaagggttctcgtaaaacg...,S,TTGAAGGGTTCTCGTAAAACGTAAATAAT,5.65,3.347304,0,0
4,RDBECOLIPMC03416,purA,b4177,sigma70,ggtcatttttgagtgcaaaaagtgctgtaactctgaaaaagcgatg...,S,CTGTAACTCTGAAAAAGCGATGGTAGAAT,5.17,10.004269,0,2
...,...,...,...,...,...,...,...,...,...,...,...
991,RDBECOLIPMC00234,pstB,b3725,sigma70,agaggggcgaggggaccgaccgagcgcctttttgactctgtacacg...,W,TTTTTGACTCTGTACACGGTTAACACT,3.43,6.568758,0,1
992,RDBECOLIPMC00511,pstC,b3727,sigma70,cggggctaaacaggcgaacgacctggattacgccagcctgccggat...,S,CTGGATTACGCCAGCCTGCCGGATAGTGT,2.78,5.653280,0,1
993,RDBECOLIPMC00512,pstB,b3725,sigma70,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,S,TTCTGGCGCGCGTTGTTTTTGCGAAGAAT,4.19,6.568758,0,1
994,RDBECOLIPMC00513,phoU,b3724,sigma70,ggctgcgcgttgttccgaccacacggcgtttatgtacctgggcgaa...,S,CGGCGTTTATGTACCTGGGCGAATTGATTGA,2.96,6.578791,0,1
995,RDBECOLIPMC03521,pstS,b3728,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,S,TTACATATAACTGTCACCTGTTTGTCCTATTTT,3.14,7.188195,0,1

In [74]:
from sklearn.cluster import KMeans

# Seleccionar la métrica de variabilidad (por ejemplo, desviación estándar o coeficiente de variación)
X = df[['phisite score']]

# Aplicar K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

# Añadir las etiquetas de los clusters al DataFrame original
df['cluster phiscore'] = kmeans.labels_

In [76]:
print("0", df[df["cluster phiscore"]==0]["phisite score"].min())
print("0", df[df["cluster phiscore"]==0]["phisite score"].max())
print("1", df[df["cluster phiscore"]==1]["phisite score"].min())
print("1", df[df["cluster phiscore"]==1]["phisite score"].max())
print("2", df[df["cluster phiscore"]==2]["phisite score"].min())
print("2", df[df["cluster phiscore"]==2]["phisite score"].max())

0 3.89
0 5.56
1 5.57
1 9.1
2 0.71
2 3.88

In [78]:
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: "a" if x==2 else x)
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: "b" if x==0 else x)
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: "c" if x==1 else x)

In [79]:
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: 0 if x=="a" else x)
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: 1 if x=='b' else x)
df["cluster phiscore"] = df["cluster phiscore"].apply(lambda x: 2 if x=='c' else x)

#### Save dataset

In [81]:
df.to_csv("dataframes/20_df_all-sigma70_mode_phiscore.csv", index=False)